force-app/main/default/objects/Country_Price__c/Country_Price__c.object-meta.xml
<CustomObject>
    <label>Country Price</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Country Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Price__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Country Prices</relationshipLabel>
    <relationshipName>Country_Prices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/price_for_deadline_2__c.field-meta.xml
<CustomField>
    <fullName>price_for_deadline_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2020-03-28_2020-09-30</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Type_of_Group__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Group__c</fullName>
    <label>Type of Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Sub-committee</fullName>
            </value>
            <value>
                <fullName>Task Force</fullName>
            </value>
            <value>
                <fullName>Scientific Panels</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Scientific Panel</fullName>
                <isActive>false</isActive>
                <label>Scientific Panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/GroupChatterGroupAssotiation__c.object-meta.xml
<CustomObject>
    <label>Working Group Membership</label>
    <nameField>
        <displayFormat>IGM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Working Group Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Working Groups</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Working Group Memberships</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Type_of_Group__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Group__c</fullName>
    <label>Type of Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_date__c</fullName>
    <label>Assignment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Indicates if this membership is active. This field use formula. The membership won&apos;t be active in this year if it expires in next one.</description>
    <formula>IF( Endless_Activation__c  = true, true, Expiration_date__c &gt;= DATETIMEVALUE( TODAY() ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SetMembershipsFlagsOnContactBatch.cls
global class SetMembershipsFlagsOnContactBatch implements Database.Batchable<sObject>, Database.Stateful {
    global Log__c log = new Log__c();
    global List<Date> deadline1 = new List<Date>();
    global Set<String> unSuccessUpdate = new Set<String>();
    global Database.QueryLocator start(Database.BatchableContext bc) {
        log.Process_Name__c='Batch: SetMembershipsFlagsOnContactBatch';
        log.Start_Time__c=Datetime.now();
        log.Status__c='In Progress';
        insert log;
        log.Status__c='Completed';
        log.Message__c='';

        //Determine borders of first deadline
        String label = Schema.getGlobalDescribe().get('Country_Price__c').getDescribe().fields.getMap().get('price_for_deadline_2__c').getDescribe().getLabel();
        List<String> dates = label.split('_');
        deadline1.add(Date.valueOf(dates[0]));
        deadline1.add(Date.valueOf(dates[dates.size() - 1]));
        return Database.getQueryLocator(
                'SELECT Id, Email, Flag_EAN_Full_Member__c, Flag_EAN_Corresponding_Member__c, Flag_EAN_Fellow_of_the_EAN__c, ' +
                        'Flag_EAN_Resident_Research_Member__c, Flag_EAN_Associate_Member__c, Flag_EAN_Student_Member__c, ' +
                        'Flag_EAN_New_Member__c, Flag_EAN_Associate_Corresponding_Member__c ' +
                        'FROM Contact'
        );
    }
    global void execute(Database.BatchableContext bc, List<Contact> records) {
        try {
            List<MembershipContactAssotiation__c> contactsMemberships = [SELECT Id, IsActive__c, Membership__r.API__c, Contact__c, Assignment_date__c FROM MembershipContactAssotiation__c WHERE Contact__c IN:records];
            List<GroupChatterGroupAssotiation__c> contactsGroups = [SELECT Group__r.Type_of_Group__c, Type_of_Group__c FROM GroupChatterGroupAssotiation__c WHERE Contact__c IN :records];

            List<User> users = [SELECT Id, Email, ContactId FROM User WHERE ContactId IN :records];
            Map<String, String> contactIdEmailMap = new Map<String, String>();
            for(User u : users){
                contactIdEmailMap.put(u.ContactId, u.Email);
            }

            for (Contact contact : records) {
                contact.Flag_EAN_Full_Member__c = false;
                contact.Flag_EAN_Corresponding_Member__c = false;
                contact.Flag_EAN_Fellow_of_the_EAN__c = false;
                contact.Flag_EAN_Resident_Research_Member__c = false;
                contact.Flag_EAN_Associate_Member__c = false;
                contact.Flag_EAN_Student_Member__c = false;
                contact.Flag_EAN_New_Member__c = false;
                contact.Flag_EAN_Associate_Corresponding_Member__c = false;
                for (MembershipContactAssotiation__c membershipStatus : contactsMemberships) {
                    if (membershipStatus.Contact__c == contact.Id && membershipStatus.IsActive__c) {
                        if (membershipStatus.Membership__r.API__c == 'full_membership') {
                            contact.Flag_EAN_Full_Member__c = true;
                        } else if (membershipStatus.Membership__r.API__c == 'corresponding_membership') {
                            contact.Flag_EAN_Corresponding_Member__c = true;
                        } else if (membershipStatus.Membership__r.API__c == 'fellow_membership') {
                            contact.Flag_EAN_Fellow_of_the_EAN__c = true;
                        } else if (membershipStatus.Membership__r.API__c == 'resident_and_research_membership') {
                            contact.Flag_EAN_Resident_Research_Member__c = true;
                        } else if (membershipStatus.Membership__r.API__c == 'associate_individual_membership') {
                            contact.Flag_EAN_Associate_Member__c = true;
                        } else if (membershipStatus.Membership__r.API__c == 'student_membership') {
                            contact.Flag_EAN_Student_Member__c = true;
                        } else if (membershipStatus.Membership__r.API__c == 'associate_corresponding_membership') {
                            contact.Flag_EAN_Associate_Corresponding_Member__c = true;
                        }
                        if(membershipStatus.Assignment_date__c>= deadline1[0] && membershipStatus.Assignment_date__c<=deadline1[1]){
                            contact.Flag_EAN_New_Member__c = true;
                        }
                    }
                }
                if(contact.Email==null){
                    contact.Email = contactIdEmailMap.get(contact.Id);
                }
            }

            Database.SaveResult[] srLis = Database.update(records, false);
            for(Database.SaveResult sr : srLis){
                if(!sr.isSuccess()){
                    unSuccessUpdate.add(sr.getId());
                }
            }
            List<GroupChatterGroupAssotiation__c> groupRolesToUpdate = new List<GroupChatterGroupAssotiation__c>();
            for (GroupChatterGroupAssotiation__c groupRole : contactsGroups) {
                if (groupRole.Group__c != null && groupRole.Group__r.Type_of_Group__c != groupRole.Type_of_Group__c) {
                    groupRole.Type_of_Group__c = groupRole.Group__r.Type_of_Group__c;
                    groupRolesToUpdate.add(groupRole);
                }
            }
            if (!groupRolesToUpdate.isEmpty()) {
                update groupRolesToUpdate;
            }
        }catch (Exception e){
            log.Message__c+=e.getMessage()+'\n';
            log.Status__c='Error';
        }
    }
    global void finish(Database.BatchableContext bc) {
        log.End_Time__c = Datetime.now();
        log.Message__c+='NOT UPDATED CONTACTS: '+String.join(new List<String>(unSuccessUpdate),',');
        update log;
    }
}