force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Form_Status__c</fullName>
    <label>Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <description>If student, attach student ID card</description>
    <label>Profession</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neurologist</fullName>
            </value>
            <value>
                <fullName>Residents/Physician in training</fullName>
                <label>Resident/physician in training</label>
            </value>
            <value>
                <fullName>Research Fellows in Neurology</fullName>
                <label>Research fellow in neurology</label>
            </value>
            <value>
                <fullName>PhD student in neurology</fullName>
            </value>
            <value>
                <fullName>Undergraduate Medical Student</fullName>
                <label>Undergraduate medical student</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Neurologist working in Pharma</fullName>
                <label>Neurologist working in pharma</label>
            </value>
            <value>
                <fullName>PhD students in neurology</fullName>
                <isActive>false</isActive>
                <label>PhD students in neurology</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <label>Country of Residence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/ZIP_Postal_code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Postal_code__c</fullName>
    <label>ZIP/Postal code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Application_form__c.field-meta.xml
<CustomField>
    <fullName>Application_form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application form</label>
    <referenceTo>Application_form__c</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date when current membership expires</description>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssignMembershipHelper_Test.cls
@IsTest
public with sharing class AssignMembershipHelper_Test {
    @TestSetup public static void setup(){
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@eamil.com');
        insert contact;
        Membership__c membership = new Membership__c(Name = 'Test Membership', API__c = 'test_membership');
        insert membership;
        Application_form__c appForm = new Application_form__c(
                First_name__c = 'Test', Last_name__c = 'Contact', Date_of_birth__c = Date.today(),
                Gender__c = 'Male', Email__c = 'test@email.com', Nationality__c = 'United States',
                Residency__c = 'United States', ZIP_Postal_code__c = '111', City__c = 'Test', Contact__c = contact.Id, Membership__c = membership.Id,
                Profession__c = 'Other', Street__c = 'TestStreet', Form_Status__c = 'Draft');
        insert appForm;
    }
    @IsTest public static void assignMembershipTest(){
        Application_form__c appForm = [SELECT Id, Form_Status__c FROM Application_form__c WHERE Contact__r.Name = 'Test Contact' AND Membership__r.API__c='test_membership'];
        appForm.Form_Status__c = 'Approved';
        System.assertEquals(0, [SELECT count() FROM MembershipContactAssotiation__c WHERE Application_form__c = :appForm.Id]);
        update appForm;
        List<MembershipContactAssotiation__c> memStatus = [SELECT Expiration_date__c, Membership__r.API__c FROM MembershipContactAssotiation__c WHERE Application_form__c = :appForm.Id LIMIT 1];
        System.assertEquals(Date.newInstance(Date.today().year()+1,12,31), memStatus[0].Expiration_date__c);
        System.assertEquals('test_membership', memStatus[0].Membership__r.API__c);
    }
    @IsTest public static void documentsMissingEmailCheckTest(){
        Application_form__c appForm = [SELECT Id, Form_Status__c FROM Application_form__c WHERE Contact__r.Name = 'Test Contact' AND Membership__r.API__c='test_membership'];
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(appForm.Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(req1);
        System.assert(result.isSuccess());
        Test.startTest();
        appForm.Form_Status__c = 'Further Information Required';
        update appForm;
        Test.stopTest();
        System.assertEquals('Further Information Required', [SELECT Id, Form_Status__c FROM Application_form__c WHERE Id =:appForm.Id].Form_Status__c);
    }
    @IsTest public static void documentsMissingEmailCheckErrorTest(){
        Application_form__c appForm = [SELECT Id, Form_Status__c, Contact__r.Email FROM Application_form__c WHERE Contact__r.Name = 'Test Contact' AND Membership__r.API__c='test_membership'];
        appForm.Contact__r.Email = '';
        update appForm.Contact__r;
        Approval.lock(appForm.Id);
        System.debug('isLocked:: '+Approval.isLocked(appForm.Id));
        Test.startTest();
        appForm.Form_Status__c = 'Further Information Required';
        update appForm;
        Test.stopTest();
        System.assertEquals('Further Information Required', [SELECT Id, Form_Status__c FROM Application_form__c WHERE Id =:appForm.Id].Form_Status__c);
    }
    @IsTest public static void rejectionLetterEmailCheckTest(){
        Application_form__c appForm = [SELECT Id, Form_Status__c FROM Application_form__c WHERE Contact__r.Name = 'Test Contact' AND Membership__r.API__c='test_membership'];
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(appForm.Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(req1);
        System.assert(result.isSuccess());
        Test.startTest();
        appForm.Form_Status__c = 'Declined';
        update appForm;
        Test.stopTest();
        System.assertEquals('Declined', [SELECT Id, Form_Status__c FROM Application_form__c WHERE Id =:appForm.Id].Form_Status__c);
    }


}