force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/AAN_Member__c.field-meta.xml
<CustomField>
    <fullName>AAN_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I am AAN Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Expected_Date_Of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_Graduation__c</fullName>
    <inlineHelpText>Please indicate the actual or expected date of graduation for your most recent degree.</inlineHelpText>
    <label>Date of Graduation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Form_Status__c</fullName>
    <label>Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/License_issued__c.field-meta.xml
<CustomField>
    <fullName>License_issued__c</fullName>
    <inlineHelpText>Please indicate the actual or expected date of issue of the license to practice medicine.</inlineHelpText>
    <label>License issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment &amp; Invoice</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Applications Forms</relationshipLabel>
    <relationshipName>Applications_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <label>Country of Residence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Retired__c.field-meta.xml
<CustomField>
    <fullName>Retired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I am Retired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Form__mdt/Contact_Form__mdt.object-meta.xml
<CustomObject>
    <label>Contact-Form</label>
    <pluralLabel>Contact-Form</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Form__mdt/fields/Contact_field__c.field-meta.xml
<CustomField>
    <fullName>Contact_field__c</fullName>
    <label>Contact_field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Form__mdt/fields/Form_field__c.field-meta.xml
<CustomField>
    <fullName>Form_field__c</fullName>
    <label>Form field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/Country_code__c.field-meta.xml
<CustomField>
    <fullName>Country_code__c</fullName>
    <label>Country code alpha2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/is_in_europe__c.field-meta.xml
<CustomField>
    <fullName>is_in_europe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is_in_europe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/member_country__c.field-meta.xml
<CustomField>
    <fullName>member_country__c</fullName>
    <defaultValue>false</defaultValue>
    <label>member_country</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country_Price__c/Country_Price__c.object-meta.xml
<CustomObject>
    <label>Country Price</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Country Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Price__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Country Prices</relationshipLabel>
    <relationshipName>Country_Prices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/price_for_deadline_1__c.field-meta.xml
<CustomField>
    <fullName>price_for_deadline_1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2020-01-01_2020-03-27</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/price_for_deadline_2__c.field-meta.xml
<CustomField>
    <fullName>price_for_deadline_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2020-03-28_2020-09-30</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/price_for_deadline_3__c.field-meta.xml
<CustomField>
    <fullName>price_for_deadline_3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2020-10-01_2020-12-31</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/isForUpdateMembershipApplication__c.field-meta.xml
<CustomField>
    <fullName>isForUpdateMembershipApplication__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if current membership is available for &quot;Update Membership Application&quot;.</description>
    <label>For Update Membership Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/www__c.field-meta.xml
<CustomField>
    <fullName>www__c</fullName>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Purchase_Type__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Type__c</fullName>
    <description>Actual for memberships invoices</description>
    <label>Purchase Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <label>Total amount</label>
    <summarizedField>Order_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount_Gros__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Gros__c</fullName>
    <formula>Total_amount__c + VAT_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Gros</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Total_amount__c</fullName>
        <formula>(Quantity__c *  Amount__c) + Discount_Amount__c</formula>
        <label>Total amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/membershipApplicationController.cls
public with sharing class membershipApplicationController {
    @AuraEnabled public static membershipApplicationWrapper getMemberships() {
        List<Membership__c> allmembrs = [SELECT Id, Name, API__c, isForUpdateMembershipApplication__c,
                www__c, (SELECT Id, Membership__c, Region__c, Price_for_Deadline_1__c,
                Price_for_Deadline_2__c, Price_for_Deadline_3__c FROM Country_Prices1__r) FROM Membership__c];
        List<Country_Price__c> countryPrices = new List<Country_Price__c>();
        for (Membership__c m : allmembrs) {
            for (Country_Price__c cp : m.Country_Prices1__r) {
                cp.Region__c = cp.Region__c == null ? 'Default' : cp.Region__c;
                countryPrices.add(cp);
            }
        }
        User user = [SELECT Contact.Id FROM User WHERE Id = :UserInfo.getUserId()];
        Contact cont = getContactForFormById(user.Contact.Id);
        List<Contact_Form__mdt> cf = [SELECT Id, Contact_field__c, Form_field__c FROM Contact_Form__mdt];
        List<Product2> product2s = [SELECT Id, Name, Product_use__c, IsActive, Description, (SELECT Id, Name, UnitPrice, Pricebook2.Name FROM PricebookEntries WHERE Pricebook2.IsActive=true) FROM Product2 WHERE Product_use__c INCLUDES ('Membership Application') AND IsActive = true];
        membershipApplicationWrapper wrapper = new membershipApplicationWrapper(
                allmembrs,
                countryPrices,
                cont,
                cf,
                product2s);
        return wrapper;
    }
    @AuraEnabled public static Contact getContactForFormById(String Id) {
        List<String> contactFieldForForm = new List<String>();
        for (Schema.FieldSetMember f : SObjectType.Contact.FieldSets.Form_fields.getFields()) {
            contactFieldForForm.add(f.getFieldPath());
        }
        String fields = String.join(contactFieldForForm, ',');
        List<Contact> cont = Database.query('SELECT ' + fields + ' FROM Contact WHERE Id=\'' + Id + '\'');
        return cont[0];
    }
    @AuraEnabled public static List<Country__mdt> getCountries() {
        List<Country__mdt> allCountries = [SELECT Id, Country__c, Country_code__c, Region__c, Label, is_in_europe__c, member_country__c FROM Country__mdt ORDER BY Label ASC];
        return allCountries;
    }
    @AuraEnabled public static List<List<String>> getFieldSets() {
        List<List<String>> allFieldSets = new List<List<String>>();
        List<String> firstFieldSet = new List<String>();
        for (Schema.FieldSetMember f : SObjectType.Application_form__c.FieldSets.Membership_application_form_part1.getFields()) {
            firstFieldSet.add(f.getFieldPath());
        }
        allFieldSets.add(firstFieldSet);

        List<String> secondFieldSet = new List<String>();
        for (Schema.FieldSetMember f : SObjectType.Application_form__c.FieldSets.Membership_application_form_part2.getFields()) {
            secondFieldSet.add(f.getFieldPath());
        }
        allFieldSets.add(secondFieldSet);
        return allFieldSets;
    }
    @AuraEnabled public static Application_form__c upsertForm(Application_form__c form) {
        try {
            upsert form;
            return form;
        } catch (Exception e) {
            String err = e.getMessage();
            if(err.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'))
            {
                List<String> tempErr = err.split('FIELD_CUSTOM_VALIDATION_EXCEPTION,');
                err = tempErr[1];
            }
            System.debug('err:: '+err);
            throw new AuraException(err);
        }
    }
    @AuraEnabled public static void updateContact(Contact contact) {
        try {
            update contact;
        } catch (Exception e) {
            String err = e.getMessage();
            if(err.contains('[Birthdate]')){
                err = 'Birthday cannot be in future.';
            } else if(err.contains('already exists')){
                err = 'A user account with this email address already exists. If you need further assistance, please contact headoffice@ean.org.';
            }
            AuraHandledException error = new AuraHandledException(err);
            error.setMessage(err);
            System.debug('err:: '+err);
            throw error;
        }
    }
    @AuraEnabled public static String getDeadline() {
        String deadline;
        Schema.DescribeSObjectResult cp = Country_Price__c.sObjectType.getDescribe();
        Map<String, Schema.SObjectField> fieldsMap = cp.fields.getMap();
        for (String fieldName : fieldsMap.keySet()) {
            if (fieldName.contains('deadline')) {
                String label = Schema.getGlobalDescribe().get('Country_Price__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                List<String> dates = label.split('_');
                Date start = Date.valueOf(dates[0]);
                Date finish = Date.valueOf(dates[dates.size() - 1]);
                if (Date.today() >= start && Date.today() <= finish) {
                    deadline = String.valueOf(fieldsMap.get(fieldName));
                }
            }
        }
        return deadline;
    }
    @AuraEnabled public static void submitForApproval(String formId){
        String userId = UserInfo.getUserId();
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setObjectId(formId);
        req1.setSubmitterId(userId);
        Approval.ProcessResult result = Approval.process(req1);
    }
    @AuraEnabled public static void deleteContentDocumentById(String docId){
        List<ContentDocument> cd = [SELECT Id FROM ContentDocument WHERE Id =: docId];
        delete cd;
    }
    @AuraEnabled public static void attachFileToForm(List<ContentDocumentLink> contentDocumentLinks){
        // Checking if cdLink/cdLinks already exist
        List<ContentDocumentLink> linksToInsert = new List<ContentDocumentLink>();
        Boolean queryIsReady = false;
        String query = 'SELECT LinkedEntityId, Visibility, ContentDocumentId, ShareType FROM ContentDocumentLink WHERE ';
        for (ContentDocumentLink c : contentDocumentLinks) {
            query += '(LinkedEntityId = \'' +  c.LinkedEntityId +'\' AND ContentDocumentId = \'' + c.ContentDocumentId + '\') OR ';
        }
        if (query.contains('OR')) {
            query = query.substringBeforeLast('OR');
            queryIsReady = true;
        }
        if (queryIsReady) {
            List<ContentDocumentLink> existingLinks = Database.query(query);
            if(!existingLinks.isEmpty()){
                for (ContentDocumentLink c : contentDocumentLinks) {
                    Boolean isFound = false;
                    for (ContentDocumentLink c2 : existingLinks) {
                        if (c.LinkedEntityId == c2.LinkedEntityId && c.ContentDocumentId == c2.ContentDocumentId) {
                            isFound = true;
                        }
                    }
                    if(!isFound){
                        linksToInsert.add(c);
                    }
                }
            }else{
                linksToInsert = contentDocumentLinks.clone();
            }
        }
        if (!linksToInsert.isEmpty()) {
            insert linksToInsert;
        }
    }
    @AuraEnabled public static Application_form__c getExistedForm(String formId){
        List<List<String>> formFields = getFieldSets();
        String queryFields = '';
        List<String> allFields = new List<String>();
        for(Integer i = 0; i<formFields.size(); i++){
            allFields.addAll(formFields[i]);
        }
        allFields.addAll(new List<String>{'Membership__c', 'Contact__c', 'Nationality__c', 'Residency__c', 'Form_Status__c', 'Expected_Date_Of_Graduation__c', 'License_issued__c', 'AAN_Member__c', 'Retired__c', 'Order__r.Purchase_Type__c' });
        queryFields = String.join(allFields, ',');
        System.debug(queryFields);
        List<Application_form__c> appForm = Database.query('SELECT '+queryFields + ' FROM Application_form__c WHERE Id=:formId');
        if(!appForm.isEmpty()){
//            if(appForm[0].Form_Status__c == 'Further Information Required'){
                return appForm[0];
//            } else {
//                throw new AuraException('This application cannot be re-submitted');
//            }
        } else{
            throw new AuraException('This application wasn\'t found' );
        }

    }
    @AuraEnabled public static List<ContentDocumentLink> getContentDocuments(String LinkedEntityId){
        return [SELECT Id, ContentDocument.Title, ContentDocument.FileExtension FROM ContentDocumentLink WHERE LinkedEntityId=:LinkedEntityId];
    }
    @AuraEnabled public static String getCommunityHomeUrl() {
        String result;
        if (!Test.isRunningTest()) {
            Network myNetwork = [SELECT Id FROM Network WHERE Name = 'ean'];
            ConnectApi.Community myCommunity = ConnectApi.Communities.getCommunity(myNetwork.id);
            result = myCommunity.siteUrl;
        }else {
            result = 'community.com';
        }
        return result;
    }
    @AuraEnabled public static Map<String, Object> getOrderWithItems(String orderId){
        Map<String, Object> mapResult = new Map<String, Object>();
        List<Order__c> order = [SELECT Id, Status__c, Total_amount__c, Total_amount_Gros__c FROM Order__c WHERE Id = :orderId];
        if(!order.isEmpty()){
            mapResult.put('order', order[0]);
            List<Order_Item__c> orderItems = [SELECT Id, Membership__c, Product__c, Amount__c, Quantity__c FROM Order_Item__c WHERE Order_Custom__c = :order[0].Id];
            if(!orderItems.isEmpty()){
                mapResult.put('orderItems', orderItems);
            }
        }
        return mapResult;
    }
}