force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Form_Status__c</fullName>
    <label>Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/Fellowship_Applications_Form__c.object-meta.xml
<CustomObject>
    <label>Fellowship Application (Form)</label>
    <nameField>
        <displayFormat>FAF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowship Applications Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Further information required</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalCommentsController.cls
public without sharing class ApprovalCommentsController {
    @AuraEnabled public static Boolean sObjectCheck(Id recordId){
        if(recordId.getSobjectType().getDescribe().getName() == 'Application_form__c'){
            List<Application_form__c> appForm = [SELECT Id, Form_Status__c FROM Application_form__c WHERE Id =:recordId];
            if(appForm[0].Form_Status__c == 'Further Information Required'){
                return true;
            }else {
                return false;
            }
        } else if(recordId.getSobjectType().getDescribe().getName() == 'Fellowship_Applications_Form__c'){
            List<Fellowship_Applications_Form__c> appForm = [SELECT Id, Approval_Status__c FROM Fellowship_Applications_Form__c WHERE Id =:recordId];
            if(appForm[0].Approval_Status__c == 'Further Information Required'){
                return true;
            }else {
                return false;
            }
        } else {
            return false;
        }
    }
    @AuraEnabled public static String getApprovalComments(Id recordId){
        List<ProcessInstance> recordInstances = [SELECT Id, TargetObjectId FROM ProcessInstance WHERE TargetObjectId =:recordId ORDER BY CreatedDate DESC];
        List<ProcessInstanceStep> instancesSteps = [SELECT Comments, ProcessInstanceId, CreatedDate, OriginalActorId FROM ProcessInstanceStep WHERE ProcessInstanceId =:recordInstances[0].Id ORDER BY CreatedDate DESC];
        if(instancesSteps[0].Comments!=null){
            TimeZone tz = UserInfo.getTimeZone();
            List<User> approver = [SELECT Id, Name, SmallPhotoUrl FROM User WHERE Id=:instancesSteps[0].OriginalActorId];
            System.debug('instancesSteps:: '+instancesSteps[0]);
            Map<String, Object> approvalPost = new Map<String, Object>();
            approvalPost.put('comment', instancesSteps[0].Comments);
            approvalPost.put('approver', approver[0]);
            approvalPost.put('date', instancesSteps[0].CreatedDate.format('MM-dd-yyyy HH:mm:ss'));
            return JSON.serialize(approvalPost);
        } else {
            return 'none';
        }
    }

}