force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Expected_Date_Of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_Graduation__c</fullName>
    <inlineHelpText>Please indicate the actual or expected date of graduation for your most recent degree.</inlineHelpText>
    <label>Date of Graduation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <label>Country of Residence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/ZIP_Postal_code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Postal_code__c</fullName>
    <label>ZIP/Postal code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/GroupChatterGroupAssotiation__c.object-meta.xml
<CustomObject>
    <label>Working Group Membership</label>
    <nameField>
        <displayFormat>IGM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Working Group Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Working Groups</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Working Group Memberships</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Alzheimer Europe representative</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate Editor</fullName>
            </value>
            <value>
                <fullName>Book Review Editor</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>CME Editor</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Chair Communication Committee</fullName>
            </value>
            <value>
                <fullName>Chair Education Committee</fullName>
            </value>
            <value>
                <fullName>Chair Programme Committee</fullName>
            </value>
            <value>
                <fullName>Chair Scientific Committee</fullName>
            </value>
            <value>
                <fullName>Chair Teaching Course sub-Committee</fullName>
            </value>
            <value>
                <fullName>Co-Chair</fullName>
            </value>
            <value>
                <fullName>EANO representative</fullName>
            </value>
            <value>
                <fullName>EAPC representative</fullName>
            </value>
            <value>
                <fullName>EC-IFCN representative</fullName>
            </value>
            <value>
                <fullName>ECTRIMS representative</fullName>
            </value>
            <value>
                <fullName>EFAS representative</fullName>
            </value>
            <value>
                <fullName>EFIC representative</fullName>
            </value>
            <value>
                <fullName>EFNR representative</fullName>
            </value>
            <value>
                <fullName>EHF representative</fullName>
            </value>
            <value>
                <fullName>EQTF Representative</fullName>
            </value>
            <value>
                <fullName>ESO representative</fullName>
            </value>
            <value>
                <fullName>Editor-in-Chief</fullName>
            </value>
            <value>
                <fullName>Ethics Advisor</fullName>
            </value>
            <value>
                <fullName>EuGMS representative</fullName>
            </value>
            <value>
                <fullName>Ex-officio member</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Secretary general</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Application_form__c.field-meta.xml
<CustomField>
    <fullName>Application_form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application form</label>
    <referenceTo>Application_form__c</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Carer</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Corresponding member</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>New Member</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>RRFS Member</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
                <isActive>false</isActive>
                <label>Panel Member (Institution)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CertificatePageControllerTest.cls
@isTest
public with sharing class CertificatePageControllerTest {

    @testSetup
    public static void setup() {
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Id groupRTId = Schema.SObjectType.Group__c.getRecordTypeInfosByName().get('Level 1 Board (EAN Board)').getRecordTypeId();
        Group__c eanBoard = new Group__c(Name = 'TestEanBoard2', RecordTypeId = groupRTId);
        insert  eanBoard;

        Contact contact = new Contact(FirstName = 'Certificate', LastName = 'TestP', Email = 'testCerP@test.com',
                MailingStreet = 'TestStreet', MailingCity = 'TestCity', MailingPostalCode = '11111',
                MailingCountry = 'Germany', Expected_Date_Of_Graduation__c = Date.today(), Salutation = 'Mr.', Residency__c = 'Germany');
        insert contact;

        Contact contact2 = new Contact(FirstName = 'PageTest', LastName = 'President', Email = 'testpagepresident@test.com',
                MailingStreet = 'TestStreet', MailingCity = 'TestCity', MailingPostalCode = '11111',
                MailingCountry = 'Germany');
        insert contact2;

        Contact contact3 = new Contact(FirstName = 'PageTest', LastName = 'Secretary', Email = 'testpagesecretary@test.com',
                MailingStreet = 'TestStreet', MailingCity = 'TestCity', MailingPostalCode = '11111', MailingCountry = 'Germany');
        insert contact3;

        Id groupMemberRTId = Schema.SObjectType.GroupChatterGroupAssotiation__c.getRecordTypeInfosByName().get('Level 1 Board (EAN Board)').getRecordTypeId();
        GroupChatterGroupAssotiation__c gca1 = new GroupChatterGroupAssotiation__c(Contact__c = contact2.Id,
                Group__c = eanBoard.Id, RecordTypeId = groupMemberRTId, Role__c = 'President');
        insert gca1;

        GroupChatterGroupAssotiation__c gca2 = new GroupChatterGroupAssotiation__c(Contact__c = contact3.Id,
                Group__c = eanBoard.Id, RecordTypeId = groupMemberRTId, Role__c = 'Secretary general');
        insert gca2;

        Membership__c membership = new Membership__c(Name = 'Resident and Research Membership', API__c = 'resident_and_research_membership');
        insert  membership;

        Application_form__c appForm = new Application_form__c(
                First_name__c = 'Certificate',
                Last_name__c = 'TestP',
                Date_of_birth__c = Date.today().addYears(-18),
                Gender__c = 'Male',
                Email__c = 'testCerP@test.com',
                Nationality__c = 'Germany',
                Residency__c = 'Germany',
                ZIP_Postal_code__c = '11111',
                City__c = 'TestCity',
                Membership__c = membership.Id,
                Street__c = 'TestStreet',
                Profession__c = 'Neurologist',
                Contact__c = contact.Id);
        insert appForm;
    }

    @isTest
    public static void mergeAllInfoTest() {
        Application_form__c appForm = [SELECT Id FROM Application_form__c WHERE Last_name__c = 'TestP' AND First_name__c = 'Certificate' LIMIT 1];
        Test.startTest();
        appForm.Form_Status__c = 'Approved';
        update appForm;
        Test.stopTest();
        MembershipContactAssotiation__c msStatus = [SELECT Id FROM MembershipContactAssotiation__c WHERE Application_form__c = :appForm.Id];
        List<GroupChatterGroupAssotiation__c>  groupMemberships = [
                SELECT Id, Contact__r.Name, Role__c
                FROM GroupChatterGroupAssotiation__c
                WHERE (Role__c = 'President' OR Role__c = 'Secretary general') AND
                Group__r.RecordType.Name = 'Level 1 Board (EAN Board)'
        ];
        String presidentName;
        String secretaryName;
        for (GroupChatterGroupAssotiation__c g : groupMemberships) {
            if (g.Role__c == 'President') {
                presidentName = g.Contact__r.Name;
            } else if (g.Role__c == 'Secretary general') {
                secretaryName = g.Contact__r.Name;
            }

            if (secretaryName != '' && presidentName != ''){
                break;
            }
        }
        PageReference pageRef = Page.CertificatePage;
        pageRef.getParameters().put('ms', msStatus.Id);
        pageRef.getParameters().put('sn', secretaryName);
        pageRef.getParameters().put('pn', presidentName);
        Test.setCurrentPage(pageRef);
        CertificatePageController controller = new CertificatePageController();
        System.assertEquals('Mr.', controller.salutation);
        System.assertEquals('Certificate TestP', controller.memberName);
        System.assertEquals('Germany', controller.nationality);
        System.assertEquals('Resident and Research Membership', controller.membershipName);

    }
}