force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Form_Status__c</fullName>
    <label>Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <description>If student, attach student ID card</description>
    <label>Profession</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neurologist</fullName>
            </value>
            <value>
                <fullName>Residents/Physician in training</fullName>
                <label>Resident/physician in training</label>
            </value>
            <value>
                <fullName>Research Fellows in Neurology</fullName>
                <label>Research fellow in neurology</label>
            </value>
            <value>
                <fullName>PhD student in neurology</fullName>
            </value>
            <value>
                <fullName>Undergraduate Medical Student</fullName>
                <label>Undergraduate medical student</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Neurologist working in Pharma</fullName>
                <label>Neurologist working in pharma</label>
            </value>
            <value>
                <fullName>PhD students in neurology</fullName>
                <isActive>false</isActive>
                <label>PhD students in neurology</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <label>Country of Residence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/ZIP_Postal_code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Postal_code__c</fullName>
    <label>ZIP/Postal code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellowship__c/Fellowship__c.object-meta.xml
<CustomObject>
    <label>Fellowship</label>
    <nameField>
        <displayFormat>F-{0}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &quot;Clinical_Fellowship&quot;, &quot;Clinical&quot;, IF($RecordType.DeveloperName = &quot;Research_Fellowship&quot;, &quot;Research&quot;, &quot;&quot;)) + &quot; Fellowship &quot; + TEXT(YEAR(TODAY())+1)</defaultValue>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellowship__c/recordTypes/Clinical_Fellowship.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Fellowship</fullName>
    <active>true</active>
    <label>Clinical Fellowship</label>
</RecordType>

force-app/main/default/objects/Fellowship_Applications_Form__c/Fellowship_Applications_Form__c.object-meta.xml
<CustomObject>
    <label>Fellowship Application (Form)</label>
    <nameField>
        <displayFormat>FAF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowship Applications Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Further information required</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fellowship_Applications_Form</relationshipLabel>
    <relationshipName>Clinical_Fellowship_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <label>Fellowship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Research Fellowship Application Form</value>
        </filterItems>
        <filterItems>
            <field>Fellowship__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Research Fellowship</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Fellowship Application Form</value>
        </filterItems>
        <filterItems>
            <field>Fellowship__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Fellowship</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fellowship__c</referenceTo>
    <relationshipLabel>Fellowship_Applications_Form</relationshipLabel>
    <relationshipName>Clinical_Fellowship_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/recordTypes/Clinical_Fellowship_Application_Form.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Fellowship_Application_Form</fullName>
    <active>true</active>
    <label>Clinical Fellowship Application Form</label>
</RecordType>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ApprovalCommentsController_Test.cls
@IsTest
public with sharing class ApprovalCommentsController_Test {
    @TestSetup public static void setup() {
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Account acc = new Account(Name = 'Test');
        insert acc;
        Contact contact = new Contact(LastName = 'test lastname', AccountId = acc.Id);
        insert contact;
        Membership__c membership = new Membership__c(Name = 'Test1', API__c = 'test1');
        insert membership;
        RecordType clinFellRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Fellowship__c' AND DeveloperName = 'Clinical_Fellowship'];
        RecordType clinFellAppFormRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Fellowship_Applications_Form__c' AND DeveloperName = 'Clinical_Fellowship_Application_Form'];
        Fellowship__c fellowship = new Fellowship__c(Name__c = 'Test1', RecordTypeId = clinFellRT.Id);
        insert fellowship;
        Id cclu = [SELECT Id FROM Profile WHERE Name = 'Member Community User Profile'].Id;
        User u = new User(
                Alias = 'test123', Email = 'test123@noemail.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = cclu, Country = 'United States', IsActive = true,
                ContactId = contact.Id, TimeZoneSidKey = 'America/Los_Angeles', Username = 'tester@noemail.com',
                CommunityNickname = 'commnick');
        insert u;
        System.runAs(u){
            Application_form__c appForm = new Application_form__c(
                    First_name__c = 'test', Last_name__c = 'testlast', Date_of_birth__c = Date.today(),
                    Gender__c = 'Male', Email__c = 'email@email.com', Nationality__c = 'United States',
                    Residency__c = 'United States', ZIP_Postal_code__c = '111', City__c = 'Test', Contact__c = contact.Id, Membership__c = membership.Id,
                    Profession__c = 'Other', Street__c = '123Street', Form_Status__c = 'Draft');
            insert appForm;
            Fellowship_Applications_Form__c appFellForm = new Fellowship_Applications_Form__c(Contact__c = contact.Id, Fellowship__c = fellowship.Id, RecordTypeId=clinFellAppFormRT.Id);
            insert appFellForm;
        }

    }
    @IsTest public static void sObjectCheckTest() {
        List<Contact> contact = [SELECT Id FROM Contact WHERE LastName = 'test lastname'];
        List<Application_form__c> appForm = [SELECT Id, OwnerId, Form_Status__c, CreatedById FROM Application_form__c WHERE Contact__c = :contact[0].Id];
        List<Fellowship_Applications_Form__c> appFellForm = [SELECT Id, Approval_Status__c FROM Fellowship_Applications_Form__c WHERE Contact__c = :contact[0].Id];
        Boolean result = ApprovalCommentsController.sObjectCheck(appForm[0].Id);
        System.assertEquals(false, result);
        Boolean result2 = ApprovalCommentsController.sObjectCheck(appFellForm[0].Id);
        System.assertEquals(false, result2);
        appForm[0].Form_Status__c = 'Further Information Required';
        update appForm;
        appFellForm[0].Approval_Status__c = 'Further Information Required';
        update appFellForm;
        result = ApprovalCommentsController.sObjectCheck(appForm[0].Id);
        System.assertEquals(true, result);
        result2 = ApprovalCommentsController.sObjectCheck(appFellForm[0].Id);
        System.assertEquals(true, result2);

        result = ApprovalCommentsController.sObjectCheck(contact[0].Id);
        System.assertEquals(false, result);
    }
    @IsTest public static void getApprovalCommentsTest() {
        List<Contact> contact = [SELECT Id FROM Contact WHERE LastName = 'test lastname'];
        List<Application_form__c> appForm = [SELECT Id, OwnerId, Form_Status__c, CreatedById FROM Application_form__c WHERE Contact__c = :contact[0].Id];
        List<User> user = [SELECT Id FROM User WHERE Username = 'tester@noemail.com'];
        //Submit record for approval
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(appForm[0].Id);
        req1.setSubmitterId(user[0].Id);
        Approval.ProcessResult result = Approval.process(req1);
        System.assert(result.isSuccess());
        System.assertEquals(
                'Pending', result.getInstanceStatus(),
                'Instance Status'+result.getInstanceStatus());
        //Reject record with Further Information Required
        List<Id> newWorkItemIds = result.getNewWorkitemIds();
        Approval.ProcessWorkitemRequest req2 =
                new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Reject');
        req2.setWorkitemId(newWorkItemIds.get(0));
        Approval.ProcessResult result2 =  Approval.process(req2);
        System.assert(result2.isSuccess(), 'Result Status:'+result2.isSuccess());
        System.assertEquals(
                'Rejected', result2.getInstanceStatus(),
                'Instance Status'+result2.getInstanceStatus());
        String result3 = ApprovalCommentsController.getApprovalComments(appForm[0].Id);
        System.assertNotEquals('none', result3);
    }
}