force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment &amp; Invoice</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Applications Forms</relationshipLabel>
    <relationshipName>Applications_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/Email_activity__c.object-meta.xml
<CustomObject>
    <label>Email Activity</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Email Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Email activities</relationshipLabel>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Email Activities</relationshipLabel>
    <relationshipName>Email_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Purchase_Type__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Type__c</fullName>
    <description>Actual for memberships invoices</description>
    <label>Purchase Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Session_Participation__c.field-meta.xml
<CustomField>
    <fullName>Session_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Participation</label>
    <referenceTo>Session_Participation__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Participation__c/Session_Participation__c.object-meta.xml
<CustomObject>
    <label>Session Participation</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Session Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Participation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Session_Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The related events do not match.</errorMessage>
        <filterItems>
            <field>Participant__c.Event_custom__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Session Bookings</relationshipLabel>
    <relationshipName>Session_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicePDFGenerator.cls
public class InvoicePDFGenerator {
    @Future(Callout = true)
    public static void generateInvoicePDFs(List<Id> orderIds) {
        List<ContentVersion> attachments = new List<ContentVersion>();
        List<ContentVersion> newAttachments = new List<ContentVersion>();
        Map<String, ContentVersion> attachmentMap = new Map<String, ContentVersion>();
        Map<String, String> fileOrderMap = new Map<String, String>();
        Set<String> attachmentNames = new Set<String>();
        List<Order__c> orders = new List<Order__c>();
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        List<BCC_email__mdt> bccEmail = [SELECT Id, Email__c FROM BCC_email__mdt LIMIT 1];
        // Collect Orders
        orders = [
                SELECT Id, Name, Contact__r.Email, Contact__r.MailingAddress, Invoice_Number__c, Purchase_Type__c,
                (SELECT Id, Product__c, Membership__c FROM Order_Items__r), (SELECT Id, Name FROM Applications_Forms__r ORDER BY CreatedDate DESC)
                FROM Order__c
                WHERE Id IN :orderIds AND Contact__c != null AND Contact__r.Email != null
                ORDER BY CreatedDate ASC
        ];
        // Generate new Invoice Numbers
        Boolean generated =  InvoicePDFGenerator.generateInvoiceNumber(orders);
        if (generated) {
            // Collect all Attachment Names
            for (Order__c o : orders) {
                attachmentNames.add('Invoice_' + o.Name + '.pdf');
            }
            // Collect all related Attachments
            attachments = [SELECT Title, VersionData FROM ContentVersion WHERE Title IN :attachmentNames];

            for (ContentVersion at : attachments) {
                attachmentMap.put(at.Title, at);
            }
            // Send an email with new or existing PDF
            List<EmailTemplate> ets = [
                    SELECT Id, Name, DeveloperName
                    FROM EmailTemplate
                    WHERE DeveloperName = 'Confirmation_of_Journal_order_invoice'
                    OR DeveloperName = 'New_Invoice_Email'
            ];
            EmailTemplate et = new EmailTemplate();
            OrgWideEmailAddress address = [SELECT Id FROM OrgWideEmailAddress WHERE Address LIKE 'membership@ean.org' LIMIT 1];
            for (Order__c o : orders) {
                ContentVersion att;

                //check if order has membership
                Boolean hasMembership = false;
                for(Order_Item__c oi : o.Order_Items__r){
                    if(oi.Membership__c != null){
                        hasMembership = true;
                    }
                }
                //find required email template
                String emailTemplateDevName = hasMembership?'New_Invoice_Email':'Confirmation_of_Journal_order_invoice';
                for(EmailTemplate emTemp : ets){
                    if(emTemp.DeveloperName == emailTemplateDevName){
                        et = emTemp;
                    }
                }
                //choose whoId and whatId for email template
                Id whatId = hasMembership?o.Applications_Forms__r[0].Id:o.Id;


                // if PDF doesn't exist
                if (!attachmentMap.keySet().contains('Invoice_' + o.Name + '.pdf')) {
                    PageReference defaultPage = new PageReference('/apex/InvoicePage');
                    defaultPage.getParameters().put('co', o.Id);
                    defaultPage.getParameters().put('in', o.Invoice_Number__c);
                    Blob pageData;

                    if (Test.isRunningTest()) {
                        pageData = Blob.valueOf('Unit.Test');
                    } else {
                        pageData = defaultPage.getContent();
                    }
                    att = new ContentVersion(
                            VersionData = pageData,
                            Title = 'Invoice_' + o.Name + '.pdf',
                            PathOnClient = 'Invoice_' + o.Name + '.pdf',
                            IsMajorVersion = true,
                            ContentLocation = 'S',
                            NetworkId = ConnectApi.Communities.getCommunities().communities[0].id
                    );
                    newAttachments.add(att);
                    fileOrderMap.put(att.Title, o.Id);
                    // else if PDF exists
                } else {
                    att = attachmentMap.get('Invoice_' + o.Name + '.pdf');
                }
                
                Messaging.SingleEmailMessage message = Messaging.renderStoredEmailTemplate(et.Id, o.Contact__c, whatId);
                Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
                attach.setBody(att.VersionData);
                attach.setFileName(att.Title);
                attach.setContentType('application/pdf');
                String emailTextBody = message.getPlainTextBody();
                message.setTargetObjectId(o.Contact__c);
                message.setPlainTextBody(emailTextBody);
                message.saveAsActivity = false;
                message.setOrgWideEmailAddressId(address.Id);

                if(!bccEmail.isEmpty()){
                    message.setBccAddresses(new List<String>{bccEmail[0].Email__c});
                }

                message.setFileAttachments(new Messaging.EmailFileAttachment[]{
                        attach
                });
                emails.add(message);
            }

            try {
                // Insert new PDF Invoices as Attachments
                if (!newAttachments.isEmpty()) {
                    System.debug(newAttachments);
                    insert newAttachments;

                    List<ContentVersion> cds = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id IN : newAttachments];
                    List<ContentDocumentLink> cdLinks = new List<ContentDocumentLink>();
                    for (ContentVersion cd : cds) {
                        Id orderId = fileOrderMap.get(cd.Title);
                        ContentDocumentLink link = new ContentDocumentLink(LinkedEntityId = orderId,
                        ShareType = 'V', ContentDocumentId = cd.ContentDocumentId);
                        cdLinks.add(link);
                    }

                    if (!cdLinks.isEmpty()) {
                        insert cdLinks;
                    }
                }
                // Send Emails with attached PDF Invoices
                if (!emails.isEmpty()) {
                    Messaging.sendEmail(emails);
                }
            } catch (Exception e) {
                Messaging.SingleEmailMessage errorEmail = new Messaging.SingleEmailMessage();
                errorEmail.setSubject('New Invoice sending error');
                String[] emailIds = new String[]{
                        'ilya.litovchik@succraft.com'
                };
                errorEmail.setToAddresses(emailIds);
                errorEmail.setPlainTextBody('Error Description: \n Message:' + e.getMessage() + '\n Line Number: ' + e.getLineNumber() + '\n Stack Trace: ' + e.getStackTraceString());
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                        errorEmail
                });
            }
        }
    }

    public static Boolean generateInvoiceNumber(List<Order__c> orders) {
        Boolean isOk = true;
        List<Order__c> newOrdersEIMF = new List<Order__c>();
        List<Order__c> newOrdersREIMF = new List<Order__c>();
        String orderTemplateEIMF = 'EIMF ' + String.valueOf(Date.today().year()) + '/%';
        String orderTemplateREIMF = 'REIMF ' + String.valueOf(Date.today().year()) + '/%';
        Integer lastEIMFNumber;
        Integer lastREIMFNumber;

        // Collect the last Orders to find the last Invoice Number for EIMF
        List<Order__c> ordersEIMF = [
                SELECT Invoice_Number__c
                FROM Order__c
                WHERE Invoice_Number__c != NULL AND Invoice_Number__c LIKE :orderTemplateEIMF
                ORDER BY Invoice_Number__c DESC
                LIMIT 10
        ];

        // Collect the last Orders to find the last Invoice Number for REIMF
        List<Order__c> ordersREIMF = [
                SELECT Invoice_Number__c
                FROM Order__c
                WHERE Invoice_Number__c != null AND Invoice_Number__c LIKE :orderTemplateREIMF
                ORDER BY Invoice_Number__c DESC
                LIMIT 10
        ];

        for (Order__c o : orders) {
            if (o.Invoice_Number__c == null || !o.Invoice_Number__c.contains('EIMF')) {
//                if (o.Purchase_Type__c == 'Update') {
//                    newOrdersREIMF.add(o);
//                } else {
                    newOrdersEIMF.add(o);
//                }
            }
        }

        // Generate Invoice Numbers for EIMF
        if (!newOrdersEIMF.isEmpty()) {
            lastEIMFNumber = 625;

            // Find the last correct Invoice Number for EIMF
            for (Order__c o : ordersEIMF) {
                String invoiceNumb = o.Invoice_Number__c.replace('EIMF ' + String.valueOf(Date.today().year()) + '/','');
                if (invoiceNumb.isNumeric()) {
                    lastEIMFNumber = Integer.valueOf(invoiceNumb);
                    break;
                }
            }

            // Set new Invoice Numbers to EIMF Orders
            for (Order__c o : newOrdersEIMF) {
                lastEIMFNumber += 1;
                String newInvoiceNumber = String.valueOf(lastEIMFNumber);
                if (lastEIMFNumber < 1000) {
                    newInvoiceNumber  = ('0000' + lastEIMFNumber).right(4);
                }
                o.Invoice_Number__c = 'EIMF ' + String.valueOf(Date.today().year()) + '/' + newInvoiceNumber;
            }
        }

        // Generate Invoice Numbers for REIMF
        if (!newOrdersREIMF.isEmpty()) {
            lastREIMFNumber = 0;

            // Find the last correct Invoice Number for REIMF
            for (Order__c o : ordersREIMF) {
                String invoiceNumb = o.Invoice_Number__c.replace('REIMF ' + String.valueOf(Date.today().year()) + '/','');
                if (invoiceNumb.isNumeric()) {
                    lastREIMFNumber = Integer.valueOf(invoiceNumb);
                    break;
                }
            }

            // Set new Invoice Numbers to REIMF Orders
            for (Order__c o : newOrdersREIMF) {
                lastREIMFNumber += 1;
                String newInvoiceNumber = String.valueOf(lastREIMFNumber);
                if (lastREIMFNumber < 1000) {
                    newInvoiceNumber  = ('0000' + lastREIMFNumber).right(4);
                }
                o.Invoice_Number__c = 'REIMF ' + String.valueOf(Date.today().year()) + '/' + newInvoiceNumber;
            }

        }

        try {
            // Update Orders with new Invoice Numbers
            if (!orders.isEmpty()) {
                update orders;
            }
        } catch (Exception e) {
            isOk = false;
            Messaging.SingleEmailMessage errorEmail = new Messaging.SingleEmailMessage();
            errorEmail.setSubject('New Invoice Number creation error');
            String[] emailIds = new String[]{
                    'ezhi.sarosek@succraft.com'
            };
            errorEmail.setToAddresses(emailIds);
            errorEmail.setPlainTextBody('Error Description: \n Message:' + e.getMessage() + '\n Line Number: ' + e.getLineNumber() + '\n Stack Trace: ' + e.getStackTraceString());
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                    errorEmail
            });
        }

        return isOk;
    }

    public static void updateParticipantsStatus(List<Id> orderIds){
        List<Order__c> ordersWithParticipationItems = [
                SELECT Id, Status__c,
                (
                        SELECT Id, Session_Participation__r.Status__c, Event_Participation__r.Status__c
                        FROM Order_Items__r
                        WHERE Session_Participation__c != NULL
                        OR Event_Participation__c != NULL
                )
                FROM Order__c
                WHERE Id IN :orderIds
        ];

        List<Participant__c> eventParticipants = new List<Participant__c>();
        List<Session_Participation__c> sessionParticipants = new List<Session_Participation__c>();

        for(Order__c o : ordersWithParticipationItems){
            for(Order_Item__c oi : o.Order_Items__r){
                if(oi.Event_Participation__c != null && oi.Event_Participation__r.Status__c == 'Pending'){
                   eventParticipants.add(new Participant__c(Id = oi.Event_Participation__c, Status__c = 'Registered'));
                }
                if(oi.Session_Participation__c != null && oi.Session_Participation__r.Status__c == 'Pending'){
                    sessionParticipants.add(new Session_Participation__c(Id = oi.Session_Participation__c, Status__c = 'Registered'));
                }
            }
        }

        update eventParticipants;
        update sessionParticipants;
    }

    @Future(Callout = true)
     public static void insertEmailActivity(List<Id> orderIds) {
         List<Order__c> orders = [
             SELECT Id, Contact__r.Email, Event_custom__c, Type__c FROM Order__c WHERE Id IN :orderIds
         ];
         List<Email_Activity__c> emailActivities = new List<Email_Activity__c>();
         for (Order__c order : orders) {
             Email_Activity__c emailActivity = new Email_Activity__c(
                 Contact__c = order.Contact__c,
                 Event_Custom__c = order.Event_custom__c,
                 Order__c = order.Id,
                 Send_To_Email__c = order.Contact__r.Email,
                 Type__c = order.Type__c
             );
             emailActivities.add(emailActivity);
         }
         if (emailActivities.size() > 0) {
             insert emailActivities;
         }
     }
}