force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment &amp; Invoice</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Applications Forms</relationshipLabel>
    <relationshipName>Applications_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/GroupChatterGroupAssotiation__c.object-meta.xml
<CustomObject>
    <label>Working Group Membership</label>
    <nameField>
        <displayFormat>IGM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Working Group Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Working Groups</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Working Group Memberships</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Alzheimer Europe representative</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate Editor</fullName>
            </value>
            <value>
                <fullName>Book Review Editor</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>CME Editor</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Chair Communication Committee</fullName>
            </value>
            <value>
                <fullName>Chair Education Committee</fullName>
            </value>
            <value>
                <fullName>Chair Programme Committee</fullName>
            </value>
            <value>
                <fullName>Chair Scientific Committee</fullName>
            </value>
            <value>
                <fullName>Chair Teaching Course sub-Committee</fullName>
            </value>
            <value>
                <fullName>Co-Chair</fullName>
            </value>
            <value>
                <fullName>EANO representative</fullName>
            </value>
            <value>
                <fullName>EAPC representative</fullName>
            </value>
            <value>
                <fullName>EC-IFCN representative</fullName>
            </value>
            <value>
                <fullName>ECTRIMS representative</fullName>
            </value>
            <value>
                <fullName>EFAS representative</fullName>
            </value>
            <value>
                <fullName>EFIC representative</fullName>
            </value>
            <value>
                <fullName>EFNR representative</fullName>
            </value>
            <value>
                <fullName>EHF representative</fullName>
            </value>
            <value>
                <fullName>EQTF Representative</fullName>
            </value>
            <value>
                <fullName>ESO representative</fullName>
            </value>
            <value>
                <fullName>Editor-in-Chief</fullName>
            </value>
            <value>
                <fullName>Ethics Advisor</fullName>
            </value>
            <value>
                <fullName>EuGMS representative</fullName>
            </value>
            <value>
                <fullName>Ex-officio member</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Secretary general</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RejectionLetterEmailController.cls
public with sharing class RejectionLetterEmailController {
    public Application_form__c appForm {get{
        return appForm.Id==null? new Application_form__c():
                [
                        SELECT Id, Name, Contact__r.Salutation, Contact__r.FirstName, Contact__r.LastName, Contact__r.Title,
                                Membership__r.Name, Membership__r.API__c, Membership__r.Reviewer__r.Salutation,
                                Membership__r.Reviewer__r.Name, Membership__r.Reviewer__r.Reviewer_Title__c, Order__r.Name
                        FROM Application_form__c
                        WHERE Id = :appForm.Id
                ];
    }set;}
    public Contact defaultSecretaryGeneral {get{
        List<GroupChatterGroupAssotiation__c>  groupMemberships = [
                SELECT Id, Contact__c
                FROM GroupChatterGroupAssotiation__c
                WHERE Role__c = 'Secretary general' AND
                Group__r.RecordType.Name = 'Level 1 Board (EAN Board)'
        ];
        Contact contact = new Contact();
        if(!groupMemberships.isEmpty()){
            contact = [SELECT Id, Salutation, Name, Title, Reviewer_Title__c FROM Contact WHERE Id = :groupMemberships[0].Contact__c];
        }
        return contact;
    } set;}
}