force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Form_Status__c</fullName>
    <label>Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <description>If student, attach student ID card</description>
    <label>Profession</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neurologist</fullName>
            </value>
            <value>
                <fullName>Residents/Physician in training</fullName>
                <label>Resident/physician in training</label>
            </value>
            <value>
                <fullName>Research Fellows in Neurology</fullName>
                <label>Research fellow in neurology</label>
            </value>
            <value>
                <fullName>PhD student in neurology</fullName>
            </value>
            <value>
                <fullName>Undergraduate Medical Student</fullName>
                <label>Undergraduate medical student</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Neurologist working in Pharma</fullName>
                <label>Neurologist working in pharma</label>
            </value>
            <value>
                <fullName>PhD students in neurology</fullName>
                <isActive>false</isActive>
                <label>PhD students in neurology</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <label>Country of Residence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/ZIP_Postal_code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Postal_code__c</fullName>
    <label>ZIP/Postal code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country_Price__c/Country_Price__c.object-meta.xml
<CustomObject>
    <label>Country Price</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Country Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Price__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Country Prices</relationshipLabel>
    <relationshipName>Country_Prices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/price_for_deadline_1__c.field-meta.xml
<CustomField>
    <fullName>price_for_deadline_1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2020-01-01_2020-03-27</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/price_for_deadline_2__c.field-meta.xml
<CustomField>
    <fullName>price_for_deadline_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2020-03-28_2020-09-30</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/price_for_deadline_3__c.field-meta.xml
<CustomField>
    <fullName>price_for_deadline_3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2020-10-01_2020-12-31</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Country_Price__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/isForUpdateMembershipApplication__c.field-meta.xml
<CustomField>
    <fullName>isForUpdateMembershipApplication__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if current membership is available for &quot;Update Membership Application&quot;.</description>
    <label>For Update Membership Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/www__c.field-meta.xml
<CustomField>
    <fullName>www__c</fullName>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TestMembershipApplicationController.cls
@isTest
public with sharing class TestMembershipApplicationController {
    @testSetup static void setup() {
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Account account = new Account(Name = 'Individuals (Contacts)');
        insert  account;
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Individual', AccountId = account.Id, Email = 'individual@individ.com');
        insert contact;
        Membership__c membership = new Membership__c(Name = 'Full Membership', API__c = 'full_membership', isForUpdateMembershipApplication__c=true, www__c = 'https://www.ean.org/Full-Member.3801.0.html');
        insert membership;
        Country_Price__c countryPrice = new Country_Price__c(Membership__c = membership.Id, Region__c = '', Price_for_Deadline_1__c = 150, Price_for_Deadline_2__c = 75, Price_for_Deadline_3__c = 150);
        insert countryPrice;
        Application_form__c appForm = new Application_form__c(
                First_name__c = 'Test',
                Last_name__c = 'TestLast',
                Date_of_birth__c = Date.today(),
                Gender__c = 'Male',
                Email__c = 'test@test.com',
                Nationality__c = 'United States',
                Residency__c = 'United States',
                ZIP_Postal_code__c = '1111',
                City__c = 'City',
                Membership__c = membership.Id,
                Contact__c = contact.Id,
                Profession__c = 'Neurologist',
                Street__c = 'test street',
                Form_Status__c = 'Further Information Required'
        );
        insert appForm;

    }
    @isTest static void getContactForFormByIdTest() {
        Contact contact = [SELECT Id FROM Contact WHERE LastName = 'Individual' LIMIT 1];
        Contact contactFFBI = membershipApplicationController.getContactForFormById(contact.Id);
        Map<String, Object> mapContactFFBI = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(contactFFBI));
        List<String> contactFieldForForm = new List<String>();
        for (Schema.FieldSetMember f : SObjectType.Contact.FieldSets.Form_fields.getFields()) {
            contactFieldForForm.add(f.getFieldPath());
        }
        Integer counter = 0;
        for (String m : mapContactFFBI.keySet()) {
            for (String fs : contactFieldForForm) {
                if (m == fs) {
                    counter++;
                }
            }
        }
        System.assertNotEquals(counter, 0);
    }
    @isTest static void getCountriesTest() {
        List<Country__mdt> countries = membershipApplicationController.getCountries();
        System.assertNotEquals(countries, null);
        for (Country__mdt c : countries) {
            System.assertNotEquals(c.get('Label'), null);
        }
    }
    @isTest static void getFieldSetsTest() {
        List<List<String>> fs = membershipApplicationController.getFieldSets();
        List<String> fieldSet = new List<String>();
        for (Integer i = 0; i < fs.size(); i++) {
            fieldSet.addAll(fs[i]);
        }
        Schema.DescribeSObjectResult r = Application_form__c.sObjectType.getDescribe();
        List<String> apiNames = new List<String>();
        for (String apiName : r.fields.getMap().keySet()) {
            apiNames.add(Schema.getGlobalDescribe().get('Application_form__c').getDescribe().fields.getMap().get(apiName).getDescribe().getName());
        }
        for (String field : fieldSet) {
            System.assertEquals(apiNames.contains(field), true);
        }
    }
    @isTest static void upsertFormTest() {
        Contact contact = new Contact(FirstName = 'Test FirstName', LastName = 'Test LastName');
        insert contact;
        Membership__c membership = [SELECT Id FROM Membership__c LIMIT 1];
        Application_form__c appForm = new Application_form__c(
                First_name__c = 'Test',
                Last_name__c = 'TestLast',
                Date_of_birth__c = Date.today(),
                Gender__c = 'Male',
                Email__c = 'test@test.com',
                Nationality__c = 'United States',
                Residency__c = 'United States',
                ZIP_Postal_code__c = '1111',
                City__c = 'City',
                Membership__c = membership.Id,
                Contact__c = contact.Id,
                Profession__c = 'Neurologist',
                Street__c = 'test street'
        );
        appForm = membershipApplicationController.upsertForm(appForm);
        System.assertNotEquals(null, appForm.Id);
        appForm.Gender__c = 'Female';
        System.assertEquals('Female', membershipApplicationController.upsertForm(appForm).Gender__c);
        try{
            appForm.Date_of_birth__c = Date.today().addDays(1);
            appForm = membershipApplicationController.upsertForm(appForm);
        } catch (Exception e){
            System.assert(e.getMessage().contains('Birthday cannot be in future'));
        }
    }
    @isTest static void updateContactTest() {
        Contact contact = [SELECT Id FROM Contact WHERE LastName = 'Individual' LIMIT 1];
        contact.LastName = 'Changed LastName';
        membershipApplicationController.updateContact(contact);
        System.assertEquals([SELECT LastName FROM Contact WHERE Id = :contact.Id].LastName, 'Changed LastName');
        try{
            contact.Birthdate = Date.today().addDays(1);
            membershipApplicationController.updateContact(contact);
        } catch (Exception e){
            System.assert(e.getMessage().contains('Birthday cannot be in future'));
        }
    }
    @isTest static void getDeadlineTest() {
        String deadline = membershipApplicationController.getDeadline();
        System.assertNotEquals(Schema.getGlobalDescribe().get('Country_Price__c').getDescribe().fields.getMap().get(deadline.toLowerCase()).getDescribe().getName(), null);
    }
    @isTest static void getMembershipsTest() {
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Id cclu = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User'].Id;
        Account acc = [SELECT Id FROM Account WHERE Name = 'Individuals (Contacts)'];
        Contact con = new Contact(LastName = 'testCon', AccountId = acc.Id);
        insert con;
        User user = new User(
                Alias = 'test123', Email = 'test123@noemail.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = cclu, Country = 'United States', IsActive = true,
                ContactId = con.Id, TimeZoneSidKey = 'America/Los_Angeles', Username = 'tester@noemail.com');
        insert user;
        System.runAs(user) {
            membershipApplicationWrapper w = membershipApplicationController.getMemberships();
            System.assertEquals(1, w.memberships.size());
            System.assertEquals(1, w.countryPrices.size());
            System.assertEquals(con.Id, w.contact.Id);
            System.assertNotEquals(null, w.fieldMap);
        }
    }
    @IsTest public static void deleteContentDocumentByIdTest(){
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Id cclu = [SELECT Id FROM Profile WHERE Name = 'Member Community User Profile'].Id;
        Account acc = [SELECT Id FROM Account WHERE Name = 'Individuals (Contacts)'];
        Contact con = new Contact(LastName = 'testCon', AccountId = acc.Id);
        insert con;
        User user = new User(
                Alias = 'test123', Email = 'test123@noemail.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = cclu, Country = 'Belarus', IsActive = true,
                ContactId = con.Id, TimeZoneSidKey = 'America/Los_Angeles', Username = 'tester@noemail.com');
        insert user;
        System.runAs(user) {
            ContentVersion cv = new ContentVersion(
                    Title = 'Test',
                    PathOnClient = 'Test.jpg',
                    VersionData = Blob.valueof('Test Content Data'),
                    IsMajorVersion = true,
                    NetworkId =[SELECT Id, Name FROM Network LIMIT 1].Id
            );
            insert cv;
            ContentVersion contentVersionSelect = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
            membershipApplicationController.deleteContentDocumentById(contentVersionSelect.ContentDocumentId);
            List<ContentDocument> cd = [SELECT Id FROM ContentDocument WHERE Id = :contentVersionSelect.ContentDocumentId];
            System.assertEquals(0, cd.size());
        }
    }
    @IsTest public static void getExistedFormTest(){
        Application_form__c appForm = [SELECT Id FROM Application_form__c WHERE First_name__c = 'Test' AND Last_name__c = 'TestLast'];
        Application_form__c fullApplicationForm = membershipApplicationController.getExistedForm(appForm.Id);
        System.assertEquals('United States', fullApplicationForm.Nationality__c);
        System.assertEquals('United States', fullApplicationForm.Residency__c);
        fullApplicationForm.Form_Status__c = 'Draft';
        update fullApplicationForm;
        try{
            fullApplicationForm = membershipApplicationController.getExistedForm(appForm.Id);
        } catch (Exception e){
            System.assertEquals('This application cannot be re-submitted', e.getMessage());
        }
        try {
            fullApplicationForm = membershipApplicationController.getExistedForm('no-id');
        } catch (Exception e){
            System.assertEquals('This application wasn\'t found', e.getMessage());
        }
    }
    @IsTest public static void getContentDocumentsTest(){
        Application_form__c appForm = [SELECT Id FROM Application_form__c WHERE First_name__c = 'Test' AND Last_name__c = 'TestLast'];
        System.assert(membershipApplicationController.getContentDocuments(appForm.Id).isEmpty());
    }
    @IsTest public static void submitForApprovalTest(){
        Application_form__c appForm = [SELECT Id FROM Application_form__c WHERE First_name__c = 'Test' AND Last_name__c = 'TestLast'];
        membershipApplicationController.submitForApproval(appForm.Id);
        System.assert(Approval.isLocked(appForm.Id));
    }
    @IsTest public static void attachFileToFormTest(){
        Application_form__c appForm = [SELECT Id FROM Application_form__c WHERE First_name__c = 'Test' AND Last_name__c = 'TestLast'];
        List<ContentVersion> contentVersionInsert = new List<ContentVersion>();
        for(Integer i = 0; i<2; i++){
            contentVersionInsert.add(new ContentVersion(
                    Title = 'Test'+i,
                    PathOnClient = 'Test'+i+'.jpg',
                    VersionData = Blob.valueOf('Test Content Data'+i),
                    IsMajorVersion = true
            ));
        }
        insert contentVersionInsert;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        System.assert(documents.size()>0);
        List<ContentDocumentLink> cDocumentLink = new List<ContentDocumentLink>();
        cDocumentLink.add(new ContentDocumentLink(ContentDocumentId = documents[0].Id, LinkedEntityId = appForm.Id, ShareType = 'I', Visibility = 'AllUsers'));
        membershipApplicationController.attachFileToForm(cDocumentLink);
        List<ContentDocumentLink> insertedLinks = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :appForm.Id];
        System.assertEquals(1, insertedLinks.size());
        cDocumentLink.add(new ContentDocumentLink(ContentDocumentId = documents[1].Id, LinkedEntityId = appForm.Id, ShareType = 'I', Visibility = 'AllUsers'));
        membershipApplicationController.attachFileToForm(cDocumentLink);
        insertedLinks = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :appForm.Id];
        System.assertEquals(2, insertedLinks.size());
    }
    @IsTest public static void getCommunityHomeUrlTest(){
        System.assertEquals('community.com', membershipApplicationController.getCommunityHomeUrl());
    }
}