force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment &amp; Invoice</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Applications Forms</relationshipLabel>
    <relationshipName>Applications_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/Country_code__c.field-meta.xml
<CustomField>
    <fullName>Country_code__c</fullName>
    <label>Country code alpha2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/www__c.field-meta.xml
<CustomField>
    <fullName>www__c</fullName>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Billing_address__c.field-meta.xml
<CustomField>
    <fullName>Billing_address__c</fullName>
    <label>Billing address</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Purchase_Type__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Type__c</fullName>
    <description>Actual for memberships invoices</description>
    <label>Purchase Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <label>Total amount</label>
    <summarizedField>Order_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Total_amount__c</fullName>
        <formula>(Quantity__c *  Amount__c) + Discount_Amount__c</formula>
        <label>Total amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderUtils.cls
public without sharing class OrderUtils {
    @AuraEnabled public static String generateOrder(String ContactId, List<Object> orderItemsObject, String purchaseType) {
        System.debug('orderItemsObject:: '+orderItemsObject);
        List<Order_Item__c> orderItems = new List<Order_Item__c>();
        for (Object item : orderItemsObject) {
            Map<String, Object> itemMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(item));
            Order_Item__c oi = new Order_Item__c();
            for (String key : itemMap.keySet()) {
                oi.put(key, itemMap.get(key));
            }
            orderItems.add(oi);
        }
        String orderId = createOrder(ContactId, purchaseType);
        createOrderItems(orderId, orderItems);
        System.debug(orderItems);
        return orderId;
    }
    public static String createOrder(String ContactId, String purchaseType) {
        Order__c o = new Order__c(Contact__c = ContactId, Purchase_Type__c=purchaseType);
        insert o;
        return o.Id;
    }
    public static void createOrderItems(String orderId, List<Order_Item__c> orderItems) {
        for (Order_Item__c oi : orderItems) {
            oi.Order_Custom__c = orderId;
        }
        insert orderItems;
    }
    public static void createTransaction(Transaction__c newTransaction) {
        insert newTransaction;
        List<Transaction__c> trans = [SELECT Id, Status__c, Amount__c FROM Transaction__c WHERE Order_Custom__c = :newTransaction.Order_Custom__c AND Status__c = 'Success'];
        Decimal sucTransTotal = 0;
        for(Transaction__c t : trans){
            sucTransTotal += t.Amount__c;
        }
        List<Order__c> order = [SELECT Total_amount__c, Status__c, Payment_Date__c FROM Order__c WHERE Id = :newTransaction.Order_Custom__c];
        if(order[0].Total_amount__c == sucTransTotal && order[0].Status__c != 'Paid'){
            System.debug('here');
            order[0].Status__c = 'Paid';
            order[0].Payment_Date__c = Datetime.now();
            update order;
        }
    }
    @AuraEnabled public static Map<String, Object> determineSuccessScreen(String orderId){
        Map<String, Object> resultMap = new Map<String, Object>();
        String result = 'ORDER';
        List<Order__c> order = [SELECT Id, Type__c, Total_amount__c, Invoice_Number__c, Event_custom__r.www__c,
        (SELECT Id, Membership__c, Membership__r.Name FROM Applications_Forms__r LIMIT 1) FROM Order__c WHERE Id = :orderId];
        resultMap.put('order', order);

        if(!order.isEmpty()){

            if (order[0].Applications_Forms__r.isEmpty()){

                if(order[0].Type__c == 'Event registration'){
                    result = 'EVENT_REGISTRATION';
                }

            } else {
                //  part of 'Membership Renewal'
                if (order[0].Applications_Forms__r[0].Membership__c != null && order[0].Type__c == 'Renewal' &&
                        order[0].Applications_Forms__r[0].Membership__r.Name != 'Student Membership') {
                    resultMap.put('type', result);
                    return resultMap;
                }

                result+='_WITH_APP_FORM';
            }

        } else {
            result = 'ERROR';
        }

        resultMap.put('type', result);

        return resultMap;
    }
    @AuraEnabled public static void updateOrderItems(String orderId, List<Order_Item__c> orderItems){
        List<Order_Item__c> existedOrderItems = [SELECT Id FROM Order_Item__c WHERE Order_Custom__c = :orderId];
        if(!existedOrderItems.isEmpty()){
            delete existedOrderItems;
        }
        createOrderItems(orderId, orderItems);
    }
    public static void writeOrderBillingAddress(String orderId, String addressesObject){
        Map<String, Object> addressesMap = (Map<String, Object>) JSON.deserializeUntyped(addressesObject);
        List<Country__mdt> countries = [SELECT Id, Country__c, Country_code__c FROM Country__mdt ORDER BY Country__c ASC];

        String billingAddress = '';
        billingAddress += (String) addressesMap.get('billing-street') + '\n';

        String billingState = (String) addressesMap.get('billing-state');
        billingState = billingState == null ? '' : billingState;

        billingAddress += (String) addressesMap.get('billing-code') + ' ' + (String) addressesMap.get('billing-city') + ' ' + billingState + '\n';

        String billingCountry = (String) addressesMap.get('billing-country');

        for(Country__mdt country : countries){
            if(country.Country_code__c == billingCountry){
                billingCountry = country.Country__c;
                break;
            }
        }

        billingAddress += billingCountry;

        update new Order__c(Id = orderId, Billing_address__c = billingAddress);
    }
}