force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DocumentsMissingEmailController.cls
public with sharing class DocumentsMissingEmailController {
    public Application_form__c appForm {get{
        return appForm.Id==null? new Application_form__c():[SELECT Id, Name, Contact__r.Salutation, Contact__r.FirstName, Contact__r.LastName, Contact__r.Title, Membership__r.Name FROM Application_form__c WHERE Id = :appForm.Id];
    } set;}
    public String approvalComment {get{
        if(appForm.Id!=null){
            List<ProcessInstance> recordInstances = [SELECT Id, TargetObjectId FROM ProcessInstance WHERE TargetObjectId =:appForm.Id ORDER BY CreatedDate DESC];
            List<ProcessInstanceStep> instancesSteps = [SELECT Comments, ProcessInstanceId, CreatedDate, OriginalActorId FROM ProcessInstanceStep WHERE ProcessInstanceId =:recordInstances[0].Id ORDER BY CreatedDate DESC];
            return instancesSteps[0].Comments;
        } else {
            return null;
        }
    }set;}
    public String communityUrl{get{
        if(Test.isRunningTest()) return 'community.com';
        List<Network> myNetwork = [SELECT Id FROM Network WHERE Name = 'ean'];
        if(!myNetwork.isEmpty() && appForm.Id!=null){
            ConnectApi.Community myCommunity = ConnectApi.Communities.getCommunity(myNetwork[0].Id);
            return myCommunity.siteUrl + '/s/detail/'+appForm.Id;
        } else {
            return 'ean.org';
        }
    } set;}
}