force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Form_Status__c</fullName>
    <label>Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Application_form__c.field-meta.xml
<CustomField>
    <fullName>Application_form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application form</label>
    <referenceTo>Application_form__c</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date when current membership expires</description>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Indicates if this membership is active. This field use formula. The membership won&apos;t be active in this year if it expires in next one.</description>
    <formula>IF( Endless_Activation__c  = true, true, Expiration_date__c &gt;= DATETIMEVALUE( TODAY() ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Renewal_Application_Form__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Application_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Application Form</label>
    <referenceTo>Application_form__c</referenceTo>
    <relationshipLabel>Membership Status (Renewal Application Form)</relationshipLabel>
    <relationshipName>Prev_Membership_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MembershipContainerController.cls
public with sharing class MembershipContainerController {
    @AuraEnabled public static String getCurrentContactMemberships(){
        List<User> currentUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        List<MembershipContactAssotiation__c> contactsMemberships = [
            SELECT Id, Expiration_date__c, Membership__c, Membership__r.Name, Membership__r.API__c, Renewal_Application_Form__c, Renewal_Application_Form__r.Form_Status__c
            FROM MembershipContactAssotiation__c
            WHERE Contact__c=:currentUser[0].ContactId
            AND IsActive__c=true
        ];
        List<Application_form__c> contactAppForms = [SELECT Id, Form_Status__c FROM Application_form__c WHERE Contact__c=:currentUser[0].ContactId];

        // return JSON.serialize(new Map<String, List<Object>>{'app-forms'=>contactAppForms, 'memberships'=>contactsMemberships});

        //  priority 2: previous year (Membership Renewal)
        Map<String, Object> renewalSettings = MembershipRenewalController.collectRenewalInfo(currentUser[0].ContactId);

        return JSON.serialize(new Map<String, Object>{'app-forms'=>contactAppForms, 'memberships'=>contactsMemberships, 'renewalSettings' => renewalSettings});
    }
}