force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Form_Status__c</fullName>
    <label>Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Renewal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_End_Date__c</fullName>
    <label>Renewal End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Renewal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Start_Date__c</fullName>
    <label>Renewal Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Application_form__c.field-meta.xml
<CustomField>
    <fullName>Application_form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application form</label>
    <referenceTo>Application_form__c</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_date__c</fullName>
    <label>Assignment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date when current membership expires</description>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>added with Membership Renewal</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AssignMembershipHelper.cls
public with sharing class AssignMembershipHelper {
    public static void assignMembership(List<Application_form__c> updatedForms){

        //  part of 'Membership Renewal'
        List<Membership__c> studentMemberhip = [SELECT Id FROM Membership__c WHERE API__c ='student_membership' LIMIT 1];
        Id studentMemberhipId = !studentMemberhip.isEmpty() ? studentMemberhip[0].Id : null;

        List<MembershipContactAssotiation__c> mca = new List<MembershipContactAssotiation__c>();
        Date expDate;

        for(Application_form__c af:updatedForms){

            Datetime renewalStartDateTime; //  part of 'Membership Renewal'
            Datetime renewalExpDateTime;   //  part of 'Membership Renewal'

            if(!Test.isRunningTest()){
                if(Date.today().month() >= 10){
                    expDate = Date.newInstance(Date.today().year()+1,12,31);
                }else{
                    expDate = Date.newInstance(Date.today().year(),12,31);
                }

                //  part of 'Membership Renewal'
                renewalExpDateTime = af.Renewal_End_Date__c;
                renewalStartDateTime = af.Renewal_Start_Date__c;
                //  part of 'Membership Renewal': if it is not 'Student' then 'Membership_Status' record will be created from a Lightning Flow
                if (af.Membership__c != studentMemberhipId && (renewalExpDateTime != null || renewalStartDateTime != null)) continue;

            } else {
                expDate = Date.newInstance(Date.today().year()+1,12,31);
            }
            if(af.Form_Status__c == 'Approved'){
                mca.add(new MembershipContactAssotiation__c(
                    Contact__c = af.Contact__c, Membership__c = af.Membership__c, Application_form__c = af.Id,
                    Start_Date__c = renewalStartDateTime != null ? renewalStartDateTime : Date.today(),   //  part of 'Membership Renewal'
                    Expiration_date__c = renewalExpDateTime != null ? renewalExpDateTime : expDate,       //  changed for 'Membership Renewal'
                    Assignment_date__c = Date.today())
                );
            }
        }
        if(!mca.isEmpty()){
            insert mca;
        }
    }
    public static void documentsMissingEmailCheck(List<Application_form__c> updatedFormsOld, List<Application_form__c> updatedFormsNew){
        List<String> sendEmailRecords = new List<String>();
        for(Integer i = 0; i<updatedFormsNew.size(); i++){
            if(updatedFormsNew[i].Form_Status__c == 'Further Information Required' && updatedFormsNew[i].Form_Status__c != updatedFormsOld[i].Form_Status__c){
                if(Approval.isLocked(updatedFormsNew[i].Id)){
                    sendEmailRecords.add(updatedFormsNew[i].Id);
                }
            }
        }
        System.debug('sendEmailRecords:: '+!sendEmailRecords.isEmpty());
        if(!sendEmailRecords.isEmpty()){
            sendEmail(sendEmailRecords, 'Documents_are_missing');
        }
    }
    @Future public static void sendEmail(List<String> ids, String templateDeveloperName){
        try{
            List<Application_form__c> appsForms = [SELECT Id, Contact__c FROM Application_form__c WHERE Id IN : ids];
            List<EmailTemplate> ets = [
                    SELECT Id, Name, DeveloperName
                    FROM EmailTemplate
                    WHERE DeveloperName = :templateDeveloperName
            ];
            System.debug('ETS:: '+ets);
            OrgWideEmailAddress address = [SELECT Id FROM OrgWideEmailAddress WHERE Address LIKE 'membership@ean.org' LIMIT 1];
            System.debug('address!!!: '+address);
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            for(Application_form__c af : appsForms){
                Messaging.SingleEmailMessage message = Messaging.renderStoredEmailTemplate(ets[0].Id, af.Contact__c, af.Id);
                String emailTextBody = message.getPlainTextBody();
                message.setTargetObjectId(af.Contact__c);
                message.setPlainTextBody(emailTextBody);
                message.saveAsActivity = false;
                message.setOrgWideEmailAddressId(address.Id);
                emails.add(message);
            }
            if (!emails.isEmpty()) {
                Messaging.sendEmail(emails);
            }
        } catch (Exception e) {
            System.debug('FUTURE_ERROR: '+e.getMessage());
            Messaging.SingleEmailMessage errorEmail = new Messaging.SingleEmailMessage();
            errorEmail.setSubject('Documents Missing Error Email');
            String[] emailIds = new String[]{
                    'ilya.litovchik@succraft.com'
            };
            errorEmail.setToAddresses(emailIds);
            errorEmail.setPlainTextBody('Error Description: \n Message:' + e.getMessage() + '\n Line Number: ' + e.getLineNumber() + '\n Stack Trace: ' + e.getStackTraceString());
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                    errorEmail
            });
        }
    }
    public static void rejectionLetterEmailCheck(List<Application_form__c> updatedFormsOld, List<Application_form__c> updatedFormsNew){
        List<String> sendEmailRecords = new List<String>();
        List<String> sendFEANEmailRecords = new List<String>();
        List<Id> membershipIds = new List<Id>();

        for(Application_form__c appForm : updatedFormsNew){
            membershipIds.add(appForm.Membership__c);
        }

        Map<Id, Membership__c> memberships = new Map<Id, Membership__c>([SELECT Id, API__c FROM Membership__c WHERE Id IN : membershipIds]);

        for(Integer i = 0; i<updatedFormsNew.size(); i++){
            if(updatedFormsNew[i].Form_Status__c == 'Declined' && updatedFormsNew[i].Form_Status__c != updatedFormsOld[i].Form_Status__c){
                if(Approval.isLocked(updatedFormsNew[i].Id)){
                    if(memberships.get(updatedFormsNew[i].Membership__c).API__c == 'fellow_membership'){
                        sendFEANEmailRecords.add(updatedFormsNew[i].Id);
                    } else {
                        sendEmailRecords.add(updatedFormsNew[i].Id);
                    }
                }
            }
        }

        if(!sendEmailRecords.isEmpty()){
            System.debug('sendEmailRecords: '+sendEmailRecords);
            sendEmail(sendEmailRecords, 'Rejection_Letter');
        }

        if(!sendFEANEmailRecords.isEmpty()){
            System.debug('sendFEANEmailRecords: '+sendFEANEmailRecords);
            sendEmail(sendFEANEmailRecords, 'Rejection_Letter_FEAN');
        }
    }
}