force-app/main/default/objects/Application_form__c/Application_form__c.object-meta.xml
<CustomObject>
    <label>Application (Form)</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications form</relationshipLabel>
    <relationshipName>Applications_form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Applications_form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_form__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <label>Country of Residence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Application_form__c.field-meta.xml
<CustomField>
    <fullName>Application_form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application form</label>
    <referenceTo>Application_form__c</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CallForRenewalEmailTemplateController.cls
public without sharing class CallForRenewalEmailTemplateController {

	//	Text field - relevant for FEANs, Full, Corresponding members who do not come from low/lower/middle/upper-middle country
	private final static Set<String> retiredMembers = new Set<String>{
		'Full Membership', 'Full Institutional Members', 'Corresponding Membership', 'Corresponding Institutional Members', 'Fellow of EAN (FEAN) Membership'
	};
	private final static Set<String> notRetiredRegions = new Set<String>{'A', 'B', 'C', 'D'};

	public String membershipStatusId { get; set; }

	public Decimal totalRenewalFee { get; set; }
	public String reductionString { get; set; }
	
	public CallForRenewalEmailTemplateController() {}

	public String getPrepareData() {
		try {
			MembershipContactAssotiation__c membershipStatusRecord = new MembershipContactAssotiation__c();
			Id.valueOf(membershipStatusId);

			List<MembershipContactAssotiation__c>  membershipStatusList = [
				SELECT Id, Name, Contact__c, Contact__r.FirstName, Contact__r.LastName, toLabel(Contact__r.Salutation), Contact__r.Email,
					Membership__c, Membership__r.Name, Application_form__c, Application_form__r.Residency__c
				FROM MembershipContactAssotiation__c
				WHERE Id =:membershipStatusId
				LIMIT 1
			];
			membershipStatusRecord = membershipStatusList.isEmpty() ? new MembershipContactAssotiation__c() : membershipStatusList[0];

			String countryName = membershipStatusRecord.Application_form__c != null && !String.isBlank(membershipStatusRecord.Application_form__r.Residency__c)
				? membershipStatusRecord.Application_form__r.Residency__c : '';

			//	Used to calculate total fee
			//	Based on membership category and country of residence (low/lower/middle/upper-middle country) pay 50% less, RRFS instead of €45 only €25 -  correct fees to be included in Salesforce
			List<Country__mdt> countryList = !String.isBlank(countryName) ? [SELECT Id, Region__c FROM Country__mdt WHERE Country__c =:countryName LIMIT 1] : new List<Country__mdt>();
			String membershipStatusRegion = !countryList.isEmpty() && !String.isBlank(countryList[0].Region__c) ? countryList[0].Region__c : null;

			//	Additional rule: //	Text field - relevant for FEANs, Full, Corresponding members who do not come from low/lower/middle/upper-middle country
			reductionString = retiredMembers.contains(membershipStatusRecord.Name) && !notRetiredRegions.contains(membershipStatusRegion) ? '(retired members get a 50% reduction)' : '';

			//	USED FOR TESTING
			// reductionString = '(retired members get a 50% reduction)';

			totalRenewalFee = MembershipRenewalController.calculateTotalRenewalFee(membershipStatusRegion, membershipStatusRecord.Membership__c);

		} catch (Exception e) {
			return 'Email Generation Error';
		}

		return '';
	}

}