force-app/main/default/objects/Contact_Form__mdt/Contact_Form__mdt.object-meta.xml
<CustomObject>
    <label>Contact-Form</label>
    <pluralLabel>Contact-Form</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_Price__c/Country_Price__c.object-meta.xml
<CustomObject>
    <label>Country Price</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Country Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Price__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Country Prices</relationshipLabel>
    <relationshipName>Country_Prices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/membershipApplicationWrapper.cls
public with sharing class membershipApplicationWrapper {
    @AuraEnabled public List<Membership__c> memberships { get; set; }
    @AuraEnabled public List<Country_Price__c> countryPrices { get; set; }
    @AuraEnabled public Contact contact { get; set; }
    @AuraEnabled public List<Contact_Form__mdt> fieldMap { get; set; }
    @AuraEnabled public List<Product2> availableProduct2s { get; set; }

    public membershipApplicationWrapper(
            List<Membership__c> memberships,
            List<Country_Price__c> countryPrices,
            Contact contact,
            List<Contact_Form__mdt> fieldMap,
            List<Product2> availableProduct2s) {
        this.memberships = memberships;
        this.countryPrices = countryPrices;
        this.contact = contact;
        this.fieldMap = fieldMap;
        this.availableProduct2s = availableProduct2s;
    }
}