force-app/main/default/objects/Visa_Letter__c/Visa_Letter__c.object-meta.xml
<CustomObject>
    <label>Visa Letter</label>
    <nameField>
        <displayFormat>V-{00000}</displayFormat>
        <label>Visa Letter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visa Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visa_Letter__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <label>Authority</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Date_of_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Expiry__c</fullName>
    <label>Date of Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Date_of_Issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue__c</fullName>
    <label>Date of Issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>his</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>her</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>their</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Official_City__c.field-meta.xml
<CustomField>
    <fullName>Official_City__c</fullName>
    <label>Official City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Official_Country__c.field-meta.xml
<CustomField>
    <fullName>Official_Country__c</fullName>
    <label>Official Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Official_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Official_State_Province__c</fullName>
    <label>Official State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Official_Street__c.field-meta.xml
<CustomField>
    <fullName>Official_Street__c</fullName>
    <label>Official Street</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Official_ZIP_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Official_ZIP_Postal_Code__c</fullName>
    <label>Official ZIP/Postal Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Place_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Birth__c</fullName>
    <label>Place of Birth</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VisaLetterController.cls
public class VisaLetterController {
	public List<Visa_Letter__c> visaLetters { get; set; }
	public String dateVisaLetter { get; set; }
	public String dateBirth { get; set; }
	public String dateIssue { get; set; }
	public String dateExpiry { get; set; }
	public String country { get; set; }

	public VisaLetterController() {
		visaLetters = new List<Visa_Letter__c>();
		dateVisaLetter = (Datetime.now()).format('MMMM dd, yyyy');
		String id = ApexPages.currentPage().getParameters().get('id');
		dateBirth = '';
		dateIssue = '';
		dateExpiry = '';
		country = '';
		visaLetters = [
			SELECT 
				Id, Name, Official_Country__c, Official_Street__c, Official_ZIP_Postal_Code__c, First_Name__c, Last_Name__c,
				Official_City__c, Official_State_Province__c, Sex__c, Date_of_Birth__c, Date_of_Issue__c, Date_of_Expiry__c,
				Passport_Number__c, Authority__c, Place_of_Birth__c, Gender__c
			FROM Visa_Letter__c
			WHERE Id = : id
		];

		if (visaLetters.size() > 0) {
			dateBirth = generateDate(visaLetters[0].Date_of_Birth__c);
			dateIssue = generateDate(visaLetters[0].Date_of_Issue__c);            
			dateExpiry = generateDate(visaLetters[0].Date_of_Expiry__c);

			Map<String, String> countryMap = new Map<String, String>();
			Schema.DescribeFieldResult field = Contact.MailingCountryCode.getDescribe();

			for (Schema.PicklistEntry f : field.getPicklistValues()) {
				countryMap.put(f.getValue(), f.getLabel());
			}

			country = countryMap.containsKey(visaLetters[0].Official_Country__c) ? countryMap.get(visaLetters[0].Official_Country__c) : '';
		}

	}
	
    @TestVisible
	private string generateDate(Date dt) {
		return (datetime.newInstance(dt.year(), dt.month(),dt.day())).format('MMMM dd, yyyy');
	}
}