force-app/main/default/objects/Fellowship__c/Fellowship__c.object-meta.xml
<CustomObject>
    <label>Fellowship</label>
    <nameField>
        <displayFormat>F-{0}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &quot;Clinical_Fellowship&quot;, &quot;Clinical&quot;, IF($RecordType.DeveloperName = &quot;Research_Fellowship&quot;, &quot;Research&quot;, &quot;&quot;)) + &quot; Fellowship &quot; + TEXT(YEAR(TODAY())+1)</defaultValue>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellowship__c/recordTypes/Clinical_Fellowship.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Fellowship</fullName>
    <active>true</active>
    <label>Clinical Fellowship</label>
</RecordType>

force-app/main/default/objects/Fellowship_Applications_Form__c/Fellowship_Applications_Form__c.object-meta.xml
<CustomObject>
    <label>Fellowship Application (Form)</label>
    <nameField>
        <displayFormat>FAF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowship Applications Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Further information required</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fellowship_Applications_Form</relationshipLabel>
    <relationshipName>Clinical_Fellowship_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <label>Fellowship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Research Fellowship Application Form</value>
        </filterItems>
        <filterItems>
            <field>Fellowship__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Research Fellowship</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Fellowship Application Form</value>
        </filterItems>
        <filterItems>
            <field>Fellowship__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Fellowship</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fellowship__c</referenceTo>
    <relationshipLabel>Fellowship_Applications_Form</relationshipLabel>
    <relationshipName>Clinical_Fellowship_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/recordTypes/Clinical_Fellowship_Application_Form.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Fellowship_Application_Form</fullName>
    <active>true</active>
    <label>Clinical Fellowship Application Form</label>
</RecordType>

force-app/main/default/classes/FellowshipApplicationsFormHelper_Test.cls
@IsTest
public with sharing class FellowshipApplicationsFormHelper_Test {
    @testSetup static void setup() {
        RecordType clinFellRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Fellowship__c' AND DeveloperName = 'Clinical_Fellowship'];
        RecordType clinFellAppFormRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Fellowship_Applications_Form__c' AND DeveloperName = 'Clinical_Fellowship_Application_Form'];
        List<Fellowship__c> fellowships = new List<Fellowship__c>();
        fellowships.add(new Fellowship__c(Name__c = 'Test1', RecordTypeId = clinFellRT.Id));
        insert fellowships;
        Contact contact = new Contact(FirstName = 'New', LastName='Contact');
        insert contact;
        List<Fellowship_Applications_Form__c> af = new List<Fellowship_Applications_Form__c>();
        af.add(new Fellowship_Applications_Form__c(Contact__c = contact.Id, Fellowship__c = fellowships[0].Id, RecordTypeId = clinFellAppFormRT.Id));
        af.add(new Fellowship_Applications_Form__c(Contact__c = contact.Id, Fellowship__c = fellowships[0].Id, RecordTypeId = clinFellAppFormRT.Id));
        insert af;
    }
    @IsTest public static void unlockRecordsTest(){
        List<Fellowship_Applications_Form__c> applicationForms = [SELECT Id, Approval_Status__c FROM Fellowship_Applications_Form__c];
        Approval.lock(applicationForms);
        for(Fellowship_Applications_Form__c af : applicationForms){
            af.Approval_Status__c = 'Further Information Required';
        }
        Test.startTest();
        update applicationForms;
        Test.stopTest();
    }
}