force-app/main/default/objects/Fellowship__c/Fellowship__c.object-meta.xml
<CustomObject>
    <label>Fellowship</label>
    <nameField>
        <displayFormat>F-{0}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &quot;Clinical_Fellowship&quot;, &quot;Clinical&quot;, IF($RecordType.DeveloperName = &quot;Research_Fellowship&quot;, &quot;Research&quot;, &quot;&quot;)) + &quot; Fellowship &quot; + TEXT(YEAR(TODAY())+1)</defaultValue>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellowship__c/recordTypes/Clinical_Fellowship.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Fellowship</fullName>
    <active>true</active>
    <label>Clinical Fellowship</label>
</RecordType>

force-app/main/default/objects/Fellowship_Applications_Form__c/Fellowship_Applications_Form__c.object-meta.xml
<CustomObject>
    <label>Fellowship Application (Form)</label>
    <nameField>
        <displayFormat>FAF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowship Applications Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fellowship_Applications_Form</relationshipLabel>
    <relationshipName>Clinical_Fellowship_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <label>Fellowship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Research Fellowship Application Form</value>
        </filterItems>
        <filterItems>
            <field>Fellowship__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Research Fellowship</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Fellowship Application Form</value>
        </filterItems>
        <filterItems>
            <field>Fellowship__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Fellowship</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fellowship__c</referenceTo>
    <relationshipLabel>Fellowship_Applications_Form</relationshipLabel>
    <relationshipName>Clinical_Fellowship_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Fellowship_Applications_Form__c/recordTypes/Clinical_Fellowship_Application_Form.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Fellowship_Application_Form</fullName>
    <active>true</active>
    <label>Clinical Fellowship Application Form</label>
</RecordType>

force-app/main/default/classes/ClinicalFellowshipAppController_Test.cls
@IsTest
public with sharing class ClinicalFellowshipAppController_Test {
    @TestSetup public static void setup(){
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Account acc = new Account(Name = 'Test');
        insert acc;
        Contact contact = new Contact(LastName = 'test', AccountId = acc.Id);
        insert contact;
        Id cclu = [SELECT Id FROM Profile WHERE Name = 'Member Community User Profile'].Id;
        User u = new User(
                Alias = 'test123', Email = 'test123@noemail.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = cclu, Country = 'United States', IsActive = true,
                ContactId = contact.Id, TimeZoneSidKey = 'America/Los_Angeles', Username = 'tester@noemail.com',
                CommunityNickname = 'commnick');
        insert u;
    }
    @IsTest public static void initWithoutContact(){
        try{
            ClinicalFellowshipApplicationController.getContact();
        } catch (Exception e){
            System.assertEquals(e.getMessage(), 'User do not have a contact');
        }
    }
    @IsTest public static void initWithContact(){
        User communityUser = [SELECT Id, ContactId FROM User WHERE Username='tester@noemail.com'];
        System.runAs(communityUser){
            Map<String, String> init = ClinicalFellowshipApplicationController.init();
            System.assertEquals(true, init.get('contact').contains('"Id":"'+communityUser.ContactId+'"'));
        }
    }
    @IsTest public static void createAppFormAndSubmitForApprovalTest(){
        RecordType clinFellRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Fellowship__c' AND DeveloperName = 'Clinical_Fellowship'];
        RecordType clinFellAppFormRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Fellowship_Applications_Form__c' AND DeveloperName = 'Clinical_Fellowship_Application_Form'];
        Fellowship__c fellowship = new Fellowship__c(Name__c = 'Test', RecordTypeId = clinFellRT.Id);
        insert fellowship;
        Contact contact = [SELECT Id FROM Contact WHERE LastName='test'];
        Fellowship_Applications_Form__c fellowshipApplicationForm = ClinicalFellowshipApplicationController.createAppForm(new Fellowship_Applications_Form__c(Fellowship__c = fellowship.Id, Contact__c = contact.Id, RecordTypeId = clinFellAppFormRT.Id));
        System.assertNotEquals('', fellowshipApplicationForm.Id);
        System.assertEquals(true, ClinicalFellowshipApplicationController.submitRecordForApproval(fellowshipApplicationForm.Id));
    }
}