force-app/main/default/objects/Event_Badge__c/Event_Badge__c.object-meta.xml
<CustomObject>
    <label>Event Badge</label>
    <nameField>
        <displayFormat>EB-{000000}</displayFormat>
        <label>Event Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Badge__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Event Badges</relationshipLabel>
    <relationshipName>Event_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/QR_Code_needed__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QR Code needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QRcodeBatch.cls
public without sharing class QRcodeBatch implements Database.Batchable<Participant__c>, Database.Stateful, Database.AllowsCallouts {
    public QRcodeBatch() {
        
    }
    Integer Count = 0;
    public List<Participant__c> start(Database.BatchableContext bc) {
        String statusRegistered = 'Registered';
        List<Participant__c> participants = [
            SELECT Id, Name, QR_Code_needed__c, Contact__r.Email, (SELECT Id FROM Event_Badges__r)
            FROM Participant__c 
            WHERE QR_Code_needed__c = true AND Status__c = :statusRegistered
        ];
        return participants;
    }
    public void execute(Database.BatchableContext BC, List<Participant__c> participants) {
        String networkId = Network.getNetworkId();
        String QRGeneratorLink = 'callout:QR_Code_Generator_Link/chart?chs=200x200&cht=qr&chl=';
        Map<String, ContentVersion> conVerToparticipantIdsMap = new Map<String, ContentVersion>();
        for (Participant__c participant : participants) {
            String Link = QRGeneratorLink + URL.getSalesforceBaseUrl().toExternalForm().replace('my.salesforce.com', 'lightning.force.com/lightning/r/Event_Badge__c').replace('salesforce.com', 'lightning.force.com/lightning/r/Event_Badge__c') + '/' + participant.Event_Badges__r[0].Id  + '/view';
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(link);
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            if (response.getStatusCode() == 200) {
                ContentVersion conVer = new ContentVersion();
                conVer.NetworkId = ConnectApi.Communities.getCommunities().communities[0].Id;
                conVer.ContentLocation = 'S';
                conVer.PathOnClient = 'QR code ' + participant.Name + '.png';
                conVer.Title = 'QR code ' + participant.Name + '.png';
                conVer.VersionData = response.getBodyAsBlob();
                conVerToparticipantIdsMap.put(participant.Id, conVer);
            }  
        }           
        if (conVerToparticipantIdsMap.size() > 0) {
            insert conVerToparticipantIdsMap.values();
            List<String> conVerIds = new List<String>();
            for (ContentVersion conVer : conVerToparticipantIdsMap.values()) {
                conVerIds.add(conVer.Id);
            }
            Map<ID, ContentVersion> conVersMap = new Map<ID, ContentVersion>([
                SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id IN :conVerIds
                ]);
            List<ContentDocumentLink> conDocLinks = new List<ContentDocumentLink>();
            for (String participantId : conVerToparticipantIdsMap.keySet()) {
                ContentDocumentLink conDocLink = New ContentDocumentLink();
                conDocLink.LinkedEntityId = participantId;
                conDocLink.ContentDocumentId = conVersMap.get(conVerToparticipantIdsMap.get(participantId).Id).ContentDocumentId;
                conDocLink.shareType = 'V';
                conDocLinks.add(conDocLink);
            }
            insert conDocLinks;
            for (Participant__c participant : participants) {
                if (conVerToparticipantIdsMap.keySet().contains(participant.Id)) {
                    participant.QR_Code_needed__c = false;
                }                
            }
            update participants;
        }
        
    }
    public void finish(Database.BatchableContext BC) {
        String jobName = 'get QR codes';
        List<CronTrigger> QRcodeJobs = [SELECT Id
                                FROM CronTrigger
                                WHERE CronJobDetail.Name = :jobName];
        for (CronTrigger QRcodeJob : QRcodeJobs) {
            System.abortJob(QRcodeJob.Id);
        }
        System.scheduleBatch(new QRcodeBatch(), jobName, 60, 70);
    }
}