force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Enable_synchronization__c.field-meta.xml
<CustomField>
    <fullName>Enable_synchronization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable synchronization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Indicates if this membership is active. This field use formula. The membership won&apos;t be active in this year if it expires in next one.</description>
    <formula>IF( Endless_Activation__c  = true, true, Expiration_date__c &gt;= DATETIMEVALUE( TODAY() ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Carer</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Corresponding member</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>New Member</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>RRFS Member</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
                <isActive>false</isActive>
                <label>Panel Member (Institution)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MembershipChatterMembersSync.cls
public with sharing class MembershipChatterMembersSync {
    public static void insertUndeleteMembershipMembers(List<MembershipContactAssotiation__c> newMembers) {
        List<MembershipContactAssotiation__c> selectedNewMembers = [
                SELECT Id, Name, Contact__c, Membership__r.Enable_synchronization__c, Membership__r.Name, Membership__r.Chatter_Group_Id__c
                FROM MembershipContactAssotiation__c
                WHERE Id IN:newMembers AND IsActive__c = TRUE
        ];
        List<Id> contactIds = new List<Id>();
        List<Id> groupsIds = new List<Id>();

        for (MembershipContactAssotiation__c mca : selectedNewMembers) {
            contactIds.add(mca.Contact__c);
            groupsIds.add(mca.Membership__r.Chatter_Group_Id__c);
        }

        List<User> users = [
                SELECT Id, ContactId, IsActive
                FROM User
                WHERE ContactId IN :contactIds
        ];
        List<CollaborationGroup> collGroups = [
                SELECT Id, Name
                FROM CollaborationGroup
                WHERE Id IN :groupsIds
        ];
        List<CollaborationGroupMember> existedGroupMembers = [
                SELECT CollaborationGroupId, MemberId
                FROM CollaborationGroupMember
                WHERE MemberId IN :users
        ];
        Set<CollaborationGroupMember> cgm = new Set<CollaborationGroupMember>();

        for (MembershipContactAssotiation__c mca : selectedNewMembers) {
            if (mca.Membership__r.Enable_synchronization__c) {

                for (CollaborationGroup chatterGroup : collGroups) {
                    if (chatterGroup.Id == mca.Membership__r.Chatter_Group_Id__c) {

                        for (User u : users) {
                            if (u.ContactId == mca.Contact__c) {
                                if (!SynchronizationGroupMembersHelper.chatterDuplicateCheck(existedGroupMembers, u.Id, chatterGroup.Id)) {
                                    cgm.add(new CollaborationGroupMember (CollaborationGroupId = chatterGroup.Id, MemberId = u.Id));
                                }
                            }
                        }

                    }
                }

            }
        }

        insert new List<CollaborationGroupMember>(cgm);
    }

    public static void deleteFromChatterGroup(List<MembershipContactAssotiation__c> membersToDelete) {
        //check if group synchronization enabled
        List<MembershipContactAssotiation__c> membersWithEnabledSync = [
                SELECT Id, Contact__c, Membership__c, Membership__r.Enable_synchronization__c, Membership__r.Chatter_Group_Id__c
                FROM MembershipContactAssotiation__c
                WHERE Id IN:membersToDelete
                AND Membership__r.Enable_synchronization__c = TRUE
                AND Membership__r.Chatter_Group_Id__c != NULL
        ];

        List<Id> contactIds = new List<Id>();
        List<Id> groupsIds = new List<Id>();
        for (MembershipContactAssotiation__c gcg : membersWithEnabledSync) {
            contactIds.add(gcg.Contact__c);
            groupsIds.add(gcg.Membership__r.Chatter_Group_Id__c);
        }

        //check if groupsMembers have double membership in group

        List<MembershipContactAssotiation__c> allContactsMembershipsAssotiations = [
                SELECT Id, Contact__c, Membership__c, Role__c
                FROM MembershipContactAssotiation__c
                WHERE Contact__c IN :contactIds AND IsActive__c = TRUE
        ];

        List<MembershipContactAssotiation__c> noDuplicateMembersWithEnabledSync = new List<MembershipContactAssotiation__c>();

        for (MembershipContactAssotiation__c triggerMember : membersWithEnabledSync) {
            Boolean duplicateFound = false;
            for (MembershipContactAssotiation__c allGroupMember : allContactsMembershipsAssotiations) {
                if(allGroupMember.Id != triggerMember.Id){
                    if (triggerMember.Contact__c == allGroupMember.Contact__c && triggerMember.Membership__c == allGroupMember.Membership__c) {
                        duplicateFound = true;
                        break;
                    }
                }
            }
            if(!duplicateFound){
                noDuplicateMembersWithEnabledSync.add(triggerMember);
            }
        }

        //check if chatter group exists

        Map<Id, CollaborationGroup> membersGroups = new Map<Id, CollaborationGroup>([
                SELECT Id, Name
                FROM CollaborationGroup
                WHERE Id IN :groupsIds
        ]);

        List<MembershipContactAssotiation__c> membersWithExistedChatterGroups = new List<MembershipContactAssotiation__c>();

        for(MembershipContactAssotiation__c groupMember : noDuplicateMembersWithEnabledSync){
            if(membersGroups.containsKey(groupMember.Membership__r.Chatter_Group_Id__c)){
                membersWithExistedChatterGroups.add(groupMember);
            }
        }

        //check if the member is part of related chatter group
        List<User> membersUsers = [
                SELECT Id, ContactId
                FROM User
                WHERE ContactId IN :contactIds
        ];

        List<CollaborationGroupMember> chatterGroupMembers = [
                SELECT CollaborationGroupId, MemberId
                FROM CollaborationGroupMember
                WHERE MemberId IN :membersUsers
        ];

        List<CollaborationGroupMember> groupMembersToDelete = new List<CollaborationGroupMember>();

        for(MembershipContactAssotiation__c groupMember : membersWithExistedChatterGroups){
            for(User user : membersUsers){
                if(user.ContactId == groupMember.Contact__c){
                    for (CollaborationGroupMember c : chatterGroupMembers) {
                        if (c.CollaborationGroupId == groupMember.Membership__r.Chatter_Group_Id__c && c.MemberId == user.Id) {
                            groupMembersToDelete.add(c);
                        }
                    }
                }
            }
        }

        //remove chatter group membership
        if(!groupMembersToDelete.isEmpty()){
            delete groupMembersToDelete;
        }
    }

    public static void insertDeleteChatterGroupMember(List<MembershipContactAssotiation__c> newMembers, List<MembershipContactAssotiation__c> oldMembers){
        List<MembershipContactAssotiation__c> onInsert = new List<MembershipContactAssotiation__c>();
        List<MembershipContactAssotiation__c> onDelete = new List<MembershipContactAssotiation__c>();

        for(Integer i = 0; i < newMembers.size(); i++){
            if(!oldMembers[i].IsActive__c && newMembers[i].IsActive__c){
                onInsert.add(newMembers[i]);
            }

            if(oldMembers[i].IsActive__c && !newMembers[i].IsActive__c){
                onDelete.add(newMembers[i]);
            }
        }

        if(!onInsert.isEmpty()){
            insertUndeleteMembershipMembers(onInsert);
        }

        if(!onDelete.isEmpty()){
            deleteFromChatterGroup(onDelete);
        }
    }
}