force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Endless_Activation__c.field-meta.xml
<CustomField>
    <fullName>Endless_Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endless Activation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date when current membership expires</description>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Indicates if this membership is active. This field use formula. The membership won&apos;t be active in this year if it expires in next one.</description>
    <formula>IF( Endless_Activation__c  = true, true, Expiration_date__c &gt;= DATETIMEVALUE( TODAY() ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Carer</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Corresponding member</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>New Member</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>RRFS Member</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
                <isActive>false</isActive>
                <label>Panel Member (Institution)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Society__c/Society__c.object-meta.xml
<CustomObject>
    <label>Society</label>
    <nameField>
        <label>Society Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Societies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Society__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Societies</relationshipLabel>
    <relationshipName>Societies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Society__c/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Society</label>
    <referenceTo>Society__c</referenceTo>
    <relationshipLabel>Societies</relationshipLabel>
    <relationshipName>Societies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Society__c/recordTypes/National_Neurological_Society.recordType-meta.xml
<RecordType>
    <fullName>National_Neurological_Society</fullName>
    <active>true</active>
    <label>National Neurological Society</label>
</RecordType>

force-app/main/default/objects/Society__c/recordTypes/Partner_Society.recordType-meta.xml
<RecordType>
    <fullName>Partner_Society</fullName>
    <active>true</active>
    <label>Partner Society</label>
</RecordType>

force-app/main/default/objects/Society_Member__c/Society_Member__c.object-meta.xml
<CustomObject>
    <label>Society Membership</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Society Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Society Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Society_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Society Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Society_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Society_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate member society - Delegate</fullName>
            </value>
            <value>
                <fullName>Collaborating Society</fullName>
            </value>
            <value>
                <fullName>Congress Manager</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Institutional Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Member at large</fullName>
            </value>
            <value>
                <fullName>Member no Benefit</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>President Elect</fullName>
            </value>
            <value>
                <fullName>RRFS National Society Delegate</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Secretary general</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Vice president</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Chief Executive Director = Ex. Director</fullName>
            </value>
            <value>
                <fullName>Chair EQTF</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
                <isActive>false</isActive>
                <label>Participant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Society_Member__c/fields/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <label>Society</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Neurological Society</value>
        </filterItems>
        <filterItems>
            <field>Society__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Neurological Society</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Societies</value>
        </filterItems>
        <filterItems>
            <field>Society__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Society</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Society__c</referenceTo>
    <relationshipName>Society_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Society_Member__c/recordTypes/National_Neurological_Society.recordType-meta.xml
<RecordType>
    <fullName>National_Neurological_Society</fullName>
    <active>true</active>
    <label>National Neurological Society</label>
</RecordType>

force-app/main/default/objects/Society_Member__c/recordTypes/Partner_Societies.recordType-meta.xml
<RecordType>
    <fullName>Partner_Societies</fullName>
    <active>true</active>
    <label>Partner Societies</label>
</RecordType>

force-app/main/default/classes/AssociateMembershipsAssignmentTest.cls
@IsTest
public with sharing class AssociateMembershipsAssignmentTest {
    @IsTest public static void assignAssociateMembership(){
        RecordType socRTNatNeurSoc = [SELECT Id FROM RecordType WHERE SobjectType = 'Society__c' AND DeveloperName = 'National_Neurological_Society'];
        RecordType socRTPartnerSoc = [SELECT Id FROM RecordType WHERE SobjectType = 'Society__c' AND DeveloperName = 'Partner_Society'];
        RecordType socMemRTNatNeurSoc = [SELECT Id FROM RecordType WHERE SobjectType = 'Society_Member__c' AND DeveloperName = 'National_Neurological_Society'];
        RecordType socMemRTPartnerSoc = [SELECT Id FROM RecordType WHERE SobjectType = 'Society_Member__c' AND DeveloperName = 'Partner_Societies'];
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert contact;
        List<Membership__c> newMemberships = new List<Membership__c>();
        newMemberships.add(new Membership__c(Name = 'Associate Membership', API__c = 'associate_individual_membership'));
        newMemberships.add(new Membership__c(Name = 'Associate Corresponding Membership', API__c = 'associate_corresponding_membership'));
        newMemberships.add(new Membership__c(Name = 'Full Institutional Members', API__c = 'full_institutional_members'));
        newMemberships.add(new Membership__c(Name = 'Corresponding Institutional Members', API__c = 'corresponding_institutional_members'));
        insert newMemberships;
        List<Society__c> societies = new List<Society__c>();
        societies.add(new Society__c(Name='TestSociety1', RecordTypeId=socRTNatNeurSoc.Id, Membership__c = newMemberships[2].Id));
        societies.add(new Society__c(Name='TestSociety2', RecordTypeId=socRTPartnerSoc.Id, Membership__c = newMemberships[3].Id));
        insert societies;

        //test start
        insert new Society_Member__c(Contact__c = contact.Id, Society__c = societies[1].Id, Is_Active__c = true, RecordTypeId=socMemRTPartnerSoc.Id, Role__c='President');
        System.assertEquals(0, [SELECT Id FROM MembershipContactAssotiation__c WHERE Contact__c =:contact.Id].size());
        Society_Member__c societyMemberWorking = new Society_Member__c(Contact__c = contact.Id, Society__c = societies[0].Id, Is_Active__c = true, RecordTypeId=socMemRTNatNeurSoc.Id, Role__c='Member');
        insert societyMemberWorking;
        System.assertEquals('associate_individual_membership', [SELECT Id, Membership__r.API__c FROM MembershipContactAssotiation__c WHERE Contact__c =:contact.Id AND IsActive__c = TRUE].Membership__r.API__c);
        societyMemberWorking.Is_Active__c = false;
        update societyMemberWorking;
        System.assertEquals(0, [SELECT Id, Membership__r.API__c FROM MembershipContactAssotiation__c WHERE Contact__c =:contact.Id AND IsActive__c = TRUE].size());
        societies[0].Membership__c = newMemberships[3].Id;
        update societies;
        societyMemberWorking.Is_Active__c = true;
        update societyMemberWorking;
        System.assertEquals('associate_corresponding_membership', [SELECT Id, Membership__r.API__c FROM MembershipContactAssotiation__c WHERE Contact__c =:contact.Id AND IsActive__c = TRUE].Membership__r.API__c);
        //check on duplicate membership status creation
        Society_Member__c societyMemberWorkingDuplicate = new Society_Member__c(Contact__c = contact.Id, Society__c = societies[0].Id, Is_Active__c = true, RecordTypeId=socMemRTNatNeurSoc.Id, Role__c='Member');
        insert societyMemberWorkingDuplicate;
        System.assertEquals(1, [SELECT Id, Membership__r.API__c FROM MembershipContactAssotiation__c WHERE Contact__c =:contact.Id AND IsActive__c = TRUE].size());
        //del duplicate soc_member record, membership status should still active
        delete societyMemberWorkingDuplicate;
        List<MembershipContactAssotiation__c> mca = [SELECT Id, Membership__r.API__c FROM MembershipContactAssotiation__c WHERE Contact__c =:contact.Id AND IsActive__c = TRUE];
        System.assertEquals(1, mca.size());
        //check if endless activation is not setup. membership status should be yesterday.
        mca[0].Endless_Activation__c = false;
        mca[0].Expiration_date__c = Date.today().addDays(1);
        update mca;
        delete societyMemberWorking;
        mca = [SELECT Id, IsActive__c, Expiration_date__c FROM MembershipContactAssotiation__c WHERE Id = :mca[0].Id];
        System.assert(!mca[0].IsActive__c);
        System.assertEquals(Date.today().addDays(-1), mca[0].Expiration_date__c);
        //check on activating old Membership Status, without creating new
        undelete societyMemberWorking;
        System.assert([SELECT Id, IsActive__c, Expiration_date__c FROM MembershipContactAssotiation__c WHERE Id = :mca[0].Id].IsActive__c);
    }

}