force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Enable_synchronization__c.field-meta.xml
<CustomField>
    <fullName>Enable_synchronization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable synchronization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduledSyncMembershipChatterBatch.cls
global class ScheduledSyncMembershipChatterBatch implements Schedulable {
    global void execute(SchedulableContext sc) {
        Map<Id, Membership__c> syncMemberships = new Map<Id, Membership__c>([SELECT Id FROM Membership__c WHERE Enable_synchronization__c = TRUE]);

        if(!syncMemberships.isEmpty()){
            SyncMembershipToChatterMembersBatch b = new SyncMembershipToChatterMembersBatch();
            b.membershipsIds = new List<Id>(syncMemberships.keySet());
            Database.executeBatch(b, 200);
        }
    }
}