force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Endless_Activation__c.field-meta.xml
<CustomField>
    <fullName>Endless_Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endless Activation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilsTest.cls
@isTest
public with sharing class UtilsTest {
    @TestSetup
    static void makeData(){
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        RecordType iprRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Industry_Partner'];
        Account acc = new Account(Name = 'Test', RecordTypeId = iprRT.Id);
        insert acc;

        Contact contact = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'info@test.com', AccountId = acc.Id, IsCommunityUser__c = true);
        insert contact;   
        
        Id memberProfileId = [SELECT Id FROM Profile WHERE Name = 'Member Community User Profile'].Id;

        User communityUser = new User(
                    Alias = 'test', Email = 'info@test.com',
                    EmailEncodingKey = 'UTF-8', FirstName = 'FirstName', LastName = 'LastName', LanguageLocaleKey = 'en_US',
                    LocaleSidKey = 'en_US', ProfileId = memberProfileId, Country = 'Germany', IsActive = true,
                    ContactId = contact.Id, TimeZoneSidKey = 'Europe/Berlin', Username = 'info@test.com'
        );
        insert communityUser;
    }
    @isTest
    public static void picklistValuesTest() { 
        List<Map<String, String>> picklistValuesListMap = Utils.picklistValues('Contact', 'Salutation');
        System.assertNotEquals(null, picklistValuesListMap.size());
    }

    @isTest
    public static void getContactMembershipsTest() {        
        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email = 'info@test.com' LIMIT 1];

        Membership__c membership = new Membership__c(Name = 'Test Membership', API__c = 'test');
        insert membership;
        MembershipContactAssotiation__c membershipStatus = new MembershipContactAssotiation__c(Contact__c = contacts[0].Id, Membership__c = membership.Id, Endless_Activation__c = true);
        insert membershipStatus;

        List<MembershipContactAssotiation__c> contactsMemebrships = Utils.getUserMemberships();
        System.assertEquals(0, contactsMemebrships.size()); 
    }
    
    @isTest
    public static void startOrderReminderTest() {        
        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email = 'info@test.com' LIMIT 1];

        Order__c order = new Order__c(Contact__c = contacts[0].Id);
        insert order;

        Utils.startOrderReminder();
    }
    
}