force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_date__c</fullName>
    <label>Assignment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Endless_Activation__c.field-meta.xml
<CustomField>
    <fullName>Endless_Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endless Activation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date when current membership expires</description>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Indicates if this membership is active. This field use formula. The membership won&apos;t be active in this year if it expires in next one.</description>
    <formula>IF( Endless_Activation__c  = true, true, Expiration_date__c &gt;= DATETIMEVALUE( TODAY() ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Status</label>
    <referenceTo>MembershipContactAssotiation__c</referenceTo>
    <relationshipLabel>MembershipContactAssotiations</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Carer</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Corresponding member</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>New Member</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>RRFS Member</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
                <isActive>false</isActive>
                <label>Panel Member (Institution)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Society__c/Society__c.object-meta.xml
<CustomObject>
    <label>Society</label>
    <nameField>
        <label>Society Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Societies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Society__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Societies</relationshipLabel>
    <relationshipName>Societies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Society__c/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Society</label>
    <referenceTo>Society__c</referenceTo>
    <relationshipLabel>Societies</relationshipLabel>
    <relationshipName>Societies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Society__c/recordTypes/National_Neurological_Society.recordType-meta.xml
<RecordType>
    <fullName>National_Neurological_Society</fullName>
    <active>true</active>
    <label>National Neurological Society</label>
</RecordType>

force-app/main/default/objects/Society_Member__c/Society_Member__c.object-meta.xml
<CustomObject>
    <label>Society Membership</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Society Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Society Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Society_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Society Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Society_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Society_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate member society - Delegate</fullName>
            </value>
            <value>
                <fullName>Collaborating Society</fullName>
            </value>
            <value>
                <fullName>Congress Manager</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Institutional Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Member at large</fullName>
            </value>
            <value>
                <fullName>Member no Benefit</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>President Elect</fullName>
            </value>
            <value>
                <fullName>RRFS National Society Delegate</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Secretary general</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Vice president</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Chief Executive Director = Ex. Director</fullName>
            </value>
            <value>
                <fullName>Chair EQTF</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
                <isActive>false</isActive>
                <label>Participant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Society_Member__c/fields/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <label>Society</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Neurological Society</value>
        </filterItems>
        <filterItems>
            <field>Society__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Neurological Society</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Societies</value>
        </filterItems>
        <filterItems>
            <field>Society__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Society</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Society__c</referenceTo>
    <relationshipName>Society_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Society_Member__c/recordTypes/National_Neurological_Society.recordType-meta.xml
<RecordType>
    <fullName>National_Neurological_Society</fullName>
    <active>true</active>
    <label>National Neurological Society</label>
</RecordType>

force-app/main/default/classes/AssociateMembershipsAssignment.cls
public with sharing class AssociateMembershipsAssignment {
    public static void associateMembershipsUpdateHandler(List<Society_Member__c> newSocietyMembers) {
        List<Society_Member__c> societyMembershipsActivate = new List<Society_Member__c>();
        List<Society_Member__c> societyMembershipsDeactivate = new List<Society_Member__c>();
        for (Society_Member__c sc : newSocietyMembers) {
            if(sc.Is_Active__c){
                societyMembershipsActivate.add(sc);
            }
            if(!sc.Is_Active__c || sc.Role__c != 'Member'){
                societyMembershipsDeactivate.add(sc);
            }
        }
        if(!societyMembershipsActivate.isEmpty()){
            assignAssociateMembership(societyMembershipsActivate);
        }
        if(!societyMembershipsDeactivate.isEmpty()){
            //deactivate
            deactivateAssociateMembership(societyMembershipsDeactivate);
        }
    }
    public static void assignAssociateMembership(List<Society_Member__c> societyMembers){
        Set<Id> contactsIds = new Set<Id>();
        Set<Id> societiesIds = new Set<Id>();
        for (Society_Member__c sm : societyMembers){
            contactsIds.add(sm.Contact__c);
            societiesIds.add(sm.Society__c);
        }
        List<Society__c> societies = [SELECT Id, Membership__r.API__c FROM Society__c WHERE Id IN :societiesIds];
        RecordType nationalNeurologySocietyRT = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'National_Neurological_Society' AND SobjectType = 'Society_Member__c'];
        Set<Id> potentialToAssociateMembership = new Set<Id>();
        Set<Id> potentialToAssociateCorrespondingMembership = new Set<Id>();
        List<MembershipContactAssotiation__c> upsetMembershipContactAssotiations = new List<MembershipContactAssotiation__c>();
        for(Society_Member__c sm : societyMembers){
            if(sm.RecordTypeId == nationalNeurologySocietyRT.Id && sm.Role__c == 'Member'){
                for(Society__c society : societies){
                    if(society.Id == sm.Society__c && society.Membership__r.API__c == 'full_institutional_members'){
                        potentialToAssociateMembership.add(sm.Contact__c);
                    }
                    if(society.Id == sm.Society__c && society.Membership__r.API__c == 'corresponding_institutional_members'){
                        potentialToAssociateCorrespondingMembership.add(sm.Contact__c);
                    }
                }
            }
        }
        upsetMembershipContactAssotiations = getUpsertMembershipStatuses(potentialToAssociateMembership, 'associate_individual_membership');
        upsetMembershipContactAssotiations.addAll(getUpsertMembershipStatuses(potentialToAssociateCorrespondingMembership, 'associate_corresponding_membership'));
        if(!upsetMembershipContactAssotiations.isEmpty()){
            upsert upsetMembershipContactAssotiations;
        }
    }
    public static List<MembershipContactAssotiation__c> getUpsertMembershipStatuses(Set<Id> contactsIds, String criteriaMembershipApi){
        List<MembershipContactAssotiation__c> resultList = new List<MembershipContactAssotiation__c>();
        List<Contact> contacts = [SELECT Id, (SELECT Id, Endless_Activation__c, Membership__c FROM MembershipContactAssotiations__r) FROM Contact WHERE Id IN :contactsIds];
        Membership__c criteriaMembership = [SELECT Id FROM Membership__c WHERE API__c = :criteriaMembershipApi LIMIT 1];
        for (Contact c : contacts){
            Boolean isFoundAssociateMembership = false;
            for (MembershipContactAssotiation__c memAss : c.MembershipContactAssotiations__r){
                if(memAss.Membership__c == criteriaMembership.Id){
                    isFoundAssociateMembership = true;
                    if(!memAss.Endless_Activation__c){
                        memAss.Endless_Activation__c = true;
                        resultList.add(memAss);
                    }
                }
            }
            if(!isFoundAssociateMembership){
                resultList.add(new MembershipContactAssotiation__c(Contact__c = c.Id, Membership__c = criteriaMembership.Id, Endless_Activation__c = true, Assignment_date__c = Date.today()));
            }
        }
        return resultList;
    }
    public static void deactivateAssociateMembership(List<Society_Member__c> societyMembers){
        RecordType nationalNeurologySocietyRT = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'National_Neurological_Society' AND SobjectType = 'Society_Member__c'];
        Set<Id> contactsIds = new Set<Id>();
        Set<Id> societiesIds = new Set<Id>();
        for(Society_Member__c sm : societyMembers){
            //check if society memberships have National_Neurological_Society record type
            if(sm.RecordTypeId == nationalNeurologySocietyRT.Id){
                contactsIds.add(sm.Contact__c);
                societiesIds.add(sm.Society__c);
            }
        }
        //check if contacts have required membership to deactivate
        List<MembershipContactAssotiation__c> contactsStatuses = [
                SELECT Id, Membership__c, Contact__c, Membership__r.API__c, Endless_Activation__c, Expiration_date__c
                FROM MembershipContactAssotiation__c
                WHERE Contact__c IN:contactsIds
                AND IsActive__c = TRUE
                AND (Membership__r.API__c = 'associate_individual_membership'
                OR Membership__r.API__c = 'associate_corresponding_membership')
        ];
        Set<Id> contactsWithAssMembership = new Set<Id>();
        for(MembershipContactAssotiation__c ms: contactsStatuses){
            for(Id contactId : contactsIds){
                if(ms.Contact__c == contactId){
                    contactsWithAssMembership.add(contactId);
                }
            }
        }
        //check if societies have required membership to deactivate contact's one
        Set<Society__c> societiesWithReqMembership = new Set<Society__c>();
        List<Society__c> societies = [SELECT Id, Membership__c, Membership__r.API__c FROM Society__c WHERE Id IN :societiesIds];
        for(Society__c society : societies){
            if(society.Membership__r.API__c == 'full_institutional_members' || society.Membership__r.API__c == 'corresponding_institutional_members'){
                societiesWithReqMembership.add(society);
            }
        }
        //select other contact's Society Membership which can activate associate memberships
        List<Society_Member__c> restSocietiesMemberships = [
                SELECT Id, Society__r.Membership__r.API__c, Contact__c
                FROM Society_Member__c
                WHERE Contact__c IN :contactsWithAssMembership
                AND (Society__r.Membership__r.API__c = 'full_institutional_members'
                OR Society__r.Membership__r.API__c = 'corresponding_institutional_members')
                AND Role__c = 'Member'
                AND RecordTypeId = :nationalNeurologySocietyRT.Id
                AND Is_Active__c = TRUE
        ];
        //Parse initial Societies Memberships, to have only those which can deactivate associate membership.
        List<Society_Member__c> parsedSocietyMemberships = new List<Society_Member__c>();
        for(Society_Member__c sm : societyMembers){
            for(Society__c soc : societiesWithReqMembership){
                if(sm.Society__c == soc.Id){
                    for (Id contId : contactsWithAssMembership){
                        if(sm.Contact__c == contId){
                            parsedSocietyMemberships.add(sm);
                        }
                    }
                }
            }
        }
        List<MembershipContactAssotiation__c> membershipStatusesToDeactivate = new List<MembershipContactAssotiation__c>();
        for(Society_Member__c sm : parsedSocietyMemberships){
            Society__c currentSociety = new Society__c();
            for(Society__c soc : societiesWithReqMembership){
                if(sm.Society__c == soc.Id){
                    currentSociety = soc;
                }
            }
            Boolean isFound = false;
            for(Society_Member__c otherSM : restSocietiesMemberships){
                if(sm.Contact__c == otherSM.Contact__c){
                    if(currentSociety.Membership__r.API__c == otherSM.Society__r.Membership__r.API__c){
                        isFound = true;
                        break;
                    }
                }
            }
            if(!isFound){
                String membershipToDeactivate = currentSociety.Membership__r.API__c == 'full_institutional_members'?'associate_individual_membership':'associate_corresponding_membership';
                for(MembershipContactAssotiation__c mca : contactsStatuses){
                    if(sm.Contact__c == mca.Contact__c && mca.Membership__r.API__c == membershipToDeactivate){
                        if(mca.Endless_Activation__c){
                            mca.Endless_Activation__c = false;
                        }
                        if(mca.Expiration_date__c>Date.today()){
                            mca.Expiration_date__c = Date.today().addDays(-1);
                        }
                        membershipStatusesToDeactivate.add(mca);
                    }
                }
            }
        }
        if(!membershipStatusesToDeactivate.isEmpty()){
            update membershipStatusesToDeactivate;
        }
    }
}