force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Billing_address__c.field-meta.xml
<CustomField>
    <fullName>Billing_address__c</fullName>
    <label>Billing address</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <label>Total amount</label>
    <summarizedField>Order_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Total_amount__c</fullName>
        <formula>(Quantity__c *  Amount__c) + Discount_Amount__c</formula>
        <label>Total amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicePageController.cls
public class InvoicePageController {
    public String name { get; set; }
    public String orderType { get; set; }
    public List<String> address { get; set; }
    public String invoiceNumber { get; set; }
    public Decimal totalAmount { get{
        if(totalAmount == null){
            totalAmount = 0;
        }
        return totalAmount.setScale(2);
    } set; }
    public Decimal paymentReceived { get{
        if(paymentReceived == null){
            paymentReceived = 0;
        }
        return paymentReceived.setScale(2);
    } set; }
    public String invoiceDate { get; set; }
    public List<Order_Item__c> memberships { get; set; }
    public List<Order_Item__c> products { get; set; }

    public InvoicePageController() {
        List<Order__c> order = new List<Order__c>();
        memberships = new List<Order_Item__c>();
        products = new List<Order_Item__c>();
        Id orderId = ApexPages.currentPage().getParameters().get('co');
        String invoNumber = ' ' + ApexPages.currentPage().getParameters().get('in');
        totalAmount = 0;
        address = new List<String>();
        name = '';
        invoiceNumber = '';
        invoiceDate = '';
        orderType = '';

        order = [
                SELECT Id, Total_amount__c, Contact__r.Name, Contact__r.Title, Contact__r.Selected_Mailing_Address__c, Payment_Date__c, Name, Invoice_Number__c, Billing_address__c, Type__c,
                        (SELECT Id, Total_amount__c, Quantity__c, Product__c, Membership__c ,Membership__r.Name, Product__r.Name FROM Order_Items__r ORDER BY CreatedDate DESC)
                FROM Order__c
                WHERE Id = :orderId
        ];

        paymentReceived = (Decimal) [SELECT SUM(Amount__c) FROM Transaction__c WHERE Status__c = 'Success' AND Order_Custom__c = :order[0].Id][0].get('expr0');

        if (!order.isEmpty() && !order[0].Order_Items__r.isEmpty()) {
            Order__c currentOrder = order[0];
            orderType = order[0].Type__c;
            name = currentOrder.Contact__r.Name;
            name += currentOrder.Contact__r.Title==null?'':', '+currentOrder.Contact__r.Title;
            invoiceDate = currentOrder.Payment_Date__c != null ? currentOrder.Payment_Date__c.format('dd MMMM, yyyy') : Datetime.now().format('dd MMMM, yyyy');
            totalAmount = currentOrder.Total_amount__c;
            invoiceNumber = invoNumber != null ? invoNumber : ' EIMF ' + String.valueOf(Date.today().year()) + '/0000';

            for (Order_Item__c oi : currentOrder.Order_Items__r) {
                if (oi.Membership__c != null) {
                    memberships.add(oi);
                } else if (oi.Product__c != null) {
                    products.add(oi);
                }
            }

            if(order[0].Total_amount__c != 0 && currentOrder.Billing_address__c != null){
                address = currentOrder.Billing_address__c.split('\n');
            } else {
                if (currentOrder.Contact__r.Selected_Mailing_Address__c != null) {
                    address = currentOrder.Contact__r.Selected_Mailing_Address__c.split('<br>');
                }
            }

        }
    }
}