force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Billing_address__c.field-meta.xml
<CustomField>
    <fullName>Billing_address__c</fullName>
    <label>Billing address</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderUtils_Test.cls
@IsTest
public with sharing class OrderUtils_Test {
    @TestSetup public static void setup(){
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Contact c = new Contact(LastName = 'testLastName');
        insert c;
        Membership__c m = new Membership__c(Name='test', API__c='test');
        insert m;
        Order__c order = new Order__c(Contact__c=c.Id);
        insert order;
        Order_Item__c orderItem = new Order_Item__c(Order_Custom__c = order.Id, Amount__c=100, Quantity__c = 1, Membership__c = m.Id);
        insert orderItem;
    }
    @IsTest public static void generateOrderTest(){
        Contact contact = [SELECT Id FROM Contact WHERE LastName = 'testLastName' LIMIT 1];
        Membership__c membership = [SELECT Id FROM Membership__c LIMIT 1];
        List<Map<String,Object>> objects = new List<Map<String,Object>>();
        for(Integer i =0; i<10;i++){
            objects.add(new Map<String, Object>{'Membership__c'=>membership.Id, 'Amount__c'=>10, 'Quantity__c'=>1});
        }
        String orderId = OrderUtils.generateOrder(contact.Id, objects, 'New');
        System.assertNotEquals([SELECT Id FROM Order__c WHERE Id=:orderId], null);
        System.assertEquals([SELECT Id FROM Order_Item__c WHERE Order_Custom__c=:orderId].size(), 10);
    }
    @IsTest public static void createTransactionTestSuccessWithFullAmount(){
        Order__c order = [SELECT Id FROM Order__c WHERE Contact__r.LastName = 'testLastName'];
        OrderUtils.createTransaction(new Transaction__c(Order_Custom__c=order.Id, Amount__c = 100, Status__c='Success'));
        System.assertEquals([SELECT Id FROM Transaction__c WHERE Order_Custom__c =:order.Id].size(), 1);
        Order__c updatedOrder = [SELECT Id, Status__c, Payment_Date__c FROM Order__c WHERE Id = :order.Id];
        System.assertEquals(updatedOrder.Status__c, 'Paid');
        System.assertEquals(
                Date.newInstance(updatedOrder.Payment_Date__c.year(), updatedOrder.Payment_Date__c.month(), updatedOrder.Payment_Date__c.day()),
                Date.today()
        );
    }
    @IsTest public static void createTransactionTestSuccessWithNotFullAmount(){
        Order__c order = [SELECT Id FROM Order__c WHERE Contact__r.LastName = 'testLastName'];
        OrderUtils.createTransaction(new Transaction__c(Order_Custom__c=order.Id, Amount__c = 99, Status__c='Success'));
        System.assertEquals([SELECT Id FROM Transaction__c WHERE Order_Custom__c =:order.Id].size(), 1);
        Order__c updatedOrder = [SELECT Id, Status__c, Payment_Date__c FROM Order__c WHERE Id = :order.Id];
        System.assertNotEquals(updatedOrder.Status__c, 'Paid');
        System.assertEquals(updatedOrder.Payment_Date__c, null);
    }
    @IsTest public static void writeOrderBillingAddressTest(){
        Order__c order = [SELECT Id FROM Order__c LIMIT 1];
        PaymentHttpRequest.writeOrderBillingAddress(order.Id, PaymentHttpRequest_Test.addressesObject);
        order = [SELECT Id, Billing_address__c FROM Order__c LIMIT 1];
        System.assertNotEquals(null, order.Billing_address__c);
    }
}