force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date when current membership expires</description>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MembershipContainerController_Test.cls
@IsTest
public with sharing class MembershipContainerController_Test {
    @IsTest public static void getCurrentContactMembershipsTest(){
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Account acc = new Account(Name = 'Individuals (Contacts)');
        insert acc;
        Contact c = new Contact(LastName='Test', AccountId= acc.Id);
        insert c;
        Id cclu = [SELECT Id FROM profile WHERE Name = 'Customer Community Login User'].Id;
        User user = new User(
                Alias = 'test123', Email = 'test123@noemail.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = cclu, Country = 'Belarus', IsActive = true,
                ContactId = c.Id, TimeZoneSidKey = 'America/Los_Angeles', Username = 'tester@noemail.com');
        insert user;
        Membership__c m = new Membership__c(Name='Test', API__c='Test');
        insert m;
        MembershipContactAssotiation__c mca = new MembershipContactAssotiation__c(Membership__c = m.Id, Contact__c=c.Id, Expiration_date__c= Datetime.now().addDays(15));
        insert mca;
        System.runAs(user) {
            String result = MembershipContainerController.getCurrentContactMemberships();
            Map<String, Object> mapResult = (Map<String, Object>) JSON.deserializeUntyped(result);
            List<Object> memberships= (List<Object>) JSON.deserializeUntyped(JSON.serialize(mapResult.get('memberships')));
            MembershipContactAssotiation__c mapObject  = (MembershipContactAssotiation__c) JSON.deserialize(JSON.serialize(memberships[0]), MembershipContactAssotiation__c.class);
            System.assertEquals(mapObject.Membership__r.Name, m.Name);
            System.assertEquals(mapObject.Id, mca.Id);
            System.assertEquals('[]',JSON.serialize(mapResult.get('app-forms')));
        }
    }

}