force-app/main/default/objects/Fellowship_Applications_Form__c/Fellowship_Applications_Form__c.object-meta.xml
<CustomObject>
    <label>Fellowship Application (Form)</label>
    <nameField>
        <displayFormat>FAF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellowship Applications Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellowship_Applications_Form__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Further information required</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FellowshipApplicationsFormTriggerHelper.cls
public with sharing class FellowshipApplicationsFormTriggerHelper {
    public static void unlockRecords(List<Fellowship_Applications_Form__c> oldForms, List<Fellowship_Applications_Form__c> newForms){
        List<String> formsIdsToUnlock = new List<String>();
        for(Integer i=0; i<newForms.size(); i++){
            if(newForms[i].Approval_Status__c != oldForms[i].Approval_Status__c && newForms[i].Approval_Status__c == 'Further Information Required' && newForms[i].Id == oldForms[i].Id){
                formsIdsToUnlock.add(newForms[i].Id);
            }
        }
        if(!formsIdsToUnlock.isEmpty()){
            unlockInFuture(JSON.serialize(formsIdsToUnlock));
        }
    }
    @future public static void unlockInFuture(String ids){
        List<String> idsList = (List<String>) JSON.deserialize(ids, List<String>.class);
        Map<Id, Boolean> checkResult = Approval.isLocked(idsList);
        List<String> idsToUnlock = new List<String>();
        for(Id id : checkResult.keySet()){
            if(checkResult.get(id)){
                idsToUnlock.add(id);
            }
        }
        List<Approval.UnlockResult> lrList = Approval.unlock(idsToUnlock);
    }
}