force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_date__c</fullName>
    <label>Assignment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Endless_Activation__c.field-meta.xml
<CustomField>
    <fullName>Endless_Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endless Activation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Status</label>
    <referenceTo>MembershipContactAssotiation__c</referenceTo>
    <relationshipLabel>MembershipContactAssotiations</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Carer</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Corresponding member</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>New Member</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>RRFS Member</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
                <isActive>false</isActive>
                <label>Panel Member (Institution)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Society__c/Society__c.object-meta.xml
<CustomObject>
    <label>Society</label>
    <nameField>
        <label>Society Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Societies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Society__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Societies</relationshipLabel>
    <relationshipName>Societies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Society__c/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Society</label>
    <referenceTo>Society__c</referenceTo>
    <relationshipLabel>Societies</relationshipLabel>
    <relationshipName>Societies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Society__c/recordTypes/National_Neurological_Society.recordType-meta.xml
<RecordType>
    <fullName>National_Neurological_Society</fullName>
    <active>true</active>
    <label>National Neurological Society</label>
</RecordType>

force-app/main/default/objects/Society_Member__c/Society_Member__c.object-meta.xml
<CustomObject>
    <label>Society Membership</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Society Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Society Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Society_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Society Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Society_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Society_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate member society - Delegate</fullName>
            </value>
            <value>
                <fullName>Collaborating Society</fullName>
            </value>
            <value>
                <fullName>Congress Manager</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
            <value>
                <fullName>Individual Delegate</fullName>
            </value>
            <value>
                <fullName>Institutional Delegate</fullName>
            </value>
            <value>
                <fullName>Managing Editor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Member at large</fullName>
            </value>
            <value>
                <fullName>Member no Benefit</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
            </value>
            <value>
                <fullName>Past president</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>President Elect</fullName>
            </value>
            <value>
                <fullName>RRFS National Society Delegate</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Secretary general</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Vice president</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Chief Executive Director = Ex. Director</fullName>
            </value>
            <value>
                <fullName>Chair EQTF</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
                <isActive>false</isActive>
                <label>Participant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Society_Member__c/fields/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <label>Society</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Neurological Society</value>
        </filterItems>
        <filterItems>
            <field>Society__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Neurological Society</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Societies</value>
        </filterItems>
        <filterItems>
            <field>Society__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Society</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Society__c</referenceTo>
    <relationshipName>Society_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Society_Member__c/recordTypes/National_Neurological_Society.recordType-meta.xml
<RecordType>
    <fullName>National_Neurological_Society</fullName>
    <active>true</active>
    <label>National Neurological Society</label>
</RecordType>

force-app/main/default/classes/AssignMembershipsToSocieties.cls
global class AssignMembershipsToSocieties implements Database.Batchable<sObject>, Database.Stateful {
    global Log__c log = new Log__c();
    global List<Membership__c> memberships = new List<Membership__c>();
    global Database.QueryLocator start(Database.BatchableContext bc) {
        log.Process_Name__c='Batch: AssignMembershipsToSocieties';
        log.Start_Time__c=Datetime.now();
        log.Status__c='In Progress';
        insert log;
        log.Status__c='Completed';
        log.Message__c='';
        memberships = [SELECT Id, API__c FROM Membership__c WHERE API__c = 'full_institutional_members' OR API__c='corresponding_institutional_members'];
        return Database.getQueryLocator(
                'SELECT Id, tx_efnsusr_type_name__c, Membership__c, RecordType.DeveloperName FROM Society__c WHERE tx_efnsusr_type_name__c = \'Society\' OR tx_efnsusr_type_name__c = \'Corresponding Societies\''
        );
    }
    global List<MembershipContactAssotiation__c> getUpsertMembershipStatuses(Set<Id> contacIds, Membership__c criteriaMembership){
        List<MembershipContactAssotiation__c> resultList = new List<MembershipContactAssotiation__c>();
        List<Contact> contactsWithSocietyType = [SELECT Id, (SELECT Id, Endless_Activation__c, Membership__c FROM MembershipContactAssotiations__r) FROM Contact WHERE Id IN :contacIds];
        for (Contact c : contactsWithSocietyType){
            Boolean isFoundAssociateMembership = false;
            for (MembershipContactAssotiation__c memAss : c.MembershipContactAssotiations__r){
                if(memAss.Membership__c == criteriaMembership.Id){
                    isFoundAssociateMembership = true;
                    if(!memAss.Endless_Activation__c){
                        memAss.Endless_Activation__c = true;
                        resultList.add(memAss);
                    }
                }
            }
            if(!isFoundAssociateMembership){
                resultList.add(new MembershipContactAssotiation__c(Contact__c = c.Id, Membership__c = criteriaMembership.Id, Endless_Activation__c = true, Assignment_date__c = Date.today()));
            }
        }
        return resultList;
    }
    global void execute(Database.BatchableContext bc, List<Society__c> records) {
        try {
            for(Society__c s : records){
                for (Membership__c m : memberships){
                    if(s.tx_efnsusr_type_name__c == 'Society' && m.API__c == 'full_institutional_members'){
                        s.Membership__c = m.Id;
                    }else if(s.tx_efnsusr_type_name__c == 'Corresponding Societies' && m.API__c == 'corresponding_institutional_members'){
                        s.Membership__c = m.Id;
                    }
                }
            }
            update records;

            List<Society__c> societiesToAssignMembershipForContacts = new List<Society__c>();
            for(Society__c s : records){
                if(s.RecordType.DeveloperName == 'National_Neurological_Society'){
                    societiesToAssignMembershipForContacts.add(s);
                }
            }

            List<Society_Member__c> societyMembers = [SELECT Id, Society__r.tx_efnsusr_type_name__c, Contact__c FROM Society_Member__c WHERE Society__c IN :societiesToAssignMembershipForContacts AND Role__c = 'Member'];
            Set<Id> contactsIdsForAssMembership = new Set<Id>();
            Set<Id> contactsIdsForAssCorrMembership = new Set<Id>();
            for (Society_Member__c sm : societyMembers){
                if(sm.Society__r.tx_efnsusr_type_name__c == 'Society'){
                    contactsIdsForAssMembership.add(sm.Contact__c);
                } else if(sm.Society__r.tx_efnsusr_type_name__c == 'Corresponding Societies') {
                    contactsIdsForAssCorrMembership.add(sm.Contact__c);
                }
            }
            Membership__c associateMembership = [SELECT Id FROM Membership__c WHERE API__c = 'associate_individual_membership' LIMIT 1];
            Membership__c associateCorrespondingMembership = [SELECT Id FROM Membership__c WHERE API__c = 'associate_corresponding_membership' LIMIT 1];
            List<MembershipContactAssotiation__c> upsetMembershipContactAssotiations = new List<MembershipContactAssotiation__c>();
//            List<Contact> contactsWithSocietyType = [SELECT Id, (SELECT Id, Endless_Activation__c, Membership__c FROM MembershipContactAssotiations__r) FROM Contact WHERE Id IN :contactsWithSocietyTypeIds];
//            for (Contact c : contactsWithSocietyType){
//                Boolean isFoundAssociateMembership = false;
//                for (MembershipContactAssotiation__c memAss : c.MembershipContactAssotiations__r){
//                    if(memAss.Membership__c == associateMembership.Id){
//                        isFoundAssociateMembership = true;
//                        if(!memAss.Endless_Activation__c){
//                            memAss.Endless_Activation__c = true;
//                            upsetMembershipContactAssotiations.add(memAss);
//                        }
//                    }
//                }
//                if(!isFoundAssociateMembership){
//                    upsetMembershipContactAssotiations.add(new MembershipContactAssotiation__c(Contact__c = c.Id, Membership__c = associateMembership.Id));
//                }
//            }
            upsetMembershipContactAssotiations = getUpsertMembershipStatuses(contactsIdsForAssMembership, associateMembership);
            upsetMembershipContactAssotiations.addAll(getUpsertMembershipStatuses(contactsIdsForAssCorrMembership, associateCorrespondingMembership));
            upsert upsetMembershipContactAssotiations;
        }catch (Exception e){
            log.Message__c+=e.getMessage()+'\n';
            log.Status__c='Error';
        }
    }
    global void finish(Database.BatchableContext bc) {
        log.End_Time__c = Datetime.now();
        update log;
    }

}