force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment &amp; Invoice</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Common</fullName>
                <isActive>false</isActive>
                <label>Common</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Purchase_Type__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Type__c</fullName>
    <description>Actual for memberships invoices</description>
    <label>Purchase Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateInvoicesBatch.cls
/*
Unit Tests are located in the RemoveAndGenerateInvoicesBatchesTest class
* */
public class GenerateInvoicesBatch implements Database.Batchable<SObject>, Database.Stateful {
    public Log__c log = new Log__c();
    public Database.QueryLocator start(Database.BatchableContext bc) {
        log.Process_Name__c = 'Batch: GenerateInvoicesBatch';
        log.Start_Time__c = Datetime.now();
        log.Status__c = 'In Progress';
        insert log;
        log.Status__c = 'Completed';
        log.Message__c = '';

        return Database.getQueryLocator(
                'SELECT Id, Name, Invoice_Number__c, Purchase_Type__c, Type__c FROM Order__c WHERE Status__c = \'Paid\' ORDER BY CreatedDate ASC'
        );
    }
    public void execute(Database.BatchableContext bc, List<Order__c> orders) {
        try {
            List<ContentVersion> attachments = new List<ContentVersion>();
            List<ContentVersion> newAttachments = new List<ContentVersion>();
            Map<String, ContentVersion> attachmentMap = new Map<String, ContentVersion>();
            Map<String, String> fileOrderMap = new Map<String, String>();
            Set<String> attachmentNames = new Set<String>();

            // Generate new Invoice Numbers
            Boolean generated = InvoicePDFGenerator.generateInvoiceNumber(orders);

            List<Network> community = [SELECT Id FROM Network WHERE Name = 'ean'];

            if (generated) {

                // Collect all Attachment Names
                for (Order__c o : orders) {
                    attachmentNames.add('Invoice_' + o.Name + '.pdf');
                }

                // Collect all related Attachments
                attachments = [SELECT Title, VersionData FROM ContentVersion WHERE Title IN :attachmentNames];

                for (ContentVersion at : attachments) {
                    attachmentMap.put(at.Title, at);
                }

                for (Order__c o : orders) {
                    ContentVersion att;

                    // if PDF doesn't exist
                    if (!attachmentMap.keySet().contains('Invoice_' + o.Name + '.pdf')) {
                        PageReference defaultPage = new PageReference('/apex/InvoicePage');
                        defaultPage.getParameters().put('co', o.Id);
                        defaultPage.getParameters().put('in', o.Invoice_Number__c);
                        Blob pageData;

                        if (Test.isRunningTest()) {
                            pageData = Blob.valueOf('Unit.Test');
                        } else {
                            pageData = defaultPage.getContent();
                        }
                        att = new ContentVersion(
                                VersionData = pageData,
                                Title = 'Invoice_' + o.Name + '.pdf',
                                PathOnClient = 'Invoice_' + o.Name + '.pdf',
                                IsMajorVersion = true,
                                ContentLocation = 'S',
                                NetworkId = community[0].Id
                        );
                        newAttachments.add(att);
                        fileOrderMap.put(att.Title, o.Id);
                        // else if PDF exists
                    } else {
                        att = attachmentMap.get('Invoice_' + o.Name + '.pdf');
                    }
                }

                // Insert new PDF Invoices as Attachments
                if (!newAttachments.isEmpty()) {
                    insert newAttachments;

                    List<ContentVersion> cds = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id IN :newAttachments];
                    List<ContentDocumentLink> cdLinks = new List<ContentDocumentLink>();
                    for (ContentVersion cd : cds) {
                        Id orderId = fileOrderMap.get(cd.Title);
                        ContentDocumentLink link = new ContentDocumentLink(LinkedEntityId = orderId,
                                ShareType = 'V', ContentDocumentId = cd.ContentDocumentId, Visibility = 'AllUsers');
                        cdLinks.add(link);
                    }

                    if (!cdLinks.isEmpty()) {
                        insert cdLinks;
                    }
                }
            }

        } catch (Exception e) {
            log.Message__c += e.getMessage() + '\n';
            log.Status__c = 'Error';
        }
    }
    public void finish(Database.BatchableContext bc) {
        log.End_Time__c = Datetime.now();
        update log;
    }
}