force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateChatterGroupNotificationFreqBatch.cls
public with sharing class UpdateChatterGroupNotificationFreqBatch implements Database.Batchable<SObject>, Database.Stateful {
    public Log__c log = new Log__c();
    public List<Id> groupsIds = new List<Id>();
    public String notificationFrequency;

    public Database.QueryLocator start(Database.BatchableContext bc) {
        log.Process_Name__c='Batch: UpdateChatterGroupNotificationFreqBatch';
        log.Start_Time__c=Datetime.now();
        log.Status__c='In Progress';
        insert log;
        log.Status__c='Completed';
        log.Message__c='';

        return Database.getQueryLocator(
                'SELECT Id, NotificationFrequency FROM CollaborationGroupMember WHERE CollaborationGroupId IN :groupsIds'
        );
    }
    public void execute(Database.BatchableContext bc, List<CollaborationGroupMember> records) {
        try {

            for(CollaborationGroupMember groupMember : records){
                if(notificationFrequency != null && notificationFrequency != ''){
                    groupMember.NotificationFrequency = notificationFrequency;
                }
            }

            update records;
        }catch (Exception e){
            log.Message__c+=e.getMessage()+'\n';
            log.Status__c='Error';
        }
    }
    public void finish(Database.BatchableContext bc) {
        log.End_Time__c = Datetime.now();
        update log;
    }

}