force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/JSONResponse__c.field-meta.xml
<CustomField>
    <fullName>JSONResponse__c</fullName>
    <label>JSONResponse</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditcard</fullName>
                <label>Card</label>
            </value>
            <value>
                <fullName>paypal</fullName>
                <label>Pay Pal</label>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <description>Stores transaction id from JSON response</description>
    <label>Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateTransactionRecordsBatch.cls
//Tests located in OneTimeRunBatchTest
public class UpdateTransactionRecordsBatch implements Database.Batchable<SObject>, Database.Stateful {
    public Log__c log = new Log__c();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        log.Process_Name__c='Batch: UpdateTransactionRecordsBatch';
        log.Start_Time__c=Datetime.now();
        log.Status__c='In Progress';
        insert log;
        log.Status__c='Completed';
        log.Message__c='';

        return Database.getQueryLocator(
                'SELECT Id, JSONResponse__c, Reference_Id__c FROM Transaction__c WHERE Payment_Method__c!=NULL'
        );
    }

    public void execute(Database.BatchableContext bc, List<Transaction__c> records) {
        try{
            for(Transaction__c tr : records){
                if(tr.Reference_Id__c == null && tr.JSONResponse__c!=null){
                    String JSONResponse = tr.JSONResponse__c.replaceAll('\\n', '');
                    if(JSONResponse.contains('transaction-id')) {
                        System.debug('OwnFlag: '+((Map<String, Object>) JSON.deserializeUntyped(tr.JSONResponse__c)).containsKey('payment'));
                        if (((Map<String, Object>) JSON.deserializeUntyped(tr.JSONResponse__c)).containsKey('payment')) {
                            Object payment = ((Map<String, Object>) JSON.deserializeUntyped(tr.JSONResponse__c)).get('payment');
                            if (((Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(payment))).containsKey('transaction-id') && payment != null) {
                                Object transactionId = ((Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(payment))).get('transaction-id');
                                tr.Reference_Id__c = (String) transactionId;
                            }
                        }
                    }
                }
            }
            update records;
        } catch (Exception e){
            log.Message__c+=e.getMessage()+'\n';
            log.Status__c='Error';
        }
    }

    public void finish(Database.BatchableContext bc) {
        log.End_Time__c = Datetime.now();
        update log;
    }
}