force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Indicates if this membership is active. This field use formula. The membership won&apos;t be active in this year if it expires in next one.</description>
    <formula>IF( Endless_Activation__c  = true, true, Expiration_date__c &gt;= DATETIMEVALUE( TODAY() ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Status</label>
    <referenceTo>MembershipContactAssotiation__c</referenceTo>
    <relationshipLabel>MembershipContactAssotiations</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateUserProfileBatch.cls
global class UpdateUserProfileBatch implements Database.Batchable<SObject>, Database.Stateful{
        global Log__c log = new Log__c();
        global Id memberProfileId;
        global Database.QueryLocator start(Database.BatchableContext bc) {
            memberProfileId = [SELECT Id, Name FROM Profile WHERE Name = 'Member Community User Profile'].Id;
            log.Process_Name__c='Batch: UpdateUserProfileBatch';
            log.Start_Time__c=Datetime.now();
            log.Status__c='In Progress';
            insert log;
            log.Status__c='Completed';
            log.Message__c='';

            return Database.getQueryLocator(
                    'SELECT Id, (SELECT Id, IsActive__c FROM MembershipContactAssotiations__r) ' +
                    'FROM Contact'
            );
        }
        global void execute(Database.BatchableContext bc, List<Contact> records) {
            try {
                List<Contact> contactsToUpdate  = new List<Contact>();
                for(Contact c : records){
                    if(c.MembershipContactAssotiations__r.size()>0){
                        for(MembershipContactAssotiation__c mca : c.MembershipContactAssotiations__r){
                            if(mca.IsActive__c){
                                contactsToUpdate.add(c);
                                break;
                            }
                        }
                    }
                }
                List<User> usersToUpdate = [SELECT Id, ProfileId FROM User WHERE ContactId IN :contactsToUpdate];
                for(User u : usersToUpdate){
                    if(u.ProfileId != memberProfileId){
                        u.ProfileId = memberProfileId;
                    }
                }
                if(!usersToUpdate.isEmpty()){
                    update usersToUpdate;
                }
            }catch (Exception e){
                log.Message__c+=e.getMessage()+'\n';
                log.Status__c='Error';
            }
        }
        global void finish(Database.BatchableContext bc) {
            log.End_Time__c = Datetime.now();
            update log;
        }
}