force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>D-{0000000000}</displayFormat>
        <label>Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <description>The discount amount in euro or %</description>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>%</fullName>
                <default>true</default>
                <label>%</label>
            </value>
            <value>
                <fullName>€</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/PromoCode__c.field-meta.xml
<CustomField>
    <fullName>PromoCode__c</fullName>
    <label>Promo Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/DiscountItem__c.object-meta.xml
<CustomObject>
    <label>Discount Item</label>
    <nameField>
        <displayFormat>DI-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DiscountItem__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Max_Participants__c.field-meta.xml
<CustomField>
    <fullName>Max_Participants__c</fullName>
    <label>Max Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End__c.field-meta.xml
<CustomField>
    <fullName>Session_End__c</fullName>
    <label>Session End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start__c.field-meta.xml
<CustomField>
    <fullName>Session_Start__c</fullName>
    <label>Session Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Career development session</fullName>
            </value>
            <value>
                <fullName>Case-based workshop</fullName>
            </value>
            <value>
                <fullName>Controversy</fullName>
            </value>
            <value>
                <fullName>Focused Workshop</fullName>
            </value>
            <value>
                <fullName>Hands-on Course</fullName>
            </value>
            <value>
                <fullName>Interactive Session</fullName>
            </value>
            <value>
                <fullName>Plenary Sysmposium</fullName>
            </value>
            <value>
                <fullName>Special Session</fullName>
            </value>
            <value>
                <fullName>Topical Symposium</fullName>
            </value>
            <value>
                <fullName>ePoster</fullName>
            </value>
            <value>
                <fullName>Oral Presentation</fullName>
            </value>
            <value>
                <fullName>Symposia</fullName>
            </value>
            <value>
                <fullName>Teaching Course</fullName>
            </value>
            <value>
                <fullName>Scientific theatre</fullName>
            </value>
            <value>
                <fullName>ePresentation</fullName>
            </value>
            <value>
                <fullName>Forum Programmes</fullName>
            </value>
            <value>
                <fullName>Networking Session</fullName>
            </value>
            <value>
                <fullName>3-Day Satellite Session</fullName>
                <isActive>false</isActive>
                <label>3-Day Satellite Session</label>
            </value>
            <value>
                <fullName>3-Days Satellite Session</fullName>
                <isActive>false</isActive>
                <label>3-Days Satellite Session</label>
            </value>
            <value>
                <fullName>Brain Challenge</fullName>
                <isActive>false</isActive>
                <label>Brain Challenge</label>
            </value>
            <value>
                <fullName>Controversy Session</fullName>
                <isActive>false</isActive>
                <label>Controversy Session</label>
            </value>
            <value>
                <fullName>Early bird satellite session</fullName>
                <isActive>false</isActive>
                <label>Early bird satellite session</label>
            </value>
            <value>
                <fullName>Grand Round session</fullName>
                <isActive>false</isActive>
                <label>Grand Round session</label>
            </value>
            <value>
                <fullName>Hands-on-course</fullName>
                <isActive>false</isActive>
                <label>Hands-on-course</label>
            </value>
            <value>
                <fullName>Networking</fullName>
                <isActive>false</isActive>
                <label>Networking</label>
            </value>
            <value>
                <fullName>Oral Session</fullName>
                <isActive>false</isActive>
                <label>Oral Session</label>
            </value>
            <value>
                <fullName>Plenary Symposium</fullName>
                <isActive>false</isActive>
                <label>Plenary Symposium</label>
            </value>
            <value>
                <fullName>Poster Session</fullName>
                <isActive>false</isActive>
                <label>Poster Session</label>
            </value>
            <value>
                <fullName>Satellite Symposium</fullName>
                <isActive>false</isActive>
                <label>Satellite Symposium</label>
            </value>
            <value>
                <fullName>Symposium</fullName>
                <isActive>false</isActive>
                <label>Symposium</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Payable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Available_for_Countries__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Countries__c</fullName>
    <label>Available for Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiscountHelperTest.cls
@isTest
public with sharing class DiscountHelperTest {

	@IsTest
	public static void getDiscount() {
		
		Event__c e = new Event__c(Name = 'Event');
		insert e;

		Ticket__c t1 = new Ticket__c(Name = 'Non-Member Ticket', Available_for_Countries__c = 'A;B;C;F');
		Ticket__c t2 = new Ticket__c(Name = 'Any Member Ticket', Available_for_Countries__c = 'A;B;C;F');

		insert new List<Ticket__c> { t1 , t2 } ;

		Session__c s1 = new Session__c( Name = 'Session Extra 1', Type__c = 'Payable', Session_Type__c = 'Special Session', Event_custom__c = e.Id,
				Max_Participants__c = 50, Session_Start__c = Datetime.now(), Session_End__c = Datetime.now().addDays(1));
		
		Session__c s2 = new Session__c( Name = 'Session Extra 2', Type__c = 'Payable', Session_Type__c = 'Special Session', Event_custom__c = e.Id,
			Max_Participants__c = 50, Session_Start__c = Datetime.now(), Session_End__c = Datetime.now().addDays(1));
		
		insert new List<Session__c> { s1, s2 };

		Discount__c disc1 = new Discount__c(
			StartDate__c = Datetime.now() - 2, EndDate__c = Datetime.now() + 2, PromoCode__c = 'PROC50',
			Discount_Type__c = '%', Discount_Amount__c = 50            
		);

		Discount__c disc2 = new Discount__c(
			StartDate__c = Datetime.now() - 2, EndDate__c = Datetime.now() + 2, PromoCode__c = 'SUM10',
			Discount_Type__c = '€', Discount_Amount__c = 10            
		);

		insert new List<Discount__c> { disc1, disc2 };

		List<DiscountItem__c> dIs = new List<DiscountItem__c>();
		
		dIs.add(new DiscountItem__c(Event_custom__c = e.Id, Ticket__c = t1.Id, Discount__c = disc2.Id));
		dIs.add(new DiscountItem__c(Event_custom__c = e.Id, Session__c = s1.Id, Discount__c = disc1.Id));
		
		insert dIs;

		Map<String,Object> generalData = new Map<String,Object>();

		generalData = new Map<String,Object> {
			'eventId' => e.Id,
			'sessions' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => s2.Id, 'amount' => 30 }
			},
			'tickets' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => t2.Id, 'amount' => 30 }
			},
			'discountCode' => 'testCode'
		};  

		Map<String,Object> resMap = DiscountHelper.getDiscount(generalData);

		System.assertEquals('Error', String.valueOf(resMap.get('status')));
		System.assertEquals('Discount code not found. Please try again.', String.valueOf(resMap.get('message')));

		generalData = new Map<String,Object> {
			'eventId' => e.Id,
			'sessions' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => s2.Id, 'amount' => 30 }
			},
			'tickets' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => t2.Id, 'amount' => 30 }
			},
			'discountCode' => 'SUM10'
		};  

		resMap = DiscountHelper.getDiscount(generalData);

		System.assertEquals('Error', String.valueOf(resMap.get('status')));
		System.assertEquals('Invalid discount code.', String.valueOf(resMap.get('message')));
		
		generalData = new Map<String,Object> {
			'eventId' => e.Id,
			'sessions' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => s1.Id, 'amount' => 30 }
			},
			'tickets' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => t1.Id, 'amount' => 30 }
			},
			'discountCode' => 'SUM10'
		};  

		resMap = DiscountHelper.getDiscount(generalData);
		System.assertEquals('Success', String.valueOf(resMap.get('status')));
		System.assertEquals('Discount code applied successfully.', String.valueOf(resMap.get('message')));
		
		Map<String,Object> data = (Map<String,Object>)resMap.get('data');
        List<Object> sessionList = (List<Object>)data.get('sessions');
        System.assertEquals(1, sessionList.size());
        
        Map<String, Object> sessions = (Map<String, Object>)sessionList[0];        
        System.assertEquals(null, sessions.get('discountAmount'));
		
		List<Object> ticketList = (List<Object>)data.get('tickets');
		System.assertEquals(1, ticketList.size());

		Map<String, Object> tickets = (Map<String, Object>)ticketList[0];
        System.assertEquals(10, (Decimal)tickets.get('discountAmount'));
        
		generalData = new Map<String,Object> {
			'eventId' => e.Id,
			'sessions' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => s1.Id, 'amount' => 30 }
			},
			'tickets' => new List<Map<String,Object>> {
				new Map<String,Object> { 'id' => t1.Id, 'amount' => 30 }
			},
			'discountCode' => 'PROC50'
		};  

		resMap = DiscountHelper.getDiscount(generalData);
		System.assertEquals('Success', String.valueOf(resMap.get('status')));
		System.assertEquals('Discount code applied successfully.', String.valueOf(resMap.get('message')));
		
		data = (Map<String,Object>)resMap.get('data');
        ticketList = (List<Object>)data.get('tickets');
		System.assertEquals(1, ticketList.size());

		tickets = (Map<String, Object>)ticketList[0];
		System.assertEquals(null, tickets.get('discountAmount'));
		
		sessionList = (List<Object>)data.get('sessions');
        System.assertEquals(1, sessionList.size());
        
        sessions = (Map<String, Object>)sessionList[0];        
        System.assertEquals(15, (Decimal)sessions.get('discountAmount'));
		
	}
}