force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>D-{0000000000}</displayFormat>
        <label>Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <description>The discount amount in euro or %</description>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>%</fullName>
                <default>true</default>
                <label>%</label>
            </value>
            <value>
                <fullName>€</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/PromoCode__c.field-meta.xml
<CustomField>
    <fullName>PromoCode__c</fullName>
    <label>Promo Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/DiscountItem__c.object-meta.xml
<CustomObject>
    <label>Discount Item</label>
    <nameField>
        <displayFormat>DI-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DiscountItem__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DiscountItem__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Discount Items</relationshipLabel>
    <relationshipName>Discount_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DiscountHelper.cls
public without sharing class DiscountHelper {

	/* 	request
		
		new Map<String,Object> {
			'eventId' => 'a1M0E000002oBvTUAU',
			'session' => new List<Map<String,Object>> {
				new Map<String,Object> {
					'id' =>'a1X0E000000d10HUAQ',
					'amount' => 30
				}
			},
			'tickets' => new List<Map<String,Object>> {
				new Map<String,Object> {
					'id' =>'a1X0E000000d10HUAQ',
					'amount' => 30
				}
			},
			'discountCode' => 'SUM10'
		};  
		
		response
	
		new Map<String,Object> {
			'status' => 'Success',
			'message' => 'Coupon code applied successfully.',
			'data' => new Map<String,Object> {
				'session' => new List<Map<String,Object>> {
					new Map<String,Object> {
						'id' =>'a1X0E000000d10HUAQ',
						'amount' => 30,
						discountAmount => 10,
						discountId => 'discountId'
						
					}
				},
				'tickets' => new List<Map<String,Object>> {
					new Map<String,Object> {
						'id' =>'a1X0E000000d10HUAQ',
						'amount' => 30,
						discountAmount => 10,
						discountId => 'discountId'
					}
				},
				'discount' => discounts[0]
			}
		}; 
		
		*/
	
		private static final Set<String> SESSION_TYPE = new Set<String>{ 'eventDiscount', 'sessionDiscount', 'sessionEventDiscount' };
		private static final Set<String> TICKET_TYPE = new Set<String>{ 'eventDiscount', 'ticketDiscount', 'ticketEventDiscount' };
	
		private static List<SessionWrapper> sessions = new List<SessionWrapper>();
		private static List<TicketWrapper> tickets = new List<TicketWrapper>();
		private static Map<String,Object> discountParam  = new Map<String,Object>();
		private static String eventId;
		private static Decimal totalDiscountAmount;
		
		@AuraEnabled
		public static Map<String,Object> getDiscount (Map<String,Object> generalData) {
			totalDiscountAmount = 0;
			Datetime dateNow = Datetime.now();
			String discountCode = String.valueOf(generalData.get('discountCode'));
			List<Discount__c> discounts = [
				SELECT 
					Id, Name, StartDate__c, EndDate__c, PromoCode__c, Discount_Type__c, Discount_Amount__c,
					(SELECT Id, Event_custom__c, Ticket__c, Session__c FROM Discount_Items__r) 
				FROM Discount__c
				WHERE PromoCode__c =:discountCode AND StartDate__c <=:dateNow AND EndDate__c >=:dateNow
			];
	
			if (discounts.isEmpty() || discounts[0].Discount_Items__r.isEmpty()) {
				return new Map<String,Object> {
					'status' => 'Error',
					'message' => 'Discount code not found. Please try again.',
					'data' => generalData
				};
			}
	
			discountParam = new Map<String,Object> {
				'type' => discounts[0].Discount_Type__c,
				'amount' => discounts[0].Discount_Amount__c
			};
	
			eventId = String.valueOf(generalData.get('eventId'));
			sessions = generalData.containsKey('sessions') ?
				(List<SessionWrapper>)JSON.deserialize(JSON.serialize(generalData.get('sessions')), List<SessionWrapper>.class) : new List<SessionWrapper>();
			tickets = generalData.containsKey('tickets') ?
				(List<TicketWrapper>)JSON.deserialize(JSON.serialize(generalData.get('tickets')), List<TicketWrapper>.class) : new List<TicketWrapper>();
			
			for (DiscountItem__c dI : discounts[0].Discount_Items__r) {
				toApplyDiscount(discounts[0].Id, dI);
			}
	
			if (totalDiscountAmount > 0) {
				return new Map<String,Object> {
					'status' => 'Success',
					'message' => 'Discount code applied successfully.',
					'data' => new Map<String,Object> {
						'sessions' => JSON.deserializeUntyped(JSON.serialize(sessions)),
						'tickets' => JSON.deserializeUntyped(JSON.serialize(tickets)),
						'discount' => discounts[0]
					}
				};
			}
			
			return new Map<String,Object> {
				'status' => 'Error',
				'message' => 'Invalid discount code.',
				'data' => generalData
			};
			
		}
	
		private static void toApplyDiscount (String discountId, DiscountItem__c dI) {
			String typeDiscount = getTypeDiscount(dI);
			if (!String.isBlank(typeDiscount)) {
				if (!sessions.isEmpty() && SESSION_TYPE.contains(typeDiscount)) {
					for (SessionWrapper s : sessions) {
						if ((typeDiscount == 'eventDiscount' && dI.Event_custom__c == eventId) || (typeDiscount == 'sessionDiscount' &&  s.id == dI.Session__c) || 
							(typeDiscount == 'sessionEventDiscount' && dI.Event_custom__c == eventId && s.id == dI.Session__c)) {
							s.discountAmount = calculateDiscount(s.amount);
							totalDiscountAmount += s.discountAmount;
							s.discountId = discountId;
						}
					}
				}
				if (!tickets.isEmpty() && TICKET_TYPE.contains(typeDiscount)) {
					for (TicketWrapper t : tickets) {
						if ((typeDiscount == 'eventDiscount' && dI.Event_custom__c == eventId) || (typeDiscount == 'ticketDiscount' &&  t.id == dI.Ticket__c) || 
							(typeDiscount == 'ticketEventDiscount' && dI.Event_custom__c == eventId && t.id == dI.Ticket__c)) {
							t.discountAmount = calculateDiscount(t.amount);
							totalDiscountAmount += t.discountAmount;
							t.discountId = discountId;
						}
					}
				}
			}
		}
	
		private static Decimal calculateDiscount (Decimal amount) {
			String discountType = String.valueOf(discountParam.get('type'));
			Decimal discountAmount = (Decimal)discountParam.get('amount');
			if (discountType == '%') { return (amount * discountAmount / 100).setScale(2, RoundingMode.CEILING); }
			return discountAmount;
		}
	
		private static String getTypeDiscount (DiscountItem__c oI) {
			Boolean isEvent = !String.isBlank(oI.Event_custom__c);
			Boolean isTicket = !String.isBlank(oI.Ticket__c);
			Boolean isSession = !String.isBlank(oI.Session__c);
			
			return 	isEvent && !isTicket && !isSession ? 'eventDiscount' : 
					isTicket && !isEvent && !isSession ? 'ticketDiscount' :
					isSession && !isEvent && !isTicket ? 'sessionDiscount' :
					isSession && isEvent && !isTicket ? 'sessionEventDiscount' :
					isTicket && isEvent && !isSession  ? 'ticketEventDiscount' : null;
		}
	
		public class TicketWrapper {
			public String id { get; set; }
			public Decimal amount { get; set; }
			public String discountId { get; set; }
			public Decimal discountAmount { get; set; }
		}
		
		public class SessionWrapper {
			public String id { get; set; }
			public Decimal amount { get; set; }
			public String discountId { get; set; }
			public Decimal discountAmount { get; set; }
		}
	
	}