force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If request was created by EAN Staff, here we can see for what contact (community user) it was created</description>
    <label>Community Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Change Requests (Contact)</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Event_Registration_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration Group</label>
    <referenceTo>Event_Registration_Group__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>ADD NEW VALUES TO
changeRequestComponent.js
myRegistrationsComponent.js
ChangeRequestController.cls
MyRegistrationsController.cls</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solo Registration Cancellation</fullName>
            </value>
            <value>
                <fullName>Full Group Registration Cancellation</fullName>
            </value>
            <value>
                <fullName>Group Registration Transfer</fullName>
            </value>
            <value>
                <fullName>Individual Participant Group Registration Cancellation</fullName>
            </value>
            <value>
                <fullName>Solo Registration Transfer</fullName>
                <isActive>false</isActive>
                <label>Solo Registration Transfer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End meeting time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/G2M.recordType-meta.xml
<RecordType>
    <fullName>G2M</fullName>
    <active>true</active>
    <label>G2M</label>
</RecordType>

force-app/main/default/objects/Event_Registration_Group__c/Event_Registration_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Group</label>
    <nameField>
        <label>Event Registration Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registration Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration_Group__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registration Groups</relationshipLabel>
    <relationshipName>Event_Registration_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration_Sub_Group__c/Event_Registration_Sub_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Sub Group</label>
    <nameField>
        <displayFormat>ERSG-{0000000000}</displayFormat>
        <label>Event Registration Sub Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registration Sub Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration_Sub_Group__c/fields/Event_Registration_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Group__c</fullName>
    <label>Event Registration Group</label>
    <referenceTo>Event_Registration_Group__c</referenceTo>
    <relationshipLabel>Event Registration Sub Groups</relationshipLabel>
    <relationshipName>Event_Registration_Sub_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Change_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Change Request</label>
    <referenceTo>Change_Request__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_Registration_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Sub_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to specify group during group registration on congress event</description>
    <label>Event Registration Sub Group</label>
    <referenceTo>Event_Registration_Sub_Group__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Registration_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Sub_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration Sub Group</label>
    <referenceTo>Event_Registration_Sub_Group__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Participant__c/recordTypes/G2M.recordType-meta.xml
<RecordType>
    <fullName>G2M</fullName>
    <active>true</active>
    <label>G2M</label>
</RecordType>

force-app/main/default/classes/MyRegistrationsControllerTest.cls
@isTest
private class MyRegistrationsControllerTest {

	@isTest
	static void myRegistrationsControllerMainTest() {

		Contact testContact1 = new Contact(FirstName = 'testFirst1', LastName = 'testLast1', Email = 'testmail1@nomail.com');
		Contact testContact2 = new Contact(FirstName = 'testFirst2', LastName = 'testLast2', Email = 'testmail2@nomail.com');
		Contact testContact3 = new Contact(FirstName = 'testFirst3', LastName = 'testLast3', Email = 'testmail3@nomail.com');
		Contact testContact4 = new Contact(FirstName = 'testFirst4', LastName = 'testLast4', Email = 'testmail4@nomail.com');
		Contact undefined = new Contact(FirstName = 'Undefined', LastName = 'Participant', Email = '');
		Contact firstGroupLeader = new Contact(FirstName = 'Leader1First', LastName = 'Leader1Last', Email = 'leader1@nomail.com');
		Contact secondGroupLeader = new Contact(FirstName = 'Leader2First', LastName = 'Leader2Last', Email = 'leader2@nomail.com');
		insert new List<Contact>{testContact1, testContact2, testContact3, testContact4, undefined, firstGroupLeader, secondGroupLeader};

		Datetime nowAdd10 = System.now().addDays(10);
		Datetime nowAdd20 = nowAdd10.addDays(10);

		Id congressEventRT = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
		Event__c event1 = new Event__c(Name = 'Event1', RecordTypeId = congressEventRT, Start_Time__c = nowAdd10, End_Time__c = nowAdd20, Status__c = 'Scheduled');
		Event__c event2 = new Event__c(Name = 'Event2', RecordTypeId = congressEventRT, Start_Time__c = nowAdd10, End_Time__c = nowAdd20, Status__c = 'Scheduled');
		Event__c event3 = new Event__c(Name = 'Event3', RecordTypeId = congressEventRT, Start_Time__c = nowAdd10, End_Time__c = nowAdd20, Status__c = 'Scheduled');
		insert new List<Event__c>{event1, event2, event3};

		Event_Registration_Group__c group1 = new Event_Registration_Group__c(Name = 'Group1', Contact__c = firstGroupLeader.Id);
		Event_Registration_Group__c group2 = new Event_Registration_Group__c(Name = 'Group2', Contact__c = secondGroupLeader.Id);
		insert new List<Event_Registration_Group__c>{group1, group2};

		Event_Registration_Sub_Group__c subGroup1_1 = new Event_Registration_Sub_Group__c(Event_Registration_Group__c = group1.Id);
		Event_Registration_Sub_Group__c subGroup1_2 = new Event_Registration_Sub_Group__c(Event_Registration_Group__c = group1.Id);
		Event_Registration_Sub_Group__c subGroup2_1 = new Event_Registration_Sub_Group__c(Event_Registration_Group__c = group2.Id);
		insert new List<Event_Registration_Sub_Group__c>{subGroup1_1, subGroup1_2, subGroup2_1};

		// Id g2mRT = Schema.SObjectType.Participant__c.getRecordTypeInfosByDeveloperName().get('G2M').getRecordTypeId();
		Id congressParticipantRT = Schema.SObjectType.Participant__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
		Participant__c solosolo = new Participant__c(Contact__c = firstGroupLeader.Id, Event_custom__c = event1.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered');
		Participant__c sologroup1_1 = new Participant__c(Contact__c = firstGroupLeader.Id, Event_custom__c = event2.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup1_1.Id);
		Participant__c sologroup2_1 = new Participant__c(Contact__c = firstGroupLeader.Id, Event_custom__c = event3.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup2_1.Id);

		Participant__c group1_1_1 = new Participant__c(Contact__c = testContact1.Id, Event_custom__c = event2.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup1_1.Id);
		Participant__c group1_1_2 = new Participant__c(Contact__c = testContact2.Id, Event_custom__c = event2.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup1_1.Id);
		Participant__c group1_1_3 = new Participant__c(Contact__c = testContact3.Id, Event_custom__c = event2.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup1_1.Id);
		Participant__c group1_1_4 = new Participant__c(Contact__c = testContact4.Id, Event_custom__c = event2.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup1_1.Id);

		Participant__c group1_2_1 = new Participant__c(Contact__c = undefined.Id, Event_custom__c = event2.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup1_2.Id);
		Participant__c group1_2_2 = new Participant__c(Contact__c = undefined.Id, Event_custom__c = event2.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup1_2.Id);

		Participant__c group2_1_1 = new Participant__c(Contact__c = testContact1.Id, Event_custom__c = event3.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup2_1.Id);
		Participant__c group2_1_2 = new Participant__c(Contact__c = testContact2.Id, Event_custom__c = event3.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered', Event_Registration_Sub_Group__c = subGroup2_1.Id);
		insert new List<Participant__c>{solosolo, sologroup1_1, sologroup2_1, group1_1_1, group1_1_2, group1_1_3, group1_1_4, group1_2_1, group1_2_2, group2_1_1, group2_1_2};

		Order__c ordersolo1 = new Order__c(Contact__c = firstGroupLeader.Id, Status__c = 'Paid', Event_custom__c = event1.Id);
		Order__c ordergroup1_1 = new Order__c(Contact__c = firstGroupLeader.Id, Status__c = 'Paid', Event_custom__c = event2.Id, Event_Registration_Sub_Group__c = subGroup1_1.Id);
		Order__c ordergroup1_2 = new Order__c(Contact__c = firstGroupLeader.Id, Status__c = 'Paid', Event_custom__c = event2.Id, Event_Registration_Sub_Group__c = subGroup1_2.Id);
		Order__c ordergroup2_1 = new Order__c(Contact__c = secondGroupLeader.Id, Status__c = 'Paid', Event_custom__c = event3.Id, Event_Registration_Sub_Group__c = subGroup2_1.Id);
		insert new List<Order__c>{ordersolo1, ordergroup1_1, ordergroup1_2, ordergroup2_1};

		Map<String, Object> result = MyRegistrationsController.getMyRegistrations(new Map<String, Object>{'params' => JSON.serialize(new Map<String, String>{'contactRecordId' => '' + firstGroupLeader.Id})});
		System.assertEquals(3, ((List<MyRegistrationsController.EventRegistrationWrap>) result.get('registrationsSolo')).size());
		System.assertEquals(1, ((List<MyRegistrationsController.EventRegistrationWrap>) result.get('registrationsGroup')).size());

		Change_Request__c newCr = new Change_Request__c(Contact__c = firstGroupLeader.Id, Type__c = MyRegistrationsController.CR_TYPE_GROUP_CANCELLATION, Event_Registration_Group__c = group1.Id, Status__c = 'In Progress');
		insert newCr;
		result = MyRegistrationsController.getMyRegistrations(new Map<String, Object>{'params' => JSON.serialize(new Map<String, String>{'contactRecordId' => '' + firstGroupLeader.Id, 'selectedCRType' => MyRegistrationsController.CR_TYPE_SOLO_CANCELLATION})});
		System.assertEquals(MyRegistrationsController.AVAILABLE_MY_REGISTRATIONS_FOR_CR_LABEL, String.valueOf(result.get('myRegistrationsLabel')));
	}
}