force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If request was created by EAN Staff, here we can see for what contact (community user) it was created</description>
    <label>Community Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Change Requests (Contact)</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/TransferToContact__c.field-meta.xml
<CustomField>
    <fullName>TransferToContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transfer to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Change Requests (Transfer to Contact)</relationshipLabel>
    <relationshipName>Change_Requests_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>ADD NEW VALUES TO
changeRequestComponent.js
myRegistrationsComponent.js
ChangeRequestController.cls
MyRegistrationsController.cls</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solo Registration Cancellation</fullName>
            </value>
            <value>
                <fullName>Full Group Registration Cancellation</fullName>
            </value>
            <value>
                <fullName>Group Registration Transfer</fullName>
            </value>
            <value>
                <fullName>Individual Participant Group Registration Cancellation</fullName>
            </value>
            <value>
                <fullName>Solo Registration Transfer</fullName>
                <isActive>false</isActive>
                <label>Solo Registration Transfer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_activity__c/Email_activity__c.object-meta.xml
<CustomObject>
    <label>Email Activity</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Email Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_activity__c/fields/Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Change_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Change Request</label>
    <referenceTo>Change_Request__c</referenceTo>
    <relationshipLabel>Email activities</relationshipLabel>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Email activities</relationshipLabel>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Send_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Email__c</fullName>
    <label>Send To Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/TransferToContact__c.field-meta.xml
<CustomField>
    <fullName>TransferToContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TransferToContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Email activities (TransferToContact)</relationshipLabel>
    <relationshipName>Email_activities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Email__c.field-meta.xml
<CustomField>
    <fullName>Participant_Email__c</fullName>
    <label>Participant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeRequestHelper.cls
public without sharing class ChangeRequestHelper {
	
	public static void sendEmailIfStatusChanged(List<Change_Request__c> changeRequestNew,  Map<Id, Change_Request__c> changeRequestOldMap) {
		List<Change_Request__c> changeRequestsStatusChanged = new List<Change_Request__c>();
		List<Change_Request__c> changeRequestsTransferApproved = new List<Change_Request__c>();
		List<String> contactIds = new List<String>();
		for (Change_Request__c changeRequest : changeRequestNew) {
			if ((changeRequest.Status__c == 'Rejected' || changeRequest.Status__c == 'Approved')
				&& changeRequestOldMap.get(changeRequest.Id).Status__c != changeRequest.Status__c) {
					changeRequestsStatusChanged.add(changeRequest);
					contactIds.add(changeRequest.Contact__c);
			}
			if (changeRequest.Status__c == 'Approved'
			&& changeRequestOldMap.get(changeRequest.Id).Status__c != changeRequest.Status__c
			&& changeRequest.Type__c == 'Solo Registration Transfer'
			|| changeRequest.Type__c == 'Group Registration Transfer') {
				changeRequestsTransferApproved.add(changeRequest);
				contactIds.add(changeRequest.TransferToContact__c);
			}
		}
		Map<Id, Contact> contactsMap = new Map<ID, Contact>([
			SELECT Id, Email FROM Contact WHERE Id IN :contactIds
		]);
		List<String> contactsWithEmptyEmail = new List<String>();
		for (Id contactId : contactsMap.keySet()) {
			if (String.isBlank(contactsMap.get(contactId).Email)) {
				contactsWithEmptyEmail.add(contactsMap.get(contactId).Id);
			}
		}
		Map<String, Participant__c> participantsToContactIdMap = new Map<String, Participant__c>();
		if (contactsWithEmptyEmail.size() > 0) {
			List<Participant__c> participants = [
				SELECT Id, Contact__c, Participant_Email__c FROM Participant__c WHERE Status__c = 'Registered' AND deleted__c = false AND Contact__c IN :contactsWithEmptyEmail
			];
			for (Participant__c participant : participants) {
				participantsToContactIdMap.put(participant.Contact__c, participant);
			}
		}
		List<Email_activity__c> emailActivities = new List<Email_activity__c>();
		for (Change_Request__c changeRequest : changeRequestsStatusChanged) {
			Email_activity__c emailActivity = new Email_activity__c();
			emailActivity.Change_Request__c = changeRequest.Id;
			emailActivity.Contact__c = changeRequest.Contact__c;
			if (String.isNotBlank(contactsMap.get(changeRequest.Contact__c).Email)) {
				emailActivity.Send_To_Email__c = contactsMap.get(changeRequest.Contact__c).Email;
			} else {
				if (participantsToContactIdMap.containsKey(changeRequest.Contact__c)) {
					emailActivity.Send_To_Email__c = participantsToContactIdMap.get(changeRequest.Contact__c).Participant_Email__c;
				}
			}
			emailActivity.Event_custom__c = changeRequest.Event_custom__c;				
			emailActivity.Type__c = changeRequest.Type__c;
			emailActivities.add(emailActivity);
		}
		insert emailActivities;
	}
}