force-app/main/default/objects/Abstract__c/Abstract__c.object-meta.xml
<CustomObject>
    <label>Abstract</label>
    <nameField>
        <displayFormat>A-{YY}-{00000}</displayFormat>
        <label>Abstract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract__c/fields/Abstract_Presenter__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Presenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abstract Presenter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstracts (Abstract Presenter)</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Abstract_Topic__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Topic__c</fullName>
    <label>Abstract Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Author_Details__c.field-meta.xml
<CustomField>
    <fullName>Author_Details__c</fullName>
    <label>Author Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Conclusion__c.field-meta.xml
<CustomField>
    <fullName>Conclusion__c</fullName>
    <label>Conclusion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Congress events.</errorMessage>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Abstracts</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_1__c.field-meta.xml
<CustomField>
    <fullName>Image_1__c</fullName>
    <label>Image 1</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_1_Caption__c.field-meta.xml
<CustomField>
    <fullName>Image_1_Caption__c</fullName>
    <label>Image 1 Caption</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_1_ID__c.field-meta.xml
<CustomField>
    <fullName>Image_1_ID__c</fullName>
    <label>Image 1 ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_1_Location__c.field-meta.xml
<CustomField>
    <fullName>Image_1_Location__c</fullName>
    <label>Image 1 Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Public_Abstract_Sections</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_2__c.field-meta.xml
<CustomField>
    <fullName>Image_2__c</fullName>
    <label>Image 2</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_2_Caption__c.field-meta.xml
<CustomField>
    <fullName>Image_2_Caption__c</fullName>
    <label>Image 2 Caption</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_2_ID__c.field-meta.xml
<CustomField>
    <fullName>Image_2_ID__c</fullName>
    <label>Image 2 ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_2_Location__c.field-meta.xml
<CustomField>
    <fullName>Image_2_Location__c</fullName>
    <label>Image 2 Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Public_Abstract_Sections</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_3__c.field-meta.xml
<CustomField>
    <fullName>Image_3__c</fullName>
    <label>Image 3</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_3_Caption__c.field-meta.xml
<CustomField>
    <fullName>Image_3_Caption__c</fullName>
    <label>Image 3 Caption</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_3_ID__c.field-meta.xml
<CustomField>
    <fullName>Image_3_ID__c</fullName>
    <label>Image 3 ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Image_3_Location__c.field-meta.xml
<CustomField>
    <fullName>Image_3_Location__c</fullName>
    <label>Image 3 Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Public_Abstract_Sections</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Introduction__c.field-meta.xml
<CustomField>
    <fullName>Introduction__c</fullName>
    <label>Introduction</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Methods__c.field-meta.xml
<CustomField>
    <fullName>Methods__c</fullName>
    <label>Methods</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Results__c.field-meta.xml
<CustomField>
    <fullName>Results__c</fullName>
    <label>Results</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a session that is part of the selected event.</errorMessage>
        <filterItems>
            <field>Session__c.Event_custom__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Abstracts</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oral</fullName>
            </value>
            <value>
                <fullName>Poster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.object-meta.xml
<CustomObject>
    <label>Abstract Author</label>
    <nameField>
        <displayFormat>AA-{YY}-{00000}</displayFormat>
        <label>Abstract Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstract Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract_Author__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Abstract Author</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authered Abstracts</relationshipLabel>
    <relationshipName>Authered_Abstracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Payable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AbstractBookController.cls
public with sharing class AbstractBookController {
    public Map<String,Object> abAll { get; set; }
    public Map<String,Object> abInfo { get; set; }
    public Map<String,String> imageMap { get; set; }
    public Map<String,Object> newAbs { get; set; }
    public AbstractBookController() {
        String idPar = ApexPages.currentPage().getParameters().get('id');
        String[] ids = idPar.split('\\,');
        List<Abstract__c> abstracts = new List<Abstract__c>();

        abstracts = [
            SELECT Id, Name, Stage__c, Session__c, Event__c, Author_Details__c, Status__c, Topics__c, 
                Title__c, Body__c,RecordTypeId, RecordType.Name,  Introduction__c, 
                Methods__c, Results__c, Conclusion__c, Type__c,  
                Image_1__c, Image_2__c, Image_3__c, Image_1_Caption__c, Image_2_Caption__c, Image_3_Caption__c,
                Image_1_Location__c, Image_2_Location__c, Image_3_Location__c, Disclosure__c,
                Abstract_Topic__c, Image_1_ID__c, Image_2_ID__c, Image_3_ID__c,Abstract_Presenter__c,
                (SELECT ID, Abstract_Author__c, Abstract_Author__r.Id, Abstract_Author__r.LastName, 
                    Abstract_Author__r.FirstName, Abstract_Author__r.Official_Department_Name__c,
                    Abstract_Author__r.Department_Name__c, Abstract_Author__r.MailingCity, Abstract_Author__r.MailingCountry 
                FROM Abstract_Authors__r)
            FROM Abstract__c 
            WHERE Id IN: ids
        ];
       
        Map<String,Object> abMap = new Map<String,Object>();
        Set<String> imgId = new Set<String>();
        abInfo = new Map<String,Object>();
        newAbs = new Map<String,Object>();
        imageMap = new Map<String,String>();
        
        if (abstracts.size() == 0 ) {
            return;
        }

        for (Abstract__c ab : abstracts) {
            if (!String.isBlank(ab.Abstract_Topic__c)) {
                if (abMap.containsKey(ab.Abstract_Topic__c)) {
                    List<Abstract__c> abOlds = (List<Abstract__c>)abMap.get(ab.Abstract_Topic__c);
                    abOlds.add(ab);
                    abMap.put(ab.Abstract_Topic__c, abOlds);
                } else {
                    abMap.put(ab.Abstract_Topic__c, new List<Abstract__c>{ab});
                }
                if (!String.isBlank(ab.Image_1_ID__c)) {
                    imgId.add(ab.Image_1_ID__c);
                }
                if (!String.isBlank(ab.Image_2_ID__c)) {
                    imgId.add(ab.Image_2_ID__c);
                }
                if (!String.isBlank(ab.Image_3_ID__c)) {
                    imgId.add(ab.Image_3_ID__c);
                }
            }            
        }

        for (String str : abMap.keySet()) {
            Map<String,Integer> depMap = new Map<String,Integer>();
            Integer count = 0;
            List<Abstract__c> abs = (List<Abstract__c>)abMap.get(str);
            for (Abstract__c a : abs) {
                newAbs.put(a.Id ,new Map<String,Object> {
                    'Image_1' => !String.isBlank(a.Image_1_ID__c) ? a.Image_1_ID__c : '',
                    'Image_2' => !String.isBlank(a.Image_2_ID__c) ? a.Image_2_ID__c : '',
                    'Image_3' => !String.isBlank(a.Image_3_ID__c) ? a.Image_3_ID__c : ''
                });
                Boolean isPresenter = false;
                List<Map<String,Object>> authors = new List<Map<String,Object>>();
                List<Map<String,Object>> departments = new List<Map<String,Object>>();
                for (Abstract_Author__c aas : a.Abstract_Authors__r) {
                    if (!String.isBlank(aas.Abstract_Author__r.Department_Name__c)) {
                        if (!depMap.containsKey(aas.Abstract_Author__r.Department_Name__c)) {
                            count++;
                            depMap.put(aas.Abstract_Author__r.Department_Name__c, count);
                            departments.add( new Map<String,Object>{
                                'count' => count,
                                'departmentName' => aas.Abstract_Author__r.Department_Name__c,
                                'city' => aas.Abstract_Author__r.MailingCity,
                                'country' => aas.Abstract_Author__r.MailingCountry                             
                            }); 

                            isPresenter = a.Abstract_Presenter__c ==  aas.Abstract_Author__c;
                            String name = '';
                            if (!String.isBlank(aas.Abstract_Author__r.FirstName)) {
                                name +=aas.Abstract_Author__r.FirstName.substring(0, 1) + '. ';
                            }
                            name +=  aas.Abstract_Author__r.LastName;
                            authors.add(  new Map<String,Object> {
                                'isPresenter' => isPresenter,
                                'count' => count,
                                'name' => name                     
                            }); 
                        }
                        else {
                            Integer cnt = depMap.get(aas.Abstract_Author__r.Department_Name__c);
                            
                            isPresenter = a.Abstract_Presenter__c ==  aas.Abstract_Author__c;
                            
                            authors.add(  new Map<String,Object> {
                                'isPresenter' => isPresenter,
                                'count' => cnt,
                                'name' => aas.Abstract_Author__r.FirstName.substring(0, 1) + '. ' + aas.Abstract_Author__r.LastName                      
                            }); 
                        }
                    }
                }
                abInfo.put(a.Id, new Map<String,Object> {
                    'authors' => authors,
                    'departments' => departments
                });
 
            }

        }
        // str_Autor

        List<ContentVersion> CDs = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId IN: imgId];
       
        this.imageMap.put('', '');
        for (ContentVersion cd : CDs) {
            this.imageMap.put(cd.ContentDocumentId, cd.Id);
        }

        this.abAll = abMap;
    }

}