force-app/main/default/objects/Abstract__c/Abstract__c.object-meta.xml
<CustomObject>
    <label>Abstract</label>
    <nameField>
        <displayFormat>A-{YY}-{00000}</displayFormat>
        <label>Abstract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract__c/fields/Abstract_Presenter__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Presenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abstract Presenter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstracts (Abstract Presenter)</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Abstract_Topic__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Topic__c</fullName>
    <label>Abstract Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Congress events.</errorMessage>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Abstracts</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstract Submissions</relationshipLabel>
    <relationshipName>Abstract_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oral</fullName>
            </value>
            <value>
                <fullName>Poster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.object-meta.xml
<CustomObject>
    <label>Abstract Author</label>
    <nameField>
        <displayFormat>AA-{YY}-{00000}</displayFormat>
        <label>Abstract Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstract Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract_Author__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Abstract Author</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authered Abstracts</relationshipLabel>
    <relationshipName>Authered_Abstracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstract Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/Reviewer__c.object-meta.xml
<CustomObject>
    <label>Reviewer</label>
    <nameField>
        <displayFormat>R{YY}-{00000}</displayFormat>
        <label>Reviewer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reviewer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Events of record type Congress.</errorMessage>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Review_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Review_Capacity__c</fullName>
    <label>Review Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-100</fullName>
            </value>
            <value>
                <fullName>100-200</fullName>
            </value>
            <value>
                <fullName>200-300</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Accpeted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignReviewersControllerTest.cls
@isTest
public with sharing class AssignReviewersControllerTest {
    public AssignReviewersControllerTest() {

    }

    @TestSetup
    static void makeData(){

        List<String> pickListValues = new List<String>();
        List<Schema.PicklistEntry> ple = Reviewer__c.Topics__c.getDescribe().getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
			pickListValues.add(pickListVal.getLabel());
        }
        List<Contact> contacts = new List<Contact>();
        for (Integer i =0; i < pickListValues.size(); i++) {
            Contact cont = new Contact(
                LastName = 'Test_abstract' + i,
                Email = 'testabstract' + i + '@test.ru'
            );
            contacts.add(cont);
        }
        insert contacts;
        System.debug('contacts --> ' + contacts);

        Event__c eventTetst = new Event__c(
            Name = 'Test event'            
        );
        insert eventTetst;
        System.debug('eventTetst --> ' + eventTetst);

        List<Reviewer__c> reviewers = new List<Reviewer__c>();
        Integer loopCounter = 0;
        for (String  pickListValue : pickListValues) {
            Reviewer__c reviewer = new Reviewer__c(
                Review_Capacity__c = '0-100',
                Event__c = eventTetst.Id,
                Contact__c = contacts[loopCounter].Id,
                Status__c = 'Accepted',
                Topics__c = pickListValue
            );
            reviewers.add(reviewer);
            loopCounter = loopCounter + 1;
        }
        insert reviewers;
        System.debug('reviewers --> ' + reviewers);

        Contact contactAbstractSubmitter = new Contact(
                LastName = 'Test_abstract_submitter',
                Email = 'testabstract.submitter@test.ru'
            );
        insert contactAbstractSubmitter;

        Contact contactAbstractPresenter = new Contact(
                LastName = 'Test_abstract_presenter',
                Email = 'testabstract.presenter@test.ru'
            );
        insert contactAbstractPresenter;

        List<String> abstractPickListValues = new List<String>();
        List<Schema.PicklistEntry> abstractPle = Abstract__c.Abstract_Topic__c.getDescribe().getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
			abstractPickListValues.add(pickListVal.getLabel());
        }
        List<Abstract__c> abstracts = new List<Abstract__c>();
        for (String abstractPickListValue : abstractPickListValues) {
            Abstract__c abstractItem = new Abstract__c(
                Event__c = eventTetst.Id,
                Abstract_Topic__c = abstractPickListValue,
                Stage__c = 'Submitted',
                Status__c = 'Pending',
                Type__c = 'Poster',
                Submitter__c = contactAbstractSubmitter.Id,
                Abstract_Presenter__c = contactAbstractPresenter.Id
            );
            abstracts.add(abstractItem);
        }
        insert abstracts;
        System.debug('abstracts --> ' + abstracts);

        Contact contactAbstractAuthor = new Contact(
                LastName = 'Test_abstract_author',
                Email = 'testabstract.author@test.ru'
            );
        insert contactAbstractAuthor;
        System.debug('contactAbstractAuthor --> ' + contactAbstractAuthor);

        List<Abstract_Author__c> abstractAuthors = new List<Abstract_Author__c>();
        for (Abstract__c abstractItem : abstracts) {
            Abstract_Author__c abstractAuthor = new Abstract_Author__c(
                Abstract__c = abstractItem.Id,
                Abstract_Author__c = contactAbstractAuthor.Id
            );
            abstractAuthors.add(abstractAuthor);
        }
        insert abstractAuthors;
        System.debug('abstractAuthors --> ' + abstractAuthors);
    }

    @isTest
    static void getPickListValuesTest(){
        String objectApiName = 'Contact';
        String fieldApiName = 'Salutation';
        String fieldApiNameWhithoutPicklist = 'LastName';
        List<String> fieldApiNames = new List<String>();
        fieldApiNames.add(fieldApiName);
        fieldApiNames.add(fieldApiNameWhithoutPicklist);
        Map<String, List<String>> objectNameToObjectFieldNamesMap = new Map<String, List<String>>();
        objectNameToObjectFieldNamesMap.put(objectApiName, fieldApiNames);
        Map<String, Map<String, List<String>>> result = AssignReviewersController.getPickListValues(objectNameToObjectFieldNamesMap);
        System.assert(result.containsKey(objectApiName));
        System.assert(result.get(objectApiName).containsKey(fieldApiName));
        System.assert(result.get(objectApiName).containsKey(fieldApiNameWhithoutPicklist));
        System.assert(result.get(objectApiName).get(fieldApiName).size() > 0);
        System.assert(result.get(objectApiName).get(fieldApiNameWhithoutPicklist).size() == 0);
    }
    @isTest
    static void getAbstractsTest(){
        String abstractTopic = '';
        String abstractType = '';
        List<Abstract__c> abstractsNotfiltered = AssignReviewersController.getAbstracts(abstractTopic, abstractType);
        System.assert(abstractsNotfiltered.size() > 0);
        abstractTopic = Abstract__c.Abstract_Topic__c.getDescribe().getPicklistValues()[0].getLabel();
        List<Abstract__c> abstractsFiltered = AssignReviewersController.getAbstracts(abstractTopic, abstractType);
        System.assert(abstractsFiltered.size() > 0);
        System.assert(abstractsNotfiltered.size() > abstractsFiltered.size());
    }

    @isTest
    static void getReviewersTest(){
        List<Abstract__c> abstracts = [
            SELECT Id
            FROM Abstract__c
            WHERE Stage__c = 'Submitted'
        ];
        System.debug('getReviewersTest abstracts --> ' + abstracts);
        List<Reviewer__c> reviewers = new List<Reviewer__c>();
        if (abstracts.size() > 0) {
            reviewers = AssignReviewersController.getReviewers(abstracts[0].Id);
        }
        System.assert(reviewers.size() > 0);
    }

    @isTest
    static void getAuthorsDataTest(){
        List<Abstract__c> abstracts = [
            SELECT Id
            FROM Abstract__c
            WHERE Stage__c = 'Submitted'
        ];
        List<Contact> contacts = [
            SELECT Id, Email
            FROM Contact
            WHERE LastName = 'Test_abstract_author'
        ];
        List<Abstract_Author__c> authors = new List<Abstract_Author__c>();
        if (abstracts.size() > 0) {
            authors = AssignReviewersController.getAuthorsData(abstracts[0].Id, contacts[0].Id, contacts[0].Email);
        }
        System.assert(authors.size() > 0);
    }
}