force-app/main/default/objects/Abstract__c/Abstract__c.object-meta.xml
<CustomObject>
    <label>Abstract</label>
    <nameField>
        <displayFormat>A-{YY}-{00000}</displayFormat>
        <label>Abstract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract__c/fields/Abstract_Topic__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Topic__c</fullName>
    <label>Abstract Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Congress events.</errorMessage>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Abstracts</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oral</fullName>
            </value>
            <value>
                <fullName>Poster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.object-meta.xml
<CustomObject>
    <label>Abstract Author</label>
    <nameField>
        <displayFormat>AA-{YY}-{00000}</displayFormat>
        <label>Abstract Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstract Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract_Author__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstract Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract_Review__c/Abstract_Review__c.object-meta.xml
<CustomObject>
    <label>Abstract Review</label>
    <nameField>
        <displayFormat>AR{YY}-{000000}</displayFormat>
        <label>Abstract Review</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstract Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract_Review__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Public Abstract Submissions can be assigned for review.</errorMessage>
        <filterItems>
            <field>Abstract__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Public Submission</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Abstract Reviews</relationshipLabel>
    <relationshipName>Abstract_Reviews</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Abstract_Review__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <label>Reviewer</label>
    <referenceTo>Reviewer__c</referenceTo>
    <relationshipLabel>Abstract Reviews</relationshipLabel>
    <relationshipName>Abstract_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Abstract_Review__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Rated</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Abstract_Submission_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Submission_Deadline__c</fullName>
    <label>Abstract Submission Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Late_Breaking_Submission_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Late_Breaking_Submission_Deadline__c</fullName>
    <label>Late Breaking Submission Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Number_of_Reviewers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Reviewers__c</fullName>
    <inlineHelpText>Public abstracts will be reviewed by how many reviewers?</inlineHelpText>
    <label>Number of Reviewers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Number_of_Reviewers_Late_Breaking__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Reviewers_Late_Breaking__c</fullName>
    <inlineHelpText>Late breaking abstracts will be reviewed by how many reviewers?</inlineHelpText>
    <label>Number of Reviewers (Late Breaking)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lecture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abstract</label>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/Reviewer__c.object-meta.xml
<CustomObject>
    <label>Reviewer</label>
    <nameField>
        <displayFormat>R{YY}-{00000}</displayFormat>
        <label>Reviewer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reviewer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Events of record type Congress.</errorMessage>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Review_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Review_Capacity__c</fullName>
    <label>Review Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-100</fullName>
            </value>
            <value>
                <fullName>100-200</fullName>
            </value>
            <value>
                <fullName>200-300</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Accpeted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AbstractBookControllerTest.cls
@isTest
public with sharing class AbstractBookControllerTest {

    @TestSetup
    static void makeData(){

        List<String> pickListValues = new List<String>();
        List<Schema.PicklistEntry> ple = Reviewer__c.Topics__c.getDescribe().getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
			pickListValues.add(pickListVal.getLabel());
        }
        List<Contact> contacts = new List<Contact>();
        for (Integer i =0; i < pickListValues.size(); i++) {
            Contact cont = new Contact(
                LastName = 'Test_abstract' + i,
                Email = 'testabstract' + i + '@test.ru'
            );
            contacts.add(cont);
        }
        insert contacts;

        Event__c eventTest = new Event__c(
            Name = 'Test event',
            Abstract_Submission_Deadline__c = Datetime.now().addDays(5),
            Late_Breaking_Submission_Deadline__c = Datetime.now().addDays(10),
            Number_of_Reviewers__c = 2,
            Number_of_Reviewers_Late_Breaking__c = 0
        );
        insert eventTest;

        List<Reviewer__c> reviewers = new List<Reviewer__c>();
        Integer loopCounter = 0;
        for (String  pickListValue : pickListValues) {
            Reviewer__c reviewer = new Reviewer__c(
                Review_Capacity__c = '0-100',
                Event__c = eventTest.Id,
                Contact__c = contacts[loopCounter].Id,
                Status__c = 'Accepted',
                Topics__c = pickListValue
            );
            reviewers.add(reviewer);
            loopCounter = loopCounter + 1;
        }
        insert reviewers;

        Contact contactAbstractSubmitter = new Contact(
                LastName = 'Test_abstract_submitter',
                Email = 'testabstract.submitter@test.ru'
            );
        insert contactAbstractSubmitter;

        Contact contactAbstractPresenter = new Contact(
                LastName = 'Test_abstract_presenter',
                Email = 'testabstract.presenter@test.ru'
            );
        insert contactAbstractPresenter;

        List<String> abstractPickListValues = new List<String>();
        List<Schema.PicklistEntry> abstractPle = Abstract__c.Abstract_Topic__c.getDescribe().getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
			abstractPickListValues.add(pickListVal.getLabel());
        }
        List<Abstract__c> abstracts = new List<Abstract__c>();
        for (String abstractPickListValue : abstractPickListValues) {
            Abstract__c abstractItem = new Abstract__c(
                Event__c = eventTest.Id,
                Abstract_Topic__c = abstractPickListValue,
                Stage__c = 'Submitted',
                Status__c = 'Pending',
                Type__c = 'Poster',
                Submitter__c = contactAbstractSubmitter.Id,
                Abstract_Presenter__c = contactAbstractPresenter.Id
            );
            abstracts.add(abstractItem);
        }
        insert abstracts;

        Contact contactAbstractAuthor = new Contact(
                FirstName = 'FirstName',
            	LastName = 'Test_abstract_author',
                Email = 'testabstract.author@test.ru',
            	Department_Name__c = 'qwe'
            );
        Contact contactAbstractAuthor1 = new Contact(
                FirstName = 'FirstName',
            	LastName = 'Test_abstract_author',
                Email = 'testabstract.author@test.ru',
            	Department_Name__c = 'qwe'
            );
        Contact contactAbstractAuthor2 = new Contact(
                FirstName = 'FirstName',
            	LastName = 'Test_abstract_author',
                Email = 'testabstract.author@test.ru'
        );
        insert new List<Contact> { contactAbstractAuthor, contactAbstractAuthor1, contactAbstractAuthor2 };

        List<Abstract_Author__c> abstractAuthors = new List<Abstract_Author__c>();
        for (Abstract__c abstractItem : abstracts) {
            abstractAuthors.add(new Abstract_Author__c(
                Abstract__c = abstractItem.Id,
                Abstract_Author__c = contactAbstractAuthor.Id
            ));
            abstractAuthors.add(new Abstract_Author__c(
                Abstract__c = abstractItem.Id,
                Abstract_Author__c = contactAbstractAuthor1.Id
            ));
            abstractAuthors.add(new Abstract_Author__c(
                Abstract__c = abstractItem.Id,
                Abstract_Author__c = contactAbstractAuthor2.Id
            ));
        }
        insert abstractAuthors;
        
        insert new Abstract_Review__c( Reviewer__c = reviewers[0].Id , Abstract__c= abstracts[0].Id, Stage__c='Assigned');
        
        List<Session__c> extraSessions = new List<Session__c>();

        extraSessions.add(new Session__c(Name = 'Session Extra 1', Type__c = 'Payable', Session_Type__c = 'Special Session',
        	Max_Participants__c = 50, Event_custom__c = eventTest.Id, Session_Start__c = Datetime.now(),
            Session_End__c = Datetime.now().addDays(1)));
        
        insert extraSessions;
         
        Lecture__c lecture = new Lecture__c(Event_custom__c = eventTest.Id, Session__c = extraSessions[0].Id, Abstract__c = abstracts[0].Id);
        insert lecture;
        
    }
    @isTest 
    static void testGetData() {
        PageReference pageRef = Page.AbstractBooks;
        pageRef.getParameters().put('type','AbstractStaff');
        Test.setCurrentPage(pageRef);
        
        AbstractBookController controller = new AbstractBookController();
        System.assertEquals(1, controller.abAll.size());
        
    }
}