force-app/main/default/objects/Abstract__c/Abstract__c.object-meta.xml
<CustomObject>
    <label>Abstract</label>
    <nameField>
        <displayFormat>A-{YY}-{00000}</displayFormat>
        <label>Abstract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract__c/fields/Abstract_Presenter__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Presenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abstract Presenter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstracts (Abstract Presenter)</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.object-meta.xml
<CustomObject>
    <label>Abstract Author</label>
    <nameField>
        <displayFormat>AA-{YY}-{00000}</displayFormat>
        <label>Abstract Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstract Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract_Author__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Abstract Author</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authered Abstracts</relationshipLabel>
    <relationshipName>Authered_Abstracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomLookUpAuthorControllerTest.cls
@isTest
public with sharing class CustomLookUpAuthorControllerTest {
    
    @testSetup static void setup() {

        List<Contact> contactList = new List<Contact>();
        List<Abstract__c> abstractList = new List<Abstract__c>();
        List<Abstract_Author__c> junctions = new List<Abstract_Author__c>();

        for(integer i = 0; i < 10; i++){
            Contact c = new Contact(
                FirstName = 'Test_', LastName = '' + i, Email = '' + i + 'test@test.com', Department_Name__c = 'department_' + i, deleted1__c = false
            );
            contactList.add(c);
        }

        insert contactList; 

        for(Integer i = 0; i < 3; i++){
            Abstract__c abstractItem = new Abstract__c(
                Abstract_Presenter__c = contactList.get(0).Id 
            );

            abstractList.add(abstractItem);
        }      

        insert abstractList;

        for(Integer i = 0; i < 3; i++){
            Abstract_Author__c junction = new Abstract_Author__c(
                Abstract_Author__c = contactList.get(0).Id,
                Abstract__c = abstractList.get(0).Id 
            );

            junctions.add(junction);
        } 

        insert junctions;
    }

    @isTest
    public static void fetchLookUpValuesTest(){
        List<Contact> contacts = CustomLookUpAuthorController.fetchLookUpValues('test', new String[]{'ThisIsNotIdOnContact'});
        System.assertEquals(contacts.size(), 5);

        contacts = CustomLookUpAuthorController.fetchLookUpValues('', new String[]{'ThisIsNotIdOnContact'});
        System.assertEquals(contacts.size(), 5);
    }

    @isTest
    public static void createContactTest(){
        String FirstName = 'Mike';
        String LastName = 'Hottorn';
        String EmailString = 'hottorn@f1.com';
        String Department = 'F1';
        String City = 'Minsk';
        String Country = 'Belarus';

        List<Contact> con = [Select Id FROM Contact WHERE FirstName =: firstName];
        System.assertEquals(con.size(), 0);

        CustomLookUpAuthorController.createContact(FirstName, LastName, EmailString, Department, City, Country);

        con = [Select Id FROM Contact WHERE FirstName =: firstName];
        System.assertEquals(con.size(), 1);
    }

    @isTest
    public static void getContactTest(){
        Abstract__c abstractItem = [SELECT Id FROM Abstract__c].get(0);

        List<Contact> con = CustomLookUpAuthorController.getContacts(abstractItem.Id);

        System.assertNotEquals(con.size(), 0);
    }

    @isTest
    public static void getMailingCountriesTest(){
        List<String> countries = CustomLookUpAuthorController.getMailingCountries();
        System.assertNotEquals(countries.size(), 0);
    }
}