force-app/main/default/objects/Abstract__c/Abstract__c.object-meta.xml
<CustomObject>
    <label>Abstract</label>
    <nameField>
        <displayFormat>A-{YY}-{00000}</displayFormat>
        <label>Abstract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract__c/fields/Abstract_Topic__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Topic__c</fullName>
    <label>Abstract Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oral</fullName>
            </value>
            <value>
                <fullName>Poster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignRewiewersController.cls
public with sharing class AssignRewiewersController {

    @AuraEnabled
    public static List<String> getTopics(){
        List<String> topics = new List<String>();

        Schema.sObjectType objType = Abstract__c.getSObjectType();
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        List<Schema.PicklistEntry> values = fieldMap.get('Abstract_Topic__c').getDescribe().getPickListValues();

        for (Schema.PicklistEntry v : values){
            topics.add(v.getLabel());
        }

        return topics;
    }
    
    @AuraEnabled
    public static List<Abstract__c> getAbstracts(String abstractTopic){
        List<Abstract__c> abstracts = new List<Abstract__c>();

        if(abstractTopic.length() == 0){
            abstracts = [
                SELECT Id, Name, Title__c, Abstract_Topic__c, Type__c, Stage__c, Status__c
                FROM Abstract__c 
                WHERE 
                    RecordType.Name = 'Public Submission'
                    AND 
                    Stage__c = 'Submitted'
                    AND 
                    Status__c = 'Pending'
            ];
        }else{
            abstracts = [
                SELECT Id, Name, Title__c, Abstract_Topic__c, Type__c, Stage__c, Status__c
                FROM Abstract__c 
                WHERE 
                    RecordType.Name = 'Public Submission'
                    AND 
                    Stage__c = 'Submitted'
                    AND 
                    Status__c = 'Pending' 
                    AND 
                    Abstract_Topic__c =: abstractTopic
            ];
        }
        
        return abstracts;
    }
}