force-app/main/default/objects/Abstract__c/Abstract__c.object-meta.xml
<CustomObject>
    <label>Abstract</label>
    <nameField>
        <displayFormat>A-{YY}-{00000}</displayFormat>
        <label>Abstract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract__c/fields/Abstract_Presenter__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Presenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abstract Presenter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstracts (Abstract Presenter)</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Abstract_Topic__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Topic__c</fullName>
    <label>Abstract Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Congress events.</errorMessage>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Abstracts</relationshipLabel>
    <relationshipName>Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstract Submissions</relationshipLabel>
    <relationshipName>Abstract_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oral</fullName>
            </value>
            <value>
                <fullName>Poster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.object-meta.xml
<CustomObject>
    <label>Abstract Author</label>
    <nameField>
        <displayFormat>AA-{YY}-{00000}</displayFormat>
        <label>Abstract Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstract Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract_Author__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/Abstract_Author__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Abstract Author</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authered Abstracts</relationshipLabel>
    <relationshipName>Authered_Abstracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract_Author__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abstract Authors</relationshipLabel>
    <relationshipName>Abstract_Authors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abstract_Review__c/Abstract_Review__c.object-meta.xml
<CustomObject>
    <label>Abstract Review</label>
    <nameField>
        <displayFormat>AR{YY}-{000000}</displayFormat>
        <label>Abstract Review</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abstract Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Abstract_Review__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Public Abstract Submissions can be assigned for review.</errorMessage>
        <filterItems>
            <field>Abstract__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Public Submission</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Abstract__c</referenceTo>
    <relationshipLabel>Abstract Reviews</relationshipLabel>
    <relationshipName>Abstract_Reviews</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Abstract_Review__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <label>Reviewer</label>
    <referenceTo>Reviewer__c</referenceTo>
    <relationshipLabel>Abstract Reviews</relationshipLabel>
    <relationshipName>Abstract_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Abstract_Review__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Rated</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/Reviewer__c.object-meta.xml
<CustomObject>
    <label>Reviewer</label>
    <nameField>
        <displayFormat>R{YY}-{00000}</displayFormat>
        <label>Reviewer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reviewer__c/fields/Assigned_Abstracts__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Abstracts__c</fullName>
    <label>Assigned Abstracts</label>
    <summaryForeignKey>Abstract_Review__c.Reviewer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Events of record type Congress.</errorMessage>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Remaining_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Capacity__c</fullName>
    <formula>Capacity__c -  Assigned_Abstracts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Accpeted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topics_of_interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignReviewersController.cls
public with sharing class AssignReviewersController {

    // @AuraEnabled
    // public static List<String> getTopics(){
    //     List<String> topics = new List<String>();

    //     Schema.sObjectType objType = Abstract__c.getSObjectType();
    //     Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
    //     Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
    //     List<Schema.PicklistEntry> values = fieldMap.get('Abstract_Topic__c').getDescribe().getPickListValues();

    //     for (Schema.PicklistEntry v : values){
    //         topics.add(v.getLabel());
    //     }

    //     return topics;
    // }
    
    @AuraEnabled
    public static Map<String, Map<String, List<String>>> getPickListValues(Map<String, List<String>> objectApiNameTofieldApiNameMap){
        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();
        Map<String, Map<String, List<String>>> resultsMap= new Map<String, Map<String, List<String>>>();
        for (String objectApiName : objectApiNameTofieldApiNameMap.keySet()) {
            if (globalDescribeMap.containsKey(objectApiName)) {
                Map<String, List<String>> pickListValuesMap= new Map<String, List<String>>();
                Map<String, Schema.SObjectField> objectFieldsMap = globalDescribeMap.get(objectApiName).getDescribe().fields.getMap();
                for (String fieldApiName : objectApiNameTofieldApiNameMap.get(objectApiName)) {
                    if (objectFieldsMap.containsKey(fieldApiName.toLowerCase())) {
                        List<String> pickListValues = new List<String>();
                        List<Schema.PicklistEntry> fieldResults = objectFieldsMap.get(fieldApiName.toLowerCase()).getDescribe().getPicklistValues();
                        for( Schema.PicklistEntry pickListValue : fieldResults){
                            pickListValues.add(pickListValue.getLabel());
                        }
                        pickListValuesMap.put(fieldApiName, pickListValues);
                    }
                }
                resultsMap.put(objectApiName, pickListValuesMap);
            }
        }
        return resultsMap;
    }

    @AuraEnabled
    public static List<Abstract__c> getAbstracts(String abstractTopic, String abstractType){
        List<Abstract__c> abstracts = new List<Abstract__c>();

        if(abstractTopic.length() == 0
            && abstractType.length() == 0){
            abstracts = [
                SELECT Id, Name, Title__c, Abstract_Topic__c, Type__c, Stage__c, Status__c, Event__c, Abstract_Presenter__c, Abstract_Presenter__r.Email,  (SELECT Id FROM Abstract_Reviews__r)
                FROM Abstract__c 
                WHERE 
                    RecordType.Name = 'Public Submission'
                    AND 
                    Stage__c = 'Submitted'
                    AND 
                    Status__c = 'Pending'
            ];
        }else{
            String recordType = 'Public Submission';
            String stage = 'Submitted';
            String status = 'Pending';
            String query = 'SELECT Id, Name, Title__c, Abstract_Topic__c, Type__c, Stage__c, Status__c, Event__c, Abstract_Presenter__c, Abstract_Presenter__r.Email,  (SELECT Id FROM Abstract_Reviews__r) FROM Abstract__c WHERE RecordType.Name = :recordType AND Stage__c = :stage AND Status__c = :status';
            if (String.isNotBlank(abstractTopic)) {
                query = query + ' AND Abstract_Topic__c = :abstractTopic';
            }
            if (String.isNotBlank(abstractType)) {
                query = query + ' AND Type__c = :abstractType';
            }
            abstracts = Database.query(query);
        }
        
        return abstracts;
    }

    @AuraEnabled
    public static List<Reviewer__c> getReviewers(Id abstractId){
        List<Reviewer__c> reviewers = new List<Reviewer__c>();

        Abstract__c abstractItem = [ 
            SELECT Id, Name, Title__c, Abstract_Topic__c, Type__c, Stage__c, Status__c, Event__c, Abstract_Presenter__c,
                    Submitter__c,
            (
                    SELECT Id, Abstract_Author__c FROM Abstract_Authors__r
            )
            FROM Abstract__c WHERE Id =: abstractId
        ].get(0);

        Set<Id> excludedReviewerContacts = new Set<Id>();

        //Reviewer.Contact != Abstract.AbstractPresenter
        excludedReviewerContacts.add(abstractItem.Abstract_Presenter__c);
        //submitter cannot be a reviewer
        excludedReviewerContacts.add(abstractItem.Submitter__c);
        //Reviewer.Contact != Check all Abstract Authors.Contact for Abstract
        for(Abstract_Author__c author : abstractItem.Abstract_Authors__r){
            excludedReviewerContacts.add(author.Abstract_Author__c);
        }

        System.debug('excludedReviewerContacts: ' + excludedReviewerContacts);

        String queryString = 
            'SELECT Id, Name, Remaining_Capacity__c, Assigned_Abstracts__c, Event__c, Topics__c, Contact__c, Contact__r.Email, Contact__r.Name ' + 
            'FROM Reviewer__c ' + 
            'WHERE ' +
                'Id NOT IN (SELECT Reviewer__c FROM Abstract_Review__c WHERE Abstract__c = :abstractId) ' +
                'AND Remaining_Capacity__c > 0 ' +
                'AND Event__c = \'' + abstractItem.Event__c + '\' ' +
                'AND Contact__c NOT IN :excludedReviewerContacts ' +
                'AND Status__c = \'Accepted\' ';

        System.debug('abstractItem.Abstract_Topic__c ' + abstractItem.Abstract_Topic__c);
        if(abstractItem.Abstract_Topic__c != null){
            String[] topicsArray = abstractItem.Abstract_Topic__c.split(';');
            queryString += 'AND Topics__c INCLUDES(';

            for(String item : topicsArray){
                queryString += '\'' + item + '\',';
            }
            queryString = queryString.removeEnd(',') +')';
        }else{
            return reviewers;
        }
        System.debug('queryString ' + queryString);
        reviewers = (List<Reviewer__c>)Database.query(queryString);
        return reviewers;
    }

    @AuraEnabled
    public static List<Abstract_Author__c> getAuthorsData(String abstractId, String reviewerContactId, String reviewerContactEmail){
        List<Abstract_Author__c> authorsData = new List<Abstract_Author__c>();

        authorsData = [
            SELECT Id, Abstract_Author__c, Abstract_Author__r.Email
            FROM Abstract_Author__c
            WHERE
                Abstract__c =: abstractId
                AND (
                    Abstract_Author__c =: reviewerContactId 
                    OR 
                    Abstract_Author__r.Email =: reviewerContactEmail
                )
        ];

        return authorsData;
    }

    @AuraEnabled
    public static Map<String,Object> setAbstractRev(Map<String,String> generalData){
        System.debug('setAbstractRev generalData ' + generalData);
        try {
            List<Abstract_Review__c> ars = new List<Abstract_Review__c>();
            for (String key : generalData.keySet()) {
                ars.add(
                    new Abstract_Review__c(
                        Abstract__c = generalData.get(key),
                        Reviewer__c = key,
                        Stage__c = 'Assigned'
                    )
                );
            }
            
            insert ars;

            return new Map<String,Object> {
                'status' => 'Success',
                'message' => 'Reviewers appointed'
            };

        } catch (Exception e) {
            return new Map<String,Object> {
                'status' => 'Error',
                'message' => e.getMessage()
            };
        }
    }
}