force-app/main/default/objects/Email_activity__c/Email_activity__c.object-meta.xml
<CustomObject>
    <label>Email Activity</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Email Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Email activities</relationshipLabel>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_Registration_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration Group</label>
    <referenceTo>Event_Registration_Group__c</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End meeting time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration_Group__c/Event_Registration_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Group</label>
    <nameField>
        <label>Event Registration Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registration Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration_Group__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registration Groups</relationshipLabel>
    <relationshipName>Event_Registration_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration_Sub_Group__c/Event_Registration_Sub_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Sub Group</label>
    <nameField>
        <displayFormat>ERSG-{0000000000}</displayFormat>
        <label>Event Registration Sub Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registration Sub Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration_Sub_Group__c/fields/Event_Registration_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Group__c</fullName>
    <label>Event Registration Group</label>
    <referenceTo>Event_Registration_Group__c</referenceTo>
    <relationshipLabel>Event Registration Sub Groups</relationshipLabel>
    <relationshipName>Event_Registration_Sub_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration_Sub_Group__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Locked for adding new participants or change existing participants</description>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Registration_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Sub_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration Sub Group</label>
    <referenceTo>Event_Registration_Sub_Group__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EAN_EmailBatchTest.cls
@isTest
public with sharing class EAN_EmailBatchTest {
    public EAN_EmailBatchTest() {

    }

    @TestSetup
    static void setup(){
        List<Contact> contacts = new List<Contact>();
        contacts.add(new Contact(
             LastName = 'Participant',
             FirstName = 'Undefined'
         ));
        contacts.add(new Contact(
             LastName = 'Group Leader Test',
             Email = 'gr.leader@test.com'
         ));
         for (Integer i=1; i <= 10; i++) {
             contacts.add(new Contact(
             LastName = 'Contact' + i,
             FirstName = 'Test'
         ));
         }
        insert contacts;
        Event_Registration_Group__c regGroup;
        Event_Registration_Sub_Group__c regSubGroup;
        for (Contact contact : contacts) {
            if (contact.LastName == 'Group Leader Test') {
                regGroup = new Event_Registration_Group__c();
                regGroup.Contact__c = contact.Id;
                insert regGroup;
                regSubGroup = new Event_Registration_Sub_Group__c();
                regSubGroup.Event_Registration_Group__c = regGroup.Id;
                // regSubGroup.Is_Locked__c = false;
                insert regSubGroup;
            }
        }
        Event__c event = new Event__c();
        event.Start_Time__c = Datetime.newInstance(Date.today().addDays(40), Time.newInstance(0, 0, 0, 0));
        event.End_Time__c = Datetime.newInstance(Date.today().addDays(50), Time.newInstance(0, 0, 0, 0));
        event.Name = 'Test event';
        insert event;
        List<Participant__c> participants = new List<Participant__c>();
        for (Contact contact : contacts) {
            Participant__c participant = new Participant__c();
            participant.Contact__c = contact.Id;
            participant.Event_Registration_Sub_Group__c = regSubGroup.Id;
            participant.Status__c = 'Registered';
            participant.Event_custom__c = event.Id;
            participants.add(participant);
        }
        insert participants;
    }

    @isTest
    static void emailBatchTest(){
        Test.startTest();
        Id batchInstanceId = Database.executeBatch(new EAN_EmailBatch());
        Test.stopTest();
        AsyncApexJob aaj = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors 
                    FROM AsyncApexJob WHERE ID =: batchInstanceId ];
        System.assertEquals('Completed', aaj.Status);
        System.assertEquals(0, aaj.NumberOfErrors);
        List<Email_Activity__c> emailActivities = [
            SELECT Type__c, Event_Custom__r.Name
            FROM Email_Activity__c
        ];
        System.assert(emailActivities.size() > 0);
        for (Email_Activity__c emailActivity : emailActivities) {
            System.assert(emailActivity.Type__c == 'Reminder GR add participants');
            System.assert(emailActivity.Event_Custom__r.Name == 'Test event');
        }
    }
}