force-app/main/default/objects/Email_activity__c/Email_activity__c.object-meta.xml
<CustomObject>
    <label>Email Activity</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Email Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Email activities</relationshipLabel>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Email Activities</relationshipLabel>
    <relationshipName>Email_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Send_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Email__c</fullName>
    <label>Send To Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderReminderBatch.cls
public without sharing class OrderReminderBatch implements Database.Batchable<Order__c>, Database.Stateful, Database.AllowsCallouts {
    public OrderReminderBatch() {

    }

    public List<Order__c> start(Database.BatchableContext bc) {
        Datetime currentDatetime = Datetime.newInstance(System.now().date(), Time.newInstance(0, 0, 0, 0));
        List<Order__c> remindOrders = [
            SELECT Id, Event_custom__c, Contact__r.Email, CreatedDate, Status__c
            FROM Order__c
            WHERE Status__c = 'Opened'
            AND Type__c = 'Event registration'
            AND CreatedDate >= :currentDatetime.addDays(-7)
            AND CreatedDate <= :currentDatetime.addDays(-6)
        ];
        List<Order__c> overdueOrders = [
            SELECT Id, Event_custom__c, Contact__r.Email, CreatedDate, Status__c
            FROM Order__c
            WHERE Status__c = 'Opened'
            AND Type__c = 'Event registration'
            AND CreatedDate >= :currentDatetime.addDays(-14)
            AND CreatedDate <= :currentDatetime.addDays(-13)
        ];
        List<Order__c> orders = new List<Order__c>();
        orders.addAll(remindOrders);
        orders.addAll(overdueOrders);
        return orders;
    }

    public void execute(Database.BatchableContext BC, List<Order__c> orders) {
        List<Email_Activity__c> emailActivities = new List<Email_Activity__c>();
        List<Order__c> updateOrders = new List<Order__c>();
        for (Order__c order : orders) {
            if (order.CreatedDate.date().addDays(14) == Date.today()) {
                order.Status__c = 'overdue';
                updateOrders.add(order);
            } else if (order.CreatedDate.date().addDays(7) == Date.today()) {
                Email_Activity__c emailActivity = new Email_Activity__c(
                Contact__c = order.Contact__c,
                Event_Custom__c = order.Event_custom__c,
                Order__c = order.Id,
                Send_To_Email__c = order.Contact__r.Email,
                Type__c = 'Open order reminder'
                );
                emailActivities.add(emailActivity);
            }
        }
        if (updateOrders.size() > 0) {
            update updateOrders;
        }
        if (emailActivities.size() > 0) {
            insert emailActivities;
        }
         
    }

    public void finish(Database.BatchableContext BC) {
        String jobName = 'Order Reminder';
        List<CronTrigger> orderReminderJobs = [SELECT Id
                                FROM CronTrigger
                                WHERE CronJobDetail.Name = :jobName];
        for (CronTrigger orderReminderJob : orderReminderJobs) {
            System.abortJob(orderReminderJob.Id);
        }
        System.scheduleBatch(new OrderReminderBatch(), jobName, 1400);
    }
}