force-app/main/default/objects/Email_activity__c/Email_activity__c.object-meta.xml
<CustomObject>
    <label>Email Activity</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Email Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Email activities</relationshipLabel>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Email_activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_activity__c/fields/Send_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Email__c</fullName>
    <label>Send To Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/Event_Badge__c.object-meta.xml
<CustomObject>
    <label>Event Badge</label>
    <nameField>
        <displayFormat>EB-{000000}</displayFormat>
        <label>Event Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Badge__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Badges</relationshipLabel>
    <relationshipName>Event_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Event Badges</relationshipLabel>
    <relationshipName>Event_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration_Sub_Group__c/Event_Registration_Sub_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Sub Group</label>
    <nameField>
        <displayFormat>ERSG-{0000000000}</displayFormat>
        <label>Event Registration Sub Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registration Sub Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration_Sub_Group__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Locked for adding new participants or change existing participants</description>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Registration_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Sub_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration Sub Group</label>
    <referenceTo>Event_Registration_Sub_Group__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Email__c.field-meta.xml
<CustomField>
    <fullName>Participant_Email__c</fullName>
    <label>Participant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/QR_Code_needed__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QR Code needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EventRegistrationSubGroupTriggerHelper.cls
public without sharing class EventRegistrationSubGroupTriggerHelper {
    public EventRegistrationSubGroupTriggerHelper() {

    }
    public static void sendEmailSubGroupMembers(List<Event_Registration_Sub_Group__c> subGroups, Map<Id, Event_Registration_Sub_Group__c> subGroupsOldMap) {
        List<String> lockedSubGroupIds = new List<String>();
        for (Event_Registration_Sub_Group__c subGroup : subGroups) {
            if (subGroup.Is_Locked__c && subGroup.Is_Locked__c != subGroupsOldMap.get(subGroup.Id).Is_Locked__c) {
                lockedSubGroupIds.add(subGroup.Id);
            }
        }
        if (lockedSubGroupIds.size() != 0) {
            List<Participant__c> partisipants = [
                SELECT Id, QR_Code_needed__c, Contact__c, Event_custom__c, Event_Registration_Sub_Group__c, Participant_Email__c, Contact__r.Email, Contact__r.Name FROM Participant__c WHERE Event_Registration_Sub_Group__c IN :lockedSubGroupIds
                ];
            List<Event_Badge__c> badges = new List<Event_Badge__c>();
            for (Participant__c partisipant : partisipants) {
                partisipant.QR_Code_needed__c = true;
                Event_Badge__c badge = new Event_Badge__c();
                badge.Event_Participation__c = partisipant.Id;
                badges.add(badge);
            }
            //Part for getting QR codes logic
            if (partisipants.size() > 0) {
                update partisipants;
            }
            
            List<Email_activity__c> emailActivities = new List<Email_activity__c>();
            for (Participant__c partisipant : partisipants) {
                Email_activity__c emailActivity = new Email_activity__c();
                emailActivity.Event_Participation__c = partisipant.Id;
                emailActivity.Contact__c = partisipant.Contact__c;
                emailActivity.Event_custom__c = partisipant.Event_custom__c;
                if (partisipant.Contact__r.Name == 'Undefined Participant') {
                    emailActivity.Send_to_email__c = partisipant.Participant_Email__c;
                } else {
                    emailActivity.Send_to_email__c = partisipant.Contact__r.Email;
                }
                emailActivity.Type__c = 'Sub group is submited';
                emailActivities.add(emailActivity);
            }
            insert emailActivities;
        }
    }
}