force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Enable_management_group__c.field-meta.xml
<CustomField>
    <fullName>Enable_management_group__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox fire trigger which create chatter group for management group members.</description>
    <label>Enable management group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Management_Chatter_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Management_Chatter_Group_Id__c</fullName>
    <label>Management Chatter Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/MG_Chatter_Group_Accessibility__c.field-meta.xml
<CustomField>
    <fullName>MG_Chatter_Group_Accessibility__c</fullName>
    <label>MG Chatter Group Accessibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unlisted</fullName>
                <default>true</default>
                <label>Unlisted</label>
            </value>
            <value>
                <fullName>Private</fullName>
                <isActive>false</isActive>
                <label>Private</label>
            </value>
            <value>
                <fullName>Public</fullName>
                <isActive>false</isActive>
                <label>Public</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Common</fullName>
                <isActive>false</isActive>
                <label>Common</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateManagementChatterGroupsBatch.cls
//One time batch
public class UpdateManagementChatterGroupsBatch implements Database.Batchable<SObject>, Database.Stateful{
    public Log__c log = new Log__c();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        log.Process_Name__c='Batch: UpdateManagementChatterGroupsBatch';
        log.Start_Time__c = Datetime.now();
        log.Status__c='In Progress';
        log.Type__c='Batch';
        insert log;
        log.Status__c='Completed';
        log.Message__c='';

        return Database.getQueryLocator(
                'SELECT Id, Name, MG_Chatter_Group_Accessibility__c, Management_Chatter_Group_Id__c ' +
                        'FROM Group__c ' +
                        'WHERE Enable_management_group__c = TRUE'
        );
    }

    public void execute(Database.BatchableContext bc, List<Group__c> records) {
        Savepoint sp = Database.setSavepoint();
        try {
            List<Id> existedChatterGroupIds = new List<Id>();

            for(Group__c g : records){
                existedChatterGroupIds.add(g.Management_Chatter_Group_Id__c);
                g.Enable_management_group__c = false;
                g.Management_Chatter_Group_Id__c = '';
            }

            update records;

            List<CollaborationGroup> chatterGroups = [SELECT Id FROM CollaborationGroup WHERE Id IN :existedChatterGroupIds];
            delete chatterGroups;

            for(Group__c g : records){
                g.MG_Chatter_Group_Accessibility__c = 'Unlisted';
                g.Enable_management_group__c = true;
            }

            update records;

        } catch (Exception e) {
            Database.rollback(sp);
            log.Message__c+=e.getMessage()+'\n';
            log.Status__c='Error';
        }
    }

    public void finish(Database.BatchableContext bc) {
        log.End_Time__c = Datetime.now();
        update log;
    }

}