force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Chatter_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Id__c</fullName>
    <label>Chatter Group Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Enable_management_group__c.field-meta.xml
<CustomField>
    <fullName>Enable_management_group__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox fire trigger which create chatter group for management group members.</description>
    <label>Enable management group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Enable_synchronization__c.field-meta.xml
<CustomField>
    <fullName>Enable_synchronization__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field enables synchronization Group with Chatter Group</description>
    <label>Enable synchronization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Management_Chatter_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Management_Chatter_Group_Id__c</fullName>
    <label>Management Chatter Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/GroupChatterGroupAssotiation__c.object-meta.xml
<CustomObject>
    <label>Working Group Membership</label>
    <nameField>
        <displayFormat>IGM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Working Group Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Working Groups</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Working Group Memberships</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Alzheimer Europe representative</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate Editor</fullName>
            </value>
            <value>
                <fullName>Book Review Editor</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>CME Editor</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Chair Communication Committee</fullName>
            </value>
            <value>
                <fullName>Chair Education Committee</fullName>
            </value>
            <value>
                <fullName>Chair Programme Committee</fullName>
            </value>
            <value>
                <fullName>Chair Scientific Committee</fullName>
            </value>
            <value>
                <fullName>Chair Teaching Course sub-Committee</fullName>
            </value>
            <value>
                <fullName>Co-Chair</fullName>
            </value>
            <value>
                <fullName>EANO representative</fullName>
            </value>
            <value>
                <fullName>EAPC representative</fullName>
            </value>
            <value>
                <fullName>EC-IFCN representative</fullName>
            </value>
            <value>
                <fullName>ECTRIMS representative</fullName>
            </value>
            <value>
                <fullName>EFAS representative</fullName>
            </value>
            <value>
                <fullName>EFIC representative</fullName>
            </value>
            <value>
                <fullName>EFNR representative</fullName>
            </value>
            <value>
                <fullName>EHF representative</fullName>
            </value>
            <value>
                <fullName>EQTF Representative</fullName>
            </value>
            <value>
                <fullName>ESO representative</fullName>
            </value>
            <value>
                <fullName>Editor-in-Chief</fullName>
            </value>
            <value>
                <fullName>Ethics Advisor</fullName>
            </value>
            <value>
                <fullName>EuGMS representative</fullName>
            </value>
            <value>
                <fullName>Ex-officio member</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Management Group Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SynchronizationGroupMembersHelper.cls
public with sharing class SynchronizationGroupMembersHelper {
    public static void insertUndeleteGroupMembers(List<GroupChatterGroupAssotiation__c> newMembers) {
        List<GroupChatterGroupAssotiation__c> selectedNewMembers = [
                SELECT Id, Name, Contact__c, Group__r.Enable_synchronization__c, Group__r.Name, Role__c,
                        Group__r.Chatter_Group_Id__c, Group__r.Management_Chatter_Group_Id__c, Group__r.Enable_management_group__c
                FROM GroupChatterGroupAssotiation__c
                WHERE Id IN:newMembers
        ];

        List<Id> contactIds = new List<Id>();
        List<Id> groupsIds = new List<Id>();

        for (GroupChatterGroupAssotiation__c gcg : selectedNewMembers) {
            contactIds.add(gcg.Contact__c);
            groupsIds.add(gcg.Group__r.Chatter_Group_Id__c);
            groupsIds.add(gcg.Group__r.Management_Chatter_Group_Id__c);
        }

        List<User> users = [
                SELECT Id, ContactId, IsActive
                FROM User
                WHERE ContactId IN :contactIds
        ];

        List<CollaborationGroup> collGroups = [
                SELECT Id, Name
                FROM CollaborationGroup
                WHERE Id IN :groupsIds
        ];

        List<CollaborationGroupMember> existedGroupMembers = [
                SELECT CollaborationGroupId, MemberId
                FROM CollaborationGroupMember
                WHERE MemberId IN :users
        ];

        Set<CollaborationGroupMember> cgm = new Set<CollaborationGroupMember>();

        for (GroupChatterGroupAssotiation__c gcg : selectedNewMembers) {
            List<Id> potentialChatterGroups = new List<Id>();

            if(gcg.Group__r.Enable_synchronization__c){
                potentialChatterGroups.add(gcg.Group__r.Chatter_Group_Id__c);
            }

            if(gcg.Group__r.Enable_management_group__c && gcg.Role__c == 'Management Group Member'){
                potentialChatterGroups.add(gcg.Group__r.Management_Chatter_Group_Id__c);
            }

            Id workingGroupMemberUserId;

            for (User u : users) {
                if (u.ContactId == gcg.Contact__c) {
                    workingGroupMemberUserId = u.Id;
                }
            }

            if(workingGroupMemberUserId != null){

                for(Id potentialChatterGroupId : potentialChatterGroups){

                    for (CollaborationGroup chatterGroup : collGroups) {

                        if (potentialChatterGroupId == chatterGroup.Id) {
                            if (!chatterDuplicateCheck(existedGroupMembers, workingGroupMemberUserId, chatterGroup.Id)) {
                                cgm.add(new CollaborationGroupMember (CollaborationGroupId = chatterGroup.Id, MemberId = workingGroupMemberUserId));
                            }
                        }

                    }

                }

            }

        }

        insert new List<CollaborationGroupMember>(cgm);

    }

    public static Boolean chatterDuplicateCheck(List<CollaborationGroupMember> existedGroupMembers, Id userId, Id groupId) {
        Boolean isExist = false;
        for (CollaborationGroupMember c : existedGroupMembers) {
            if (c.CollaborationGroupId == groupId && c.MemberId == userId) {
                isExist = true;
            }
        }
        return isExist;
    }

    public static void checkGroupMemberDuplicateBeforeInsert(List<GroupChatterGroupAssotiation__c> newMembers) {
        List<Id> contactIds = new List<Id>();
        for (GroupChatterGroupAssotiation__c gcg : newMembers) {
            contactIds.add(gcg.Contact__c);
        }
        List<GroupChatterGroupAssotiation__c> existedGroupAssotiations = [
                SELECT Id, Contact__c, Group__c, Role__c
                FROM GroupChatterGroupAssotiation__c
                WHERE Contact__c IN :contactIds
        ];
        for (GroupChatterGroupAssotiation__c gcga : existedGroupAssotiations) {
            for (GroupChatterGroupAssotiation__c nm : newMembers) {
                if(gcga.Id != nm.Id){
                    if (nm.Contact__c == gcga.Contact__c && nm.Group__c == gcga.Group__c && nm.Role__c == gcga.Role__c) {
                        nm.addError('This contact already has this role in this group.');
                    }
                }

            }
        }
    }

    public static void deleteFromChatterGroup(List<GroupChatterGroupAssotiation__c> membersToDelete){
        //check if group synchronization enabled
        List<GroupChatterGroupAssotiation__c> membersWithEnabledSync = [
                SELECT Id, Contact__c, Group__c, Group__r.Enable_synchronization__c, Group__r.Chatter_Group_Id__c,
                        Group__r.Management_Chatter_Group_Id__c, Group__r.Enable_management_group__c, Role__c
                FROM GroupChatterGroupAssotiation__c
                WHERE Id IN:membersToDelete
        ];

        Set<Id> contactIds = new Set<Id>();
        List<Id> chatterGroupsIds = new List<Id>();

        for (GroupChatterGroupAssotiation__c gcg : membersWithEnabledSync) {

            if(gcg.Group__r.Chatter_Group_Id__c != null && gcg.Group__r.Enable_synchronization__c){
                chatterGroupsIds.add(gcg.Group__r.Chatter_Group_Id__c);
                contactIds.add(gcg.Contact__c);
            }

            if(gcg.Group__r.Management_Chatter_Group_Id__c != null && gcg.Group__r.Enable_management_group__c){
                chatterGroupsIds.add(gcg.Group__r.Management_Chatter_Group_Id__c);
                contactIds.add(gcg.Contact__c);
            }

        }

        //check if groupsMembers have double membership in group
        List<GroupChatterGroupAssotiation__c> allContactsWorkingGroupAssotiations = [
                SELECT Id, Contact__c, Group__c, Role__c
                FROM GroupChatterGroupAssotiation__c
                WHERE Contact__c IN :contactIds
        ];

        List<GroupChatterGroupAssotiation__c> updatedMembersWithEnabledSync = new List<GroupChatterGroupAssotiation__c>();

        List<GroupChatterGroupAssotiation__c> workingGroupManagementMembersToDel = new List<GroupChatterGroupAssotiation__c>();

        for (GroupChatterGroupAssotiation__c triggerGroupMember : membersWithEnabledSync) {

            if(triggerGroupMember.Group__r.Enable_management_group__c
                    && triggerGroupMember.Group__r.Management_Chatter_Group_Id__c != null
                    && triggerGroupMember.Role__c == 'Management Group Member'){
                workingGroupManagementMembersToDel.add(triggerGroupMember);
            }

            if(triggerGroupMember.Group__r.Enable_synchronization__c
                    && triggerGroupMember.Group__r.Chatter_Group_Id__c != null){
                Boolean duplicateFound = false;

                for (GroupChatterGroupAssotiation__c allGroupMember : allContactsWorkingGroupAssotiations) {
                    if(allGroupMember.Id != triggerGroupMember.Id){
                        if (triggerGroupMember.Contact__c == allGroupMember.Contact__c && triggerGroupMember.Group__c == allGroupMember.Group__c) {
                            duplicateFound = true;
                            break;
                        }
                    }
                }

                if(!duplicateFound){
                    updatedMembersWithEnabledSync.add(triggerGroupMember);
                }
            }

        }

        //check if chatter group exists
        Map<Id, CollaborationGroup> groupMembersGroups = new Map<Id, CollaborationGroup>([
                SELECT Id, Name
                FROM CollaborationGroup
                WHERE Id IN :chatterGroupsIds
        ]);

        List<GroupChatterGroupAssotiation__c> membersWithExistedChatterGroups = new List<GroupChatterGroupAssotiation__c>();

        for(GroupChatterGroupAssotiation__c groupMember : updatedMembersWithEnabledSync){
            if(groupMembersGroups.containsKey(groupMember.Group__r.Chatter_Group_Id__c)){
                membersWithExistedChatterGroups.add(groupMember);
            }
        }

        List<GroupChatterGroupAssotiation__c> managementMembersWithExistedChatterGroups = new List<GroupChatterGroupAssotiation__c>();

        for(GroupChatterGroupAssotiation__c groupMember : workingGroupManagementMembersToDel){
            if(groupMembersGroups.containsKey(groupMember.Group__r.Management_Chatter_Group_Id__c)){
                managementMembersWithExistedChatterGroups.add(groupMember);
            }
        }

        //check if the member is part of related chatter group
        List<User> groupMembersUsers = [
                SELECT Id, ContactId
                FROM User
                WHERE ContactId IN :contactIds
        ];

        List<CollaborationGroupMember> chatterGroupMembers = [
                SELECT CollaborationGroupId, MemberId
                FROM CollaborationGroupMember
                WHERE MemberId IN :groupMembersUsers
        ];

        Set<CollaborationGroupMember> groupMembersToDelete = new Set<CollaborationGroupMember>();

        for(GroupChatterGroupAssotiation__c groupMember : membersWithExistedChatterGroups){
            for(User user : groupMembersUsers){
                if(user.ContactId == groupMember.Contact__c){
                    for (CollaborationGroupMember c : chatterGroupMembers) {
                        if (c.CollaborationGroupId == groupMember.Group__r.Chatter_Group_Id__c && c.MemberId == user.Id) {
                            groupMembersToDelete.add(c);
                        }
                    }
                }
            }
        }

        for(GroupChatterGroupAssotiation__c groupMember : managementMembersWithExistedChatterGroups){
            for(User user : groupMembersUsers){
                if(user.ContactId == groupMember.Contact__c){
                    for (CollaborationGroupMember c : chatterGroupMembers) {
                        if (c.CollaborationGroupId == groupMember.Group__r.Management_Chatter_Group_Id__c && c.MemberId == user.Id) {
                            groupMembersToDelete.add(c);
                        }
                    }
                }
            }
        }

        //remove chatter group membership
        if(!groupMembersToDelete.isEmpty()){
            delete new List<CollaborationGroupMember>(groupMembersToDelete);
        }
    }

    public static void updateGroupMembers(List<GroupChatterGroupAssotiation__c> triggerNew, List<GroupChatterGroupAssotiation__c> triggerOld){
        List<GroupChatterGroupAssotiation__c> membersToInsert = new List<GroupChatterGroupAssotiation__c>();
        List<GroupChatterGroupAssotiation__c> membersToDelete = new List<GroupChatterGroupAssotiation__c>();

        for(Integer i = 0; i < triggerNew.size(); i++){
            if(triggerNew[i].Role__c == 'Management Group Member' && triggerOld[i].Role__c != 'Management Group Member'){
                membersToInsert.add(triggerNew[i]);
            }

            if(triggerNew[i].Role__c != 'Management Group Member' && triggerOld[i].Role__c == 'Management Group Member'){
                membersToDelete.add(triggerOld[i]);
            }
        }

        if(!membersToInsert.isEmpty()){
            insertUndeleteGroupMembers(membersToInsert);
        }

        if(!membersToDelete.isEmpty()){
            deleteFromChatterGroup_UPDATE(membersToDelete);
        }

    }

    public static void deleteFromChatterGroup_UPDATE(List<GroupChatterGroupAssotiation__c> membersToDelete){
        //check if group synchronization enabled
        List<GroupChatterGroupAssotiation__c> membersWithEnabledSync = [
                SELECT Id, Contact__c, Group__c, Group__r.Enable_synchronization__c, Group__r.Chatter_Group_Id__c,
                        Group__r.Management_Chatter_Group_Id__c, Group__r.Enable_management_group__c, Role__c
                FROM GroupChatterGroupAssotiation__c
                WHERE Id IN:membersToDelete
        ];

        Set<Id> contactIds = new Set<Id>();
        List<Id> chatterGroupsIds = new List<Id>();

        for (GroupChatterGroupAssotiation__c gcg : membersWithEnabledSync) {

            if(gcg.Group__r.Management_Chatter_Group_Id__c != null && gcg.Group__r.Enable_management_group__c){
                chatterGroupsIds.add(gcg.Group__r.Management_Chatter_Group_Id__c);
                contactIds.add(gcg.Contact__c);
            }

        }

        List<GroupChatterGroupAssotiation__c> workingGroupManagementMembersToDel = new List<GroupChatterGroupAssotiation__c>();

        for (GroupChatterGroupAssotiation__c triggerGroupMember : membersWithEnabledSync) {

            if(triggerGroupMember.Group__r.Enable_management_group__c
                    && triggerGroupMember.Group__r.Management_Chatter_Group_Id__c != null){
                workingGroupManagementMembersToDel.add(triggerGroupMember);
            }

        }

        //check if chatter group exists
        Map<Id, CollaborationGroup> groupMembersGroups = new Map<Id, CollaborationGroup>([
                SELECT Id, Name
                FROM CollaborationGroup
                WHERE Id IN :chatterGroupsIds
        ]);

        List<GroupChatterGroupAssotiation__c> managementMembersWithExistedChatterGroups = new List<GroupChatterGroupAssotiation__c>();

        for(GroupChatterGroupAssotiation__c groupMember : workingGroupManagementMembersToDel){
            if(groupMembersGroups.containsKey(groupMember.Group__r.Management_Chatter_Group_Id__c)){
                managementMembersWithExistedChatterGroups.add(groupMember);
            }
        }

        //check if the member is part of related chatter group
        List<User> groupMembersUsers = [
                SELECT Id, ContactId
                FROM User
                WHERE ContactId IN :contactIds
        ];

        List<CollaborationGroupMember> chatterGroupMembers = [
                SELECT CollaborationGroupId, MemberId
                FROM CollaborationGroupMember
                WHERE MemberId IN :groupMembersUsers
        ];

        Set<CollaborationGroupMember> groupMembersToDelete = new Set<CollaborationGroupMember>();


        for(GroupChatterGroupAssotiation__c groupMember : managementMembersWithExistedChatterGroups){
            for(User user : groupMembersUsers){
                if(user.ContactId == groupMember.Contact__c){
                    for (CollaborationGroupMember c : chatterGroupMembers) {
                        if (c.CollaborationGroupId == groupMember.Group__r.Management_Chatter_Group_Id__c && c.MemberId == user.Id) {
                            groupMembersToDelete.add(c);
                        }
                    }
                }
            }
        }

        //remove chatter group membership
        if(!groupMembersToDelete.isEmpty()){
            delete new List<CollaborationGroupMember>(groupMembersToDelete);
        }
    }
}