force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Chatter_Group_Accessibility__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Accessibility__c</fullName>
    <label>Chatter Group Accessibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Unlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group__c/fields/Chatter_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Id__c</fullName>
    <label>Chatter Group Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Enable_management_group__c.field-meta.xml
<CustomField>
    <fullName>Enable_management_group__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox fire trigger which create chatter group for management group members.</description>
    <label>Enable management group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Enable_synchronization__c.field-meta.xml
<CustomField>
    <fullName>Enable_synchronization__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field enables synchronization Group with Chatter Group</description>
    <label>Enable synchronization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Management_Chatter_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Management_Chatter_Group_Id__c</fullName>
    <label>Management Chatter Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/recordTypes/Level_3_Working_Group.recordType-meta.xml
<RecordType>
    <fullName>Level_3_Working_Group</fullName>
    <active>true</active>
    <label>Level 3 Working Group</label>
</RecordType>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/GroupChatterGroupAssotiation__c.object-meta.xml
<CustomObject>
    <label>Working Group Membership</label>
    <nameField>
        <displayFormat>IGM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Working Group Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Working Groups</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Working Group Memberships</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Alzheimer Europe representative</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate Editor</fullName>
            </value>
            <value>
                <fullName>Book Review Editor</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>CME Editor</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Chair Communication Committee</fullName>
            </value>
            <value>
                <fullName>Chair Education Committee</fullName>
            </value>
            <value>
                <fullName>Chair Programme Committee</fullName>
            </value>
            <value>
                <fullName>Chair Scientific Committee</fullName>
            </value>
            <value>
                <fullName>Chair Teaching Course sub-Committee</fullName>
            </value>
            <value>
                <fullName>Co-Chair</fullName>
            </value>
            <value>
                <fullName>EANO representative</fullName>
            </value>
            <value>
                <fullName>EAPC representative</fullName>
            </value>
            <value>
                <fullName>EC-IFCN representative</fullName>
            </value>
            <value>
                <fullName>ECTRIMS representative</fullName>
            </value>
            <value>
                <fullName>EFAS representative</fullName>
            </value>
            <value>
                <fullName>EFIC representative</fullName>
            </value>
            <value>
                <fullName>EFNR representative</fullName>
            </value>
            <value>
                <fullName>EHF representative</fullName>
            </value>
            <value>
                <fullName>EQTF Representative</fullName>
            </value>
            <value>
                <fullName>ESO representative</fullName>
            </value>
            <value>
                <fullName>Editor-in-Chief</fullName>
            </value>
            <value>
                <fullName>Ethics Advisor</fullName>
            </value>
            <value>
                <fullName>EuGMS representative</fullName>
            </value>
            <value>
                <fullName>Ex-officio member</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Management Group Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/recordTypes/Level_3_Working_Group.recordType-meta.xml
<RecordType>
    <fullName>Level_3_Working_Group</fullName>
    <active>true</active>
    <label>Level 3 Working Group</label>
</RecordType>

force-app/main/default/classes/CreateChatterGroupHelperTest.cls
@IsTest public with sharing class CreateChatterGroupHelperTest {

    @IsTest public static void newWorkingGroupTest() {
        List<Group__c> newCustomGroups = new List<Group__c>();
        newCustomGroups.add(new Group__c(Name='Group_un1', Enable_synchronization__c = true, Enable_management_group__c = false, Chatter_Group_Accessibility__c = 'Public'));
        newCustomGroups.add(new Group__c(Name='Group_un2', Enable_synchronization__c = false, Enable_management_group__c = true));

        insert newCustomGroups;

        List<CollaborationGroup> allChatterGroups = [SELECT Id, Name, CollaborationType FROM CollaborationGroup];

        System.assertEquals(2, allChatterGroups.size());

        for(CollaborationGroup chatterGroup : allChatterGroups){

            if(chatterGroup.Name == 'MG Group_un2'){
                System.assertEquals('Private', chatterGroup.CollaborationType);
            } else {
                System.assertEquals(newCustomGroups[0].Chatter_Group_Accessibility__c, chatterGroup.CollaborationType);
            }

        }

    }

    @IsTest public static void updateWorkingGroupTest() {
        Group__c g = new Group__c(Name='Group_un1', Enable_synchronization__c = true, Enable_management_group__c = true, Chatter_Group_Accessibility__c = 'Public');
        insert g;
        g  = [SELECT Id, Name, Chatter_Group_Id__c, Management_Chatter_Group_Id__c, Enable_synchronization__c, Enable_management_group__c FROM Group__c WHERE Id =:g.Id];
        g.Enable_synchronization__c = true;
        g.Enable_management_group__c = false;
        g.Name = 'Group_un2';
        update g;
        List<Id> chatterGroupIds = new List<Id>{g.Chatter_Group_Id__c, g.Management_Chatter_Group_Id__c};
        List<CollaborationGroup> chatterGroups = [SELECT Id, Name FROM CollaborationGroup WHERE Id IN :chatterGroupIds];

        for(CollaborationGroup chatterGroup : chatterGroups){

            if(chatterGroup.Id == g.Management_Chatter_Group_Id__c){
                System.assertEquals('MG Group_un1', chatterGroup.Name);
            }

            if(chatterGroup.Id == g.Chatter_Group_Id__c){
                System.assertEquals(g.Name, chatterGroup.Name);
            }

        }

        CollaborationGroup managementGroup = [SELECT Id FROM CollaborationGroup WHERE Name = 'MG Group_un1'];
        delete managementGroup;

        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Id MCUP = [SELECT Id FROM Profile WHERE Name = 'Member Community User Profile'].Id;
        Account account = new Account(Name = 'Individuals (Contacts)', RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Individuals' AND SobjectType = 'Account' LIMIT 1].Id);
        insert account;

        List<Contact> contacts = new List<Contact>();

        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact1', AccountId = account.Id));
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact2', AccountId = account.Id));
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact3', AccountId = account.Id));

        insert contacts;

        List<User> user = new List<User>();

        user.add(
                new User(
                        Alias = 'test0', Email = '0test_un@email.com',
                        EmailEncodingKey = 'UTF-8', LastName = 'Test_un', LanguageLocaleKey = 'en_US',
                        LocaleSidKey = 'en_US', ProfileId = MCUP, Country = 'United States', IsActive = true,
                        ContactId = contacts[0].Id, TimeZoneSidKey = 'America/Los_Angeles', Username = '0test_un@email.com'
                )
        );
        user.add(
                new User(
                        Alias = 'test1', Email = '1test_un@email.com',
                        EmailEncodingKey = 'UTF-8', LastName = contacts[1].LastName, LanguageLocaleKey = 'en_US',
                        LocaleSidKey = 'en_US', ProfileId = MCUP, Country = 'United States', IsActive = true,
                        ContactId = contacts[1].Id, TimeZoneSidKey = 'America/Los_Angeles', Username = '1test_un@email.com'
                )
        );

        insert user;

        RecordType groupMemberRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'GroupChatterGroupAssotiation__c' AND DeveloperName = 'Level_3_Working_Group'];
        List<GroupChatterGroupAssotiation__c> workingGroupMembers = new List<GroupChatterGroupAssotiation__c>();

        workingGroupMembers.add(new GroupChatterGroupAssotiation__c(Group__c = g.Id, Contact__c = contacts[0].Id, Role__c = 'Management Group Member', RecordTypeId = groupMemberRecordType.Id));
        workingGroupMembers.add(new GroupChatterGroupAssotiation__c(Group__c = g.Id, Contact__c = contacts[1].Id));
        workingGroupMembers.add(new GroupChatterGroupAssotiation__c(Group__c = g.Id, Contact__c = contacts[2].Id));

        insert workingGroupMembers;

        g.Enable_management_group__c = true;
        update g;

        g  = [SELECT Id, Name, Chatter_Group_Id__c, Management_Chatter_Group_Id__c, Enable_synchronization__c, Enable_management_group__c FROM Group__c WHERE Id =:g.Id];

        List<CollaborationGroupMember> managedChatterGroupMembers = [
                SELECT Id, MemberId
                FROM CollaborationGroupMember
                WHERE CollaborationGroupId = :g.Management_Chatter_Group_Id__c
                AND CollaborationRole != 'Admin'
        ];

        System.assertEquals(1, managedChatterGroupMembers.size());

        g.Enable_management_group__c = false;
        update g;

        g.Enable_management_group__c = true;
        g.Name = 'Group_un3';
        update g;

        managementGroup = [SELECT Id, Name FROM CollaborationGroup WHERE Id  = :g.Management_Chatter_Group_Id__c];

        System.assertEquals('MG Group_un3', managementGroup.Name);
    }

    @IsTest public static void getChatterGroupNameTest(){
        String str = '';

        for(Integer i =0; i < 41; i++){
            str += 'a';
        }

        String str2 = '';

        for(Integer i =0; i < 37; i++){
            str2 += 'a';
        }

        str2+='...';

        System.assertEquals(str2, CreateChatterGroupHelper.getChatterGroupName(str));
    }

}