force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Type_of_Group__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Group__c</fullName>
    <label>Type of Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Sub-committee</fullName>
            </value>
            <value>
                <fullName>Task Force</fullName>
            </value>
            <value>
                <fullName>Scientific Panels</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Scientific Panel</fullName>
                <isActive>false</isActive>
                <label>Scientific Panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/GroupChatterGroupAssotiation__c.object-meta.xml
<CustomObject>
    <label>Working Group Membership</label>
    <nameField>
        <displayFormat>IGM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Working Group Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Working Groups</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Working Group Memberships</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Type_of_Group__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Group__c</fullName>
    <label>Type of Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Temp Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/MembershipContactAssotiation__c.object-meta.xml
<CustomObject>
    <label>Membership Status</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Membership Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_date__c</fullName>
    <label>Assignment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date when current membership expires</description>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembershipContactAssotiation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Membership Status</relationshipLabel>
    <relationshipName>MembershipContactAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SetMembershipsFlagsOnContactBatch_Test.cls
@IsTest
public with sharing class SetMembershipsFlagsOnContactBatch_Test {
    @testSetup static void setup() {
        List<Contact> contacts = new List<Contact>();
        for(Integer i=0; i<10; i++){
            contacts.add(new Contact(LastName='Test'+i));
        }
        insert contacts;
        List<Membership__c> memberships = new List<Membership__c>();
        memberships.add(new Membership__c(Name='Test1', API__c='full_membership'));
        memberships.add(new Membership__c(Name='Test2', API__c='corresponding_membership'));
        memberships.add(new Membership__c(Name='Test3', API__c='fellow_membership'));
        memberships.add(new Membership__c(Name='Test4', API__c='resident_and_research_membership'));
        memberships.add(new Membership__c(Name='Test5', API__c='associate_individual_membership'));
        memberships.add(new Membership__c(Name='Test6', API__c='student_membership'));
        insert memberships;
        List<MembershipContactAssotiation__c> membershipStatuses = new List<MembershipContactAssotiation__c>();
        for(Contact c : contacts){
            membershipStatuses.add(new MembershipContactAssotiation__c(Contact__c = c.Id, Membership__c = memberships[0].Id, Expiration_date__c = Datetime.now().addYears(1), Assignment_date__c = Date.newInstance(Date.today().year(), 01, 28)));
        }
        membershipStatuses.add(new MembershipContactAssotiation__c(Contact__c = contacts[0].Id, Membership__c = memberships[1].Id, Expiration_date__c = Datetime.now().addYears(1), Assignment_date__c = Date.newInstance(Date.today().year(), 01, 28)));
        membershipStatuses.add(new MembershipContactAssotiation__c(Contact__c = contacts[0].Id, Membership__c = memberships[2].Id, Expiration_date__c = Datetime.now().addYears(1), Assignment_date__c = Date.newInstance(Date.today().year(), 01, 28)));
        membershipStatuses.add(new MembershipContactAssotiation__c(Contact__c = contacts[0].Id, Membership__c = memberships[3].Id, Expiration_date__c = Datetime.now().addYears(1), Assignment_date__c = Date.newInstance(Date.today().year(), 01, 28)));
        membershipStatuses.add(new MembershipContactAssotiation__c(Contact__c = contacts[0].Id, Membership__c = memberships[4].Id, Expiration_date__c = Datetime.now().addYears(1), Assignment_date__c = Date.newInstance(Date.today().year(), 01, 28)));
        membershipStatuses.add(new MembershipContactAssotiation__c(Contact__c = contacts[0].Id, Membership__c = memberships[5].Id, Expiration_date__c = Datetime.now().addYears(1), Assignment_date__c = Date.newInstance(Date.today().year(), 01, 28)));
        insert membershipStatuses;

        Id groupRTId = Schema.SObjectType.Group__c.getRecordTypeInfosByName().get('Level 3 Working Group').getRecordTypeId();
        Group__c testGroup = new Group__c(Name = 'Test_Group_1', Type_of_Group__c = 'Other', RecordTypeId = groupRTId);
        insert testGroup;

        Id groupRoleRTId = Schema.SObjectType.GroupChatterGroupAssotiation__c.getRecordTypeInfosByName().get('Level 3 Working Group').getRecordTypeId();
        List<GroupChatterGroupAssotiation__c> groupRoles = new List<GroupChatterGroupAssotiation__c>();
        for (Contact c : contacts) {
            groupRoles.add(new GroupChatterGroupAssotiation__c(Contact__c = c.Id, Group__c = testGroup.Id, RecordTypeId = groupRoleRTId));
        }
        insert  groupRoles;
    }
    @IsTest public static void setMembershipsFlagsOnContactBatchTest(){
        Test.startTest();
        SetMembershipsFlagsOnContactBatch job = new SetMembershipsFlagsOnContactBatch();
        Database.executeBatch(job, 200);
        Test.stopTest();
        List<Contact> contacts = [SELECT Id, Flag_EAN_Full_Member__c FROM Contact];
        for (Contact c : contacts){
            System.assertEquals(true, c.Flag_EAN_Full_Member__c);
        }

        List<GroupChatterGroupAssotiation__c> groupRoles = [SELECT Group__r.Type_of_Group__c, Type_of_Group__c FROM GroupChatterGroupAssotiation__c];
        for (GroupChatterGroupAssotiation__c groupRole : groupRoles) {
            System.debug(groupRole.Type_of_Group__c);
            System.debug(groupRole.Group__r.Type_of_Group__c);
            System.assertEquals(groupRole.Type_of_Group__c, groupRole.Group__r.Type_of_Group__c);
        }
        System.assertEquals(1, [SELECT Id FROM Log__c].size());
    }
}