force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Chatter_Group_Accessibility__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Accessibility__c</fullName>
    <label>Chatter Group Accessibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Unlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group__c/fields/Chatter_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Id__c</fullName>
    <label>Chatter Group Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Enable_management_group__c.field-meta.xml
<CustomField>
    <fullName>Enable_management_group__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox fire trigger which create chatter group for management group members.</description>
    <label>Enable management group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Enable_synchronization__c.field-meta.xml
<CustomField>
    <fullName>Enable_synchronization__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field enables synchronization Group with Chatter Group</description>
    <label>Enable synchronization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group__c/recordTypes/Level_3_Working_Group.recordType-meta.xml
<RecordType>
    <fullName>Level_3_Working_Group</fullName>
    <active>true</active>
    <label>Level 3 Working Group</label>
</RecordType>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/GroupChatterGroupAssotiation__c.object-meta.xml
<CustomObject>
    <label>Working Group Membership</label>
    <nameField>
        <displayFormat>IGM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Working Group Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Working Groups</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 2 Working Group (Committee)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 3 Working Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 4 Working Group (Taskforce)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Level 1 Board (EAN Board)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <filterItems>
            <field>Group__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Working Group Memberships</relationshipLabel>
    <relationshipName>GroupChatterGroupAssotiations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Alzheimer Europe representative</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate Editor</fullName>
            </value>
            <value>
                <fullName>Book Review Editor</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>CME Editor</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Chair Communication Committee</fullName>
            </value>
            <value>
                <fullName>Chair Education Committee</fullName>
            </value>
            <value>
                <fullName>Chair Programme Committee</fullName>
            </value>
            <value>
                <fullName>Chair Scientific Committee</fullName>
            </value>
            <value>
                <fullName>Chair Teaching Course sub-Committee</fullName>
            </value>
            <value>
                <fullName>Co-Chair</fullName>
            </value>
            <value>
                <fullName>EANO representative</fullName>
            </value>
            <value>
                <fullName>EAPC representative</fullName>
            </value>
            <value>
                <fullName>EC-IFCN representative</fullName>
            </value>
            <value>
                <fullName>ECTRIMS representative</fullName>
            </value>
            <value>
                <fullName>EFAS representative</fullName>
            </value>
            <value>
                <fullName>EFIC representative</fullName>
            </value>
            <value>
                <fullName>EFNR representative</fullName>
            </value>
            <value>
                <fullName>EHF representative</fullName>
            </value>
            <value>
                <fullName>EQTF Representative</fullName>
            </value>
            <value>
                <fullName>ESO representative</fullName>
            </value>
            <value>
                <fullName>Editor-in-Chief</fullName>
            </value>
            <value>
                <fullName>Ethics Advisor</fullName>
            </value>
            <value>
                <fullName>EuGMS representative</fullName>
            </value>
            <value>
                <fullName>Ex-officio member</fullName>
            </value>
            <value>
                <fullName>Executive Director</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Management Group Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupChatterGroupAssotiation__c/recordTypes/Level_3_Working_Group.recordType-meta.xml
<RecordType>
    <fullName>Level_3_Working_Group</fullName>
    <active>true</active>
    <label>Level 3 Working Group</label>
</RecordType>

force-app/main/default/classes/SynchronizationGroupMembersHelperTest.cls
@IsTest public with sharing class SynchronizationGroupMembersHelperTest {
    @TestSetup public static void setup(){
        NewsletterSubscriptionController.isCreateSubscribersEnabled = false;
        Id cclu = [SELECT Id FROM Profile WHERE Name = 'Member Community User Profile'].Id;
        Account account = new Account(Name = 'Individuals (Contacts)', RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Individuals' AND SobjectType = 'Account' LIMIT 1].Id);
        insert account;
        Contact con = new Contact(LastName = 'testCon', AccountId = account.Id);
        insert con;
        User user = new User(
                Alias = 'test123', Email = 'test123@noemail.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing_un', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = cclu, Country = 'United States', IsActive = true,
                ContactId = con.Id, TimeZoneSidKey = 'America/Los_Angeles', Username = 'tester@noemail.com');
        insert user;
    }

    @IsTest public static void insertUndeleteGroupMembersTest(){
        Contact con = [SELECT Id FROM Contact WHERE Name='testCon'];
        User u = [SELECT Id FROM User WHERE LastName = 'Testing_un' LIMIT 1];

        Group__c g = new Group__c(Name = 'TestGroup_test', Enable_synchronization__c = true, Chatter_Group_Accessibility__c = 'Public', Enable_management_group__c = true);
        insert g;
        g = [SELECT Id, Name, Enable_synchronization__c, Chatter_Group_Id__c FROM Group__c WHERE Id = :g.Id];
        g.Enable_synchronization__c = false;
        g.Enable_management_group__c = false;
        update g;

        RecordType groupMemberRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'GroupChatterGroupAssotiation__c' AND DeveloperName = 'Level_3_Working_Group'];
        GroupChatterGroupAssotiation__c newManagementMember = new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id, RecordTypeId = groupMemberRecordType.Id, Role__c = 'Management Group Member');
        insert newManagementMember;
        List<CollaborationGroupMember> collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(collMember.size(), 0);

        delete newManagementMember;

        g.Enable_synchronization__c = true;
        update g;
        undelete newManagementMember;
        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(collMember.size(), 1);
        System.assertEquals(collMember[0].CollaborationGroupId, g.Chatter_Group_Id__c);

        delete newManagementMember;

        g.Enable_synchronization__c = true;
        g.Enable_management_group__c = true;
        update g;

        undelete newManagementMember;
        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(collMember.size(), 2);

        //Make sure that no exceptions occurs
        GroupChatterGroupAssotiation__c newMember = new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id);
        insert newMember;

    }

    @IsTest public static void checkGroupMemberDuplicateBeforeInsertTest(){
        try {
            Contact con = [SELECT Id FROM Contact WHERE Name='testCon'];
            Group__c g = new Group__c(Name='TestGroup_test', Enable_synchronization__c = true, Chatter_Group_Accessibility__c = 'Public');
            insert g;
            insert new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id);
            insert new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id);
        }catch (Exception e){
            System.assert(e.getMessage().contains('This contact already has this role in this group.'));
        }
    }

    @IsTest public static void deleteFromChatterGroupTest(){
        Contact con = [SELECT Id FROM Contact WHERE Name='testCon'];
        User u = [SELECT Id FROM User WHERE LastName = 'Testing_un' LIMIT 1];
        Group__c g = new Group__c(Name='TestGroup_test', Enable_synchronization__c = true, Chatter_Group_Accessibility__c = 'Public', Enable_management_group__c = true);
        insert g;

        g = [SELECT Id, Name, Enable_synchronization__c, Chatter_Group_Id__c FROM Group__c WHERE Id = :g.Id];
        RecordType groupMemberRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'GroupChatterGroupAssotiation__c' AND DeveloperName = 'Level_3_Working_Group'];
        GroupChatterGroupAssotiation__c newManagementMember = new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id, RecordTypeId = groupMemberRecordType.Id, Role__c = 'Management Group Member');
        insert newManagementMember;

        g.Enable_synchronization__c = false;
        g.Enable_management_group__c = false;
        update g;

        delete newManagementMember;
        List<CollaborationGroupMember> collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(2, collMember.size());

        undelete newManagementMember;

        test.startTest();
        g.Enable_synchronization__c = true;
        g.Enable_management_group__c = true;
        update g;
        delete newManagementMember;
        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(0, collMember.size());

        undelete newManagementMember;

        g.Enable_synchronization__c = false;
        update g;
        delete newManagementMember;
        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(1, collMember.size());
        System.assertEquals(g.Chatter_Group_Id__c, collMember[0].CollaborationGroupId);

        g.Enable_synchronization__c = true;
        update g;

        //test groupsMembers have double membership in group
        List<GroupChatterGroupAssotiation__c> newMembers = new List<GroupChatterGroupAssotiation__c>{
                new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id),
                new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id, RecordTypeId = groupMemberRecordType.Id, Role__c = 'Management Group Member')
        };
        insert newMembers;
        delete newMembers[1];
        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(1, collMember.size());
        test.stopTest();
    }

    @IsTest public static void updateGroupMembersTest(){
        Contact con = [SELECT Id FROM Contact WHERE Name='testCon'];
        User u = [SELECT Id FROM User WHERE LastName = 'Testing_un' LIMIT 1];
        Group__c g = new Group__c(Name='TestGroup_test', Enable_synchronization__c = true, Chatter_Group_Accessibility__c = 'Public', Enable_management_group__c = true);
        insert g;

        g = [SELECT Id, Name, Enable_synchronization__c, Chatter_Group_Id__c FROM Group__c WHERE Id = :g.Id];
        RecordType groupMemberRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'GroupChatterGroupAssotiation__c' AND DeveloperName = 'Level_3_Working_Group'];
        GroupChatterGroupAssotiation__c newManagementMember = new GroupChatterGroupAssotiation__c(Contact__c = con.Id, Group__c= g.Id, RecordTypeId = groupMemberRecordType.Id, Role__c = 'Management Group Member');
        insert newManagementMember;

        List<CollaborationGroupMember> collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(2, collMember.size());

        newManagementMember.Role__c = 'Chair';
        update newManagementMember;

        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(1, collMember.size());

        newManagementMember.Role__c = 'Management Group Member';
        update newManagementMember;

        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(2, collMember.size());

        g.Enable_management_group__c = false;
        update g;

        newManagementMember.Role__c = 'Chair';
        update newManagementMember;

        collMember = [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId = :u.Id];
        System.assertEquals(2, collMember.size());

    }
}