force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>EAN Working Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAN Working Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Chatter_Group_Accessibility__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Accessibility__c</fullName>
    <label>Chatter Group Accessibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Unlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group__c/fields/Enable_synchronization__c.field-meta.xml
<CustomField>
    <fullName>Enable_synchronization__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field enables synchronization Group with Chatter Group</description>
    <label>Enable synchronization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_CreateCustomGroupTrigger.cls
@isTest public with sharing class Test_CreateCustomGroupTrigger {
    @isTest public static void updateCustomGroupTest(){
        Group__c g = new Group__c(Name='TestWithSynch', Enable_synchronization__c = true, Chatter_Group_Accessibility__c = 'Public');
        insert g;
        CollaborationGroup cg = [SELECT Id FROM CollaborationGroup WHERE Name = 'TestWithSynch'];
        cg.Name = 'Change Name';
        update cg;
        System.assertEquals([SELECT Name FROM Group__c WHERE Name='Change Name'].size(),1);

        g.Enable_synchronization__c = false;
        update g;
        cg.Name = 'Change Name2';
        update cg;
        System.assertEquals([SELECT Name FROM Group__c WHERE Name='Change Name2'].size(),0);
    }
}