force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Department Position</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Role__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) AND 3</booleanFilter>
        <errorMessage>Please select either a Hospital or a Department.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Hospital__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Positions</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Department Positions</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/is_primary_workplace__c.field-meta.xml
<CustomField>
    <fullName>is_primary_workplace__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Workplace</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Position/Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate member society - Delegate</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Head</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Acting President</fullName>
                <isActive>false</isActive>
                <label>Acting President</label>
            </value>
            <value>
                <fullName>Advocate</fullName>
                <isActive>false</isActive>
                <label>Advocate</label>
            </value>
            <value>
                <fullName>Basic</fullName>
                <isActive>false</isActive>
                <label>Basic</label>
            </value>
            <value>
                <fullName>Co-Chair</fullName>
                <isActive>false</isActive>
                <label>Co-Chair</label>
            </value>
            <value>
                <fullName>Collaborator</fullName>
                <isActive>false</isActive>
                <label>Collaborator</label>
            </value>
            <value>
                <fullName>Coordinator</fullName>
                <isActive>false</isActive>
                <label>Coordinator</label>
            </value>
            <value>
                <fullName>Delegate</fullName>
                <isActive>false</isActive>
                <label>Delegate</label>
            </value>
            <value>
                <fullName>Director</fullName>
                <isActive>false</isActive>
                <label>Director</label>
            </value>
            <value>
                <fullName>Exectuive Director</fullName>
                <isActive>false</isActive>
                <label>Exectuive Director</label>
            </value>
            <value>
                <fullName>Executive</fullName>
                <isActive>false</isActive>
                <label>Executive</label>
            </value>
            <value>
                <fullName>Fellow</fullName>
                <isActive>false</isActive>
                <label>Fellow</label>
            </value>
            <value>
                <fullName>Industry - Main Contact</fullName>
                <isActive>false</isActive>
                <label>Industry - Main Contact</label>
            </value>
            <value>
                <fullName>Industry - NPO Contact</fullName>
                <isActive>false</isActive>
                <label>Industry - NPO Contact</label>
            </value>
            <value>
                <fullName>Industry - contact</fullName>
                <isActive>false</isActive>
                <label>Industry - contact</label>
            </value>
            <value>
                <fullName>Initiator</fullName>
                <isActive>false</isActive>
                <label>Initiator</label>
            </value>
            <value>
                <fullName>Institution Role1</fullName>
                <isActive>false</isActive>
                <label>Institution Role1</label>
            </value>
            <value>
                <fullName>Institution Role2</fullName>
                <isActive>false</isActive>
                <label>Institution Role2</label>
            </value>
            <value>
                <fullName>Institution Role3</fullName>
                <isActive>false</isActive>
                <label>Institution Role3</label>
            </value>
            <value>
                <fullName>Institutional Delegate</fullName>
                <isActive>false</isActive>
                <label>Institutional Delegate</label>
            </value>
            <value>
                <fullName>Observer</fullName>
                <isActive>false</isActive>
                <label>Observer</label>
            </value>
            <value>
                <fullName>Patient</fullName>
                <isActive>false</isActive>
                <label>Patient</label>
            </value>
            <value>
                <fullName>President</fullName>
                <isActive>false</isActive>
                <label>President</label>
            </value>
            <value>
                <fullName>Representative</fullName>
                <isActive>false</isActive>
                <label>Representative</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Role__c/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/classes/PrimaryWorkplaceCheck_Test.cls
@IsTest
public with sharing class PrimaryWorkplaceCheck_Test {
    /*@TestSetup public static void setup(){
        RecordType rtAccDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Department'];
        List<Account> accs = new List<Account>();
        accs.add(new Account(Name = 'Test account 1', RecordTypeId = rtAccDepartment.Id));
        accs.add(new Account(Name = 'Test account 2', RecordTypeId = rtAccDepartment.Id));
        insert accs;
        Contact contact = new Contact(LastName = 'TestContact');
        insert contact;
    }
    @IsTest public static void PWCheckTestInsert(){
        Contact cont = [SELECT Id FROM Contact WHERE LastName = 'TestContact'];
        List<Account> accs = [SELECT Id, Name FROM Account];
        RecordType rtDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact_Role__c' AND DeveloperName = 'Department'];
        try {
            Contact_Role__c cr1 = new Contact_Role__c(Account__c = accs[0].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = true, RecordTypeId=rtDepartment.Id);
            insert cr1;
            System.assertEquals(1, [SELECT Id FROM Contact_Role__c WHERE Contact__c = :cont.Id].size());
            insert new Contact_Role__c(Account__c = accs[1].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = true, RecordTypeId=rtDepartment.Id);
        }catch (Exception e ){
            Boolean expectedExceptionThrown =  e.getMessage().contains(PrimaryWorkplaceCheckHelper.message);
            System.assertEquals(true, expectedExceptionThrown);
            System.assertEquals(1, [SELECT Id FROM Contact_Role__c WHERE Contact__c = :cont.Id AND is_primary_workplace__c=true].size());
        }
    }
    @IsTest public static void PWCheckTestUpdate(){
        Contact cont = [SELECT Id FROM Contact WHERE LastName = 'TestContact'];
        List<Account> accs = [SELECT Id, Name FROM Account];
        RecordType rtDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact_Role__c' AND DeveloperName = 'Department'];
        try {
            Contact_Role__c cr1 = new Contact_Role__c(Account__c = accs[0].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = true, RecordTypeId=rtDepartment.Id);
            insert cr1;
            Contact_Role__c cr2 = new Contact_Role__c(Account__c = accs[1].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = false, RecordTypeId=rtDepartment.Id);
            insert cr2;
            System.assertEquals(2, [SELECT Id FROM Contact_Role__c WHERE Contact__c = :cont.Id].size());
            cr2.is_primary_workplace__c = true;
            update cr2;
        }catch (Exception e ){
            Boolean expectedExceptionThrown =  e.getMessage().contains(PrimaryWorkplaceCheckHelper.message);
            System.assertEquals(true, expectedExceptionThrown);
            System.assertEquals(1, [SELECT Id FROM Contact_Role__c WHERE Contact__c = :cont.Id AND is_primary_workplace__c=true].size());
        }
    }
    @IsTest public static void PWCheckTestUndelete(){
        Contact cont = [SELECT Id FROM Contact WHERE LastName = 'TestContact'];
        List<Account> accs = [SELECT Id, Name FROM Account];
        RecordType rtDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact_Role__c' AND DeveloperName = 'Department'];
        try {
            Contact_Role__c cr1 = new Contact_Role__c(Account__c = accs[0].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = true, RecordTypeId=rtDepartment.Id);
            insert cr1;
            delete cr1;

            Contact_Role__c cr2 = new Contact_Role__c(Account__c = accs[1].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = false, RecordTypeId=rtDepartment.Id);
            insert cr2;
            cr2.is_primary_workplace__c = true;
            update cr2;
            delete cr2;

            undelete cr1;
            undelete cr2;
        }catch (Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains(PrimaryWorkplaceCheckHelper.message);
            System.assertEquals(true, expectedExceptionThrown);
            System.assertEquals(1, [SELECT Id FROM Contact_Role__c WHERE Contact__c = :cont.Id AND is_primary_workplace__c=true].size());
        }
    }
    @IsTest public static void uncheckedPWAndPWDeletedTest(){
        Contact cont = [SELECT Id FROM Contact WHERE LastName = 'TestContact'];
        List<Account> accs = [SELECT Id, Name FROM Account];
        RecordType rtDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact_Role__c' AND DeveloperName = 'Department'];
        update new Account(Id=accs[0].Id, ShippingCity='test', ShippingCountry='Belarus', ShippingPostalCode='12231', ShippingStreet='test');
        Contact_Role__c cr1 = new Contact_Role__c(Account__c = accs[0].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = true, RecordTypeId=rtDepartment.Id);
        insert cr1;
        cont.Mailing_address__c = 'Work Address';
        update cont;
        System.assertEquals('Work Address', [SELECT Id, Mailing_address__c FROM Contact WHERE LastName = 'TestContact'].Mailing_address__c);
        //uncheckedPW test
        cr1.is_primary_workplace__c = false;
        update cr1;
        Contact c = [SELECT Id, Mailing_address__c, Previous_Mailing_Address__c FROM Contact WHERE LastName = 'TestContact'];
        System.assertEquals(null, c.Mailing_address__c);
        System.assertEquals('Work Address', c.Previous_Mailing_Address__c);
        //checkedPW test
        cr1.is_primary_workplace__c = true;
        update cr1;
        System.assertEquals('Work Address', [SELECT Id, Mailing_address__c FROM Contact WHERE LastName = 'TestContact'].Mailing_address__c);
        //PWDeleted test
        delete cr1;
        c = [SELECT Id, Mailing_address__c, Previous_Mailing_Address__c FROM Contact WHERE LastName = 'TestContact'];
        System.assertEquals(null, c.Mailing_address__c);
        System.assertEquals('Work Address', c.Previous_Mailing_Address__c);
        //checkedPWInInsert test
        Contact_Role__c cr2 = new Contact_Role__c(Account__c = accs[0].Id, Contact__c = cont.Id, Role__c = 'Member', is_primary_workplace__c = true, RecordTypeId=rtDepartment.Id);
        insert cr2;
        c = [SELECT Id, Mailing_address__c, Previous_Mailing_Address__c FROM Contact WHERE LastName = 'TestContact'];
        System.assertEquals('Work Address', c.Mailing_address__c);
    }*/
}