force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Department Position</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Role__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) AND 3</booleanFilter>
        <errorMessage>Please select either a Hospital or a Department.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Hospital__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Positions</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Department Positions</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/is_primary_workplace__c.field-meta.xml
<CustomField>
    <fullName>is_primary_workplace__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Workplace</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Position/Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Editor</fullName>
            </value>
            <value>
                <fullName>Associate member society - Delegate</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>GroupAdmin</fullName>
            </value>
            <value>
                <fullName>Head</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Acting President</fullName>
                <isActive>false</isActive>
                <label>Acting President</label>
            </value>
            <value>
                <fullName>Advocate</fullName>
                <isActive>false</isActive>
                <label>Advocate</label>
            </value>
            <value>
                <fullName>Basic</fullName>
                <isActive>false</isActive>
                <label>Basic</label>
            </value>
            <value>
                <fullName>Co-Chair</fullName>
                <isActive>false</isActive>
                <label>Co-Chair</label>
            </value>
            <value>
                <fullName>Collaborator</fullName>
                <isActive>false</isActive>
                <label>Collaborator</label>
            </value>
            <value>
                <fullName>Coordinator</fullName>
                <isActive>false</isActive>
                <label>Coordinator</label>
            </value>
            <value>
                <fullName>Delegate</fullName>
                <isActive>false</isActive>
                <label>Delegate</label>
            </value>
            <value>
                <fullName>Director</fullName>
                <isActive>false</isActive>
                <label>Director</label>
            </value>
            <value>
                <fullName>Exectuive Director</fullName>
                <isActive>false</isActive>
                <label>Exectuive Director</label>
            </value>
            <value>
                <fullName>Executive</fullName>
                <isActive>false</isActive>
                <label>Executive</label>
            </value>
            <value>
                <fullName>Fellow</fullName>
                <isActive>false</isActive>
                <label>Fellow</label>
            </value>
            <value>
                <fullName>Industry - Main Contact</fullName>
                <isActive>false</isActive>
                <label>Industry - Main Contact</label>
            </value>
            <value>
                <fullName>Industry - NPO Contact</fullName>
                <isActive>false</isActive>
                <label>Industry - NPO Contact</label>
            </value>
            <value>
                <fullName>Industry - contact</fullName>
                <isActive>false</isActive>
                <label>Industry - contact</label>
            </value>
            <value>
                <fullName>Initiator</fullName>
                <isActive>false</isActive>
                <label>Initiator</label>
            </value>
            <value>
                <fullName>Institution Role1</fullName>
                <isActive>false</isActive>
                <label>Institution Role1</label>
            </value>
            <value>
                <fullName>Institution Role2</fullName>
                <isActive>false</isActive>
                <label>Institution Role2</label>
            </value>
            <value>
                <fullName>Institution Role3</fullName>
                <isActive>false</isActive>
                <label>Institution Role3</label>
            </value>
            <value>
                <fullName>Institutional Delegate</fullName>
                <isActive>false</isActive>
                <label>Institutional Delegate</label>
            </value>
            <value>
                <fullName>Observer</fullName>
                <isActive>false</isActive>
                <label>Observer</label>
            </value>
            <value>
                <fullName>Patient</fullName>
                <isActive>false</isActive>
                <label>Patient</label>
            </value>
            <value>
                <fullName>President</fullName>
                <isActive>false</isActive>
                <label>President</label>
            </value>
            <value>
                <fullName>Representative</fullName>
                <isActive>false</isActive>
                <label>Representative</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Role__c/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/classes/ContactMailingAddressValidation_Test.cls
@IsTest
public with sharing class ContactMailingAddressValidation_Test {
    /*@TestSetup public static void setup(){
        insert new Contact(LastName = 'Test');
        RecordType rtDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Department'];
        Account acc = new Account(Name = 'Test Account', RecordTypeId=rtDepartment.Id);
        insert acc;
    }
    @IsTest public static void addressCheckTestErrorWorkAddressEmptyDepartmentPositions(){
        Contact contact = [SELECT Id, Mailing_address__c FROM Contact WHERE LastName='Test'];
        Contact updatedContact = new Contact();
        try {
            contact.Mailing_address__c = 'Work Address';
            update contact;
        } catch (Exception e ){
            Boolean expectedExceptionThrown =  e.getMessage().contains(ContactMailingAddressValidationHelper.message2);
            System.assertEquals(true, expectedExceptionThrown);
            updatedContact = [SELECT Id, Mailing_address__c FROM Contact WHERE Id = :contact.Id];
            System.assertNotEquals('Work Address',updatedContact.Mailing_address__c);
        }
    }
    @IsTest public static void addressCheckTestErrorWorkAddressWithDepartmentPositionsNotSetPWP(){
        Contact contact = [SELECT Id, Mailing_address__c FROM Contact WHERE LastName='Test'];
        Contact updatedContact = new Contact();
        Account a = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        RecordType rtCRDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact_Role__c' AND DeveloperName = 'Department'];
        Contact_Role__c cr = new Contact_Role__c(Contact__c=contact.Id, Account__c=a.Id, Role__c='Head', RecordTypeId=rtCRDepartment.Id);
        insert cr;
        try {
            contact.Mailing_address__c = 'Work Address';
            update contact;
        } catch (Exception e ){
            System.debug(e.getMessage());
            Boolean expectedExceptionThrown =  e.getMessage().contains(ContactMailingAddressValidationHelper.message2);
            System.assertEquals(true, expectedExceptionThrown);
            updatedContact = [SELECT Id, Mailing_address__c FROM Contact WHERE Id = :contact.Id];
            System.assertNotEquals('Work Address',updatedContact.Mailing_address__c);
        }
    }
    @IsTest public static void addressCheckTestErrorWorkAddressWithDepartmentPositionsSetPWP(){
        Contact contact = [SELECT Id, Mailing_address__c FROM Contact WHERE LastName='Test'];
        Contact updatedContact = new Contact();
        Account a = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        RecordType rtCRDepartment = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact_Role__c' AND DeveloperName = 'Department'];
        Contact_Role__c cr = new Contact_Role__c(Contact__c=contact.Id, Account__c=a.Id, Role__c='Head', is_primary_workplace__c = true,  RecordTypeId=rtCRDepartment.Id);
        insert cr;
        try {
            contact.Mailing_address__c = 'Work Address';
            update contact;
        } catch (Exception e ){
            Boolean expectedExceptionThrown =  e.getMessage().contains(ContactMailingAddressValidationHelper.message1);
            System.assertEquals(true, expectedExceptionThrown);
            updatedContact = [SELECT Id, Mailing_address__c FROM Contact WHERE Id = :contact.Id];
            System.assertNotEquals('Work Address',updatedContact.Mailing_address__c);
        }
    }*/
}