force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Department Position</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Role__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) AND 3</booleanFilter>
        <errorMessage>Please select either a Hospital or a Department.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Hospital__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Positions</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Department Positions</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/is_primary_workplace__c.field-meta.xml
<CustomField>
    <fullName>is_primary_workplace__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Workplace</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactMailingAddressValidationHelper.cls
public with sharing class ContactMailingAddressValidationHelper {
    public static String message1 = 'You can\'t choose this address as mailing. It\'s not completely filled.';
    public static String message2 = 'You don\'t have Primary Workplace.';
    public static void addressCheck(List<Contact> contacts){
        List<Contact_Role__c> contactRoles = [SELECT Id, is_primary_workplace__c, Contact__c, Account__r.ShippingCountry, Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingPostalCode FROM Contact_Role__c WHERE Contact__c IN :contacts];
        for(Contact c : contacts){
            if(c.Mailing_address__c == 'Work Address'){
                List<Contact_Role__c> currentCR = new List<Contact_Role__c>();
                for(Contact_Role__c cr : contactRoles){
                    if(cr.Contact__c == c.Id){
                        currentCR.add(cr);
                    }
                }
                if(!currentCR.isEmpty()){
                    Contact_Role__c contRole;
                    for(Contact_Role__c ccr : currentCR){
                        if(ccr.is_primary_workplace__c){
                            contRole = ccr;
                        }
                    }
                    if(contRole !=null){
                        if(contRole.Account__r.ShippingCountry == null || contRole.Account__r.ShippingStreet  == null || contRole.Account__r.ShippingCity == null || contRole.Account__r.ShippingPostalCode == null){
                            c.addError(message1);

                        }
                    }else{
                        c.addError(message2);
                    }
                }else{
                    c.addError(message2);
                }
            }
        }
    }
    public static void saveLastMailingAddress(List<Contact> newCont, List<Contact>oldCont){
        for(Integer i = 0; i<newCont.size(); i++){
            if(oldCont[i].Mailing_address__c!=newCont[i].Mailing_address__c){
                newCont[i].Previous_Mailing_Address__c = oldCont[i].Mailing_address__c;
            }
        }
    }
}