force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/Event_Ticket__c.object-meta.xml
<CustomObject>
    <label>Event Ticket</label>
    <nameField>
        <displayFormat>ET-{0000000000}</displayFormat>
        <label>Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Ticket__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Tickets</relationshipLabel>
    <relationshipName>Event_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/fields/Participation__c.field-meta.xml
<CustomField>
    <fullName>Participation__c</fullName>
    <label>Participation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
                <default>true</default>
                <label>Onsite</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Event Tickets</relationshipLabel>
    <relationshipName>Event_Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Badge_Retrieval__c.field-meta.xml
<CustomField>
    <fullName>Badge_Retrieval__c</fullName>
    <label>Badge Retrieval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pre_print</fullName>
                <label>Pre-print by EAN</label>
            </value>
            <value>
                <fullName>onsite</fullName>
                <label>Onsite print</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Event_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Ticket</label>
    <referenceTo>Event_Ticket__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderInvoiceTableControllerTest.cls
@isTest
private with sharing class OrderInvoiceTableControllerTest {
    public OrderInvoiceTableControllerTest() {

    }

    @TestSetup
    static void Setup(){
        Contact testContact = new Contact(
            LastName = 'Test',
            Email = 'testmail@mail.com'
        );
        insert testContact;
        Event__c event = new Event__c(
            Name = 'Test event'
        );
        insert event;
        Ticket__c testTicket = new Ticket__c();
        insert testTicket;
        Event_Ticket__c testEventTicket = new Event_Ticket__c(
            Event_custom__c = event.Id,
            Participation__c = 'Onsite',
            Ticket__c = testTicket.Id
        );
        insert testEventTicket;
        Participant__c testParticipant = new Participant__c(
            Contact__c = testContact.Id,
            Event_custom__c = event.Id,
            Status__c = 'Registered',
            Badge_Retrieval__c = 'onsite',
            Event_Ticket__c = testEventTicket.Id
        );
        insert testParticipant;
        List<Order__c> orders = new List<Order__c>();
        for (Integer i = 1; i <= 5; i++) {
            Order__c order = new Order__c(
                Contact__c = testContact.Id,
                Status__c = 'Opened',
                Type__c = 'Event registration',
                Event_custom__c = event.Id
            );
            orders.add(order);
        }
        insert orders;
        List<Order_Item__c> orderItems = new List<Order_Item__c>();
        for (Order__c order : orders) {
            for (Integer i = 1; i <=4; i++) {
                Order_Item__c orderItem = new Order_Item__c(
                    Amount__c = i +0.5,
                    Quantity__c = 1,
                    Order_Custom__c = order.Id,
                    Event_Participation__c = testParticipant.Id
                );
                orderItems.add(orderItem);
            }
        }
        insert orderItems;
    }

    @isTest
    static void getOrderItemsTest(){
        List<Order__c> orders = [
            SELECT Id
            FROM Order__c
        ];
        for (Order__c order : orders){
            OrderInvoiceTableController OrderInvoiceTable = new OrderInvoiceTableController();
            OrderInvoiceTable.orderId = order.Id;
            List<OrderInvoiceTableController.OrderItemWrapper> wraperInstances = OrderInvoiceTable.getOrderItems();
            for (OrderInvoiceTableController.OrderItemWrapper wraperInstance : wraperInstances) {
                System.assert(wraperInstance.participantContactEmail == 'testmail@mail.com');
            }
        }
    }
}