force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End meeting time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/LogMeIn_Owner_Key__c.field-meta.xml
<CustomField>
    <fullName>LogMeIn_Owner_Key__c</fullName>
    <label>LogMeIn Owner Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/G2M.recordType-meta.xml
<RecordType>
    <fullName>G2M</fullName>
    <active>true</active>
    <label>G2M</label>
</RecordType>

force-app/main/default/objects/G2M_Settings_Obj__c/G2M_Settings_Obj__c.object-meta.xml
<CustomObject>
    <label>G2M Settings Obj</label>
    <nameField>
        <label>G2M Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>G2M Settings Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/G2M_Settings_Obj__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access_Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/G2M_Settings_Obj__c/fields/Account_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Key__c</fullName>
    <label>Account Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/G2M_Settings_Obj__c/fields/Admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email__c</fullName>
    <label>Admin Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/G2M_Settings_Obj__c/fields/Admin_Password__c.field-meta.xml
<CustomField>
    <fullName>Admin_Password__c</fullName>
    <label>Admin Password</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/G2M_Settings_Obj__c/fields/Consumer_Key__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Key__c</fullName>
    <label>Consumer Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/G2M_Settings_Obj__c/fields/Consumer_Secret__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Secret__c</fullName>
    <label>Consumer Secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/G2M_Settings_Obj__c/fields/Expires_in__c.field-meta.xml
<CustomField>
    <fullName>Expires_in__c</fullName>
    <label>Expires in</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CheckMeetingStartTimeTest.cls
@IsTest
public with sharing class CheckMeetingStartTimeTest {

    @TestSetup
    public static void setup() {
        Id meetingPTId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('G2M').getRecordTypeId();
        Event__c meeting1 = new Event__c(Name = 'Test Start Meeting 1', RecordTypeId = meetingPTId, Start_Time__c = Datetime.now().addMinutes(-5),
                Duration__c = 150, LogMeIn_Owner_Key__c = '0123456789', End_Time__c = Datetime.now().addMinutes(30));
        insert meeting1;

        Event__c meeting2 = new Event__c(Name = 'Test Stop Meeting 1', RecordTypeId = meetingPTId, Start_Time__c = Datetime.now().addMinutes(-45),
                Duration__c = 150, LogMeIn_Owner_Key__c = '0123456789', End_Time__c = Datetime.now().addMinutes(-15));
        insert meeting2;

        G2M_Settings_Obj__c g2ms = new G2M_Settings_Obj__c(
                Name = 'Sandbox',
                Account_Key__c = '4845706458463628293',
                Admin_Email__c = 'test@test.com',
                Admin_Password__c = '1234567',
                Consumer_Key__c = 'RP3r0b7UsFMBO5MVARg',
                Consumer_Secret__c = 'jdkjughvqeNEnefe4A',
                Expires_in__c = 3600,
                Access_Token__c = '0b7UsFMBO5MVARughvqeNEnef');
        insert g2ms;
    }

    @IsTest
    public static void scheduleStartTest() {
        Test.startTest();
//        CheckMeetingStartTime cmst = new CheckMeetingStartTime();
        Test.setMock(HttpCalloutMock.class, new GetSomethingLogMeInMock());
        CheckMeetingStartTime cmst = new CheckMeetingStartTime();
        String sch = '0 0 * * * ?';
        System.schedule('Test Start', sch, cmst);
        Test.stopTest();
    }

    @IsTest
    public static void setLicenseTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new GetSomethingLogMeInMock());
        CheckMeetingStartTimeQueueable.getAndSetLicenses('12345678','12345678');
        Test.stopTest();
    }

    @IsTest
    public static void deleteLicenseTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new GetSomethingLogMeInMock());
        CheckMeetingStartTimeQueueable.getAndDeleteLicenses('12345678','12345678');
        Test.stopTest();
    }

}