force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/Event_Ticket__c.object-meta.xml
<CustomObject>
    <label>Event Ticket</label>
    <nameField>
        <displayFormat>ET-{0000000000}</displayFormat>
        <label>Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Ticket__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Tickets</relationshipLabel>
    <relationshipName>Event_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/fields/Participation__c.field-meta.xml
<CustomField>
    <fullName>Participation__c</fullName>
    <label>Participation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
                <default>true</default>
                <label>Onsite</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Badge_Retrieval__c.field-meta.xml
<CustomField>
    <fullName>Badge_Retrieval__c</fullName>
    <label>Badge Retrieval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pre_print</fullName>
                <label>Pre-print by EAN</label>
            </value>
            <value>
                <fullName>onsite</fullName>
                <label>Onsite print</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Event_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Ticket</label>
    <referenceTo>Event_Ticket__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/QR_Code_needed__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QR Code needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QRcodeBatchTest.cls
@isTest
private without sharing class QRcodeBatchTest {
    public QRcodeBatchTest() {

    }

    @testSetup
    static void Setup() {
        Contact testContact = new Contact(
            LastName = 'Test Contact',
            Email = 'test@mail.com'
        );
        insert testContact;
        Event__c event = new Event__c(
            Name = 'Test event'
        );
        insert event;
        Event_Ticket__c testEventTicket = new Event_Ticket__c(
            Event_custom__c = event.Id,
            Participation__c = 'Onsite'
        );
        insert testEventTicket;
        Participant__c testParticipant = new Participant__c(
            Contact__c = testContact.Id,
            Event_custom__c = event.Id,
            QR_Code_needed__c = true,
            Status__c = 'Registered',
            Badge_Retrieval__c = 'onsite',
            Event_Ticket__c = testEventTicket.Id
        );
        insert testParticipant;
        // List<Participant__c> testParticipants = [
        //     SELECT Id, Name FROM Participant__c LIMIT 1
        // ];
        // ContentVersion testConVer = new ContentVersion(
        //     ContentLocation = 'S',
        //     PathOnClient = 'QR code ' + testParticipants[0].Name + '.png',
        //     Title = 'QR code ' + testParticipants[0].Name + '.png',
        //     VersionData = Blob.valueOf('Test Version Data')
        // );
        // insert testConVer;
        // List<ContentVersion> testConVers = [
        //             SELECT Id, ContentDocumentId, Title FROM ContentVersion WHERE Id = :testConVer.Id
        //             ];
        // ContentDocumentLink conDocLink = new ContentDocumentLink(
        //     LinkedEntityId = testParticipant.Id,
        //     ContentDocumentId = testConVers[0].ContentDocumentId,
        //     shareType = 'V',
        //     Visibility='AllUsers'
        // );
        // insert conDocLink;
    }
}