force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End meeting time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Event_Badge__c/Event_Badge__c.object-meta.xml
<CustomObject>
    <label>Event Badge</label>
    <nameField>
        <displayFormat>EB-{000000}</displayFormat>
        <label>Event Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Badge__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Badges</relationshipLabel>
    <relationshipName>Event_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Footer_Definitions__c.field-meta.xml
<CustomField>
    <fullName>Footer_Definitions__c</fullName>
    <label>Footer Definitions</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Associate Member</fullName>
            </value>
            <value>
                <fullName>Corresponding</fullName>
            </value>
            <value>
                <fullName>Day of the week</fullName>
            </value>
            <value>
                <fullName>EAN Head Office</fullName>
            </value>
            <value>
                <fullName>Exhibitor</fullName>
            </value>
            <value>
                <fullName>Fellow of the EAN</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Hostess</fullName>
            </value>
            <value>
                <fullName>Meeting only</fullName>
            </value>
            <value>
                <fullName>Non-Member</fullName>
            </value>
            <value>
                <fullName>Panel Management Group Member</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Resident &amp; Research Member</fullName>
            </value>
            <value>
                <fullName>Student Member</fullName>
            </value>
            <value>
                <fullName>Technical Staff</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
            <value>
                <fullName>ePoster presenter</fullName>
            </value>
            <value>
                <fullName>ePresentation presenter</fullName>
            </value>
            <value>
                <fullName>Tournament candidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Requested_For_Print_Or_Preview__c.field-meta.xml
<CustomField>
    <fullName>Requested_For_Print_Or_Preview__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requested For Print Or Preview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/recordTypes/Exhibitor_Badge.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor_Badge</fullName>
    <active>true</active>
    <description>(for known Participants of Industry Partners) Firstname Lastname City, Country (Official Address) (one additional badge)  -&gt; requirements are explained in: https://jira.towa-digital.com/browse/EANER-61</description>
    <label>Exhibitor Badge</label>
</RecordType>

force-app/main/default/classes/BadgeControllerTest.cls
@IsTest
public with sharing class BadgeControllerTest {
    @IsTest
    public static void getTemplateBadgeTest() {

        Id congressEventRT = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
        Event__c event = new Event__c(Name = 'Event1', RecordTypeId = congressEventRT, 
            Start_Time__c = System.now().addDays(10), End_Time__c = System.now().addDays(20), Status__c = 'Scheduled');
        insert event;

        Id exhibitorRTId = Schema.SObjectType.Event_Badge__c.getRecordTypeInfosByDeveloperName().get('Exhibitor_Badge').getRecordTypeId();
        Event_Badge__c badge = new Event_Badge__c(
            Event_custom__c = event.Id,
            Company__c = 'asd',
            Footer_Definitions__c = 'Non-Member',
            RecordTypeId = exhibitorRTId
        );

        insert badge;
        
        List<Map<String,Object>> badges = BadgeController.getTemplateBadge(new List<String>{badge.Id});
        System.assertEquals(1, badges.size());
        
        List<Event_Badge__c> bgs = [SELECT Id, Requested_For_Print_Or_Preview__c FROM Event_Badge__c WHERE Id =:badge.Id];
        
        System.assertEquals(1, bgs.size());        
        System.assertEquals(true, bgs[0].Requested_For_Print_Or_Preview__c);
        
        
    }
}