force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End meeting time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <label>Total amount</label>
    <summarizedField>Order_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Event registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Total_amount__c</fullName>
        <formula>(Quantity__c *  Amount__c) + Discount_Amount__c</formula>
        <label>Total amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Session_Participation__c.field-meta.xml
<CustomField>
    <fullName>Session_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Participation</label>
    <referenceTo>Session_Participation__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.Event_custom__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event_custom__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Payable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Participation__c/Session_Participation__c.object-meta.xml
<CustomObject>
    <label>Session Participation</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Session Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Participation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Session_Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Session_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Participants</relationshipLabel>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderHelperTest.cls
@isTest
public with sharing class OrderHelperTest {
    @isTest
    public static void createOrderTest() {
        Contact c = new Contact(LastName = 'test', Email = 'orderCreate@test.com', MailingStreet = 'TestStreet',
        MailingCity = 'TestCity', MailingPostalCode = '11111',
        MailingCountry = 'Germany');
        insert c;
        Id congressEventRT = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
        Event__c event = new Event__c(Name = 'Event1', RecordTypeId = congressEventRT, 
            Start_Time__c = System.now().addDays(10), End_Time__c = System.now().addDays(20), Status__c = 'Scheduled');
        insert event;

        Id congressParticipantRT = Schema.SObjectType.Participant__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
        Participant__c p = new Participant__c(Contact__c = c.Id, Event_custom__c = event.Id, 
            RecordTypeId = congressParticipantRT, Status__c = 'Registered');
        insert p;
        
        Session__c session = new Session__c(Name = 'Test Session', Event_custom__c = event.Id, Type__c = 'Payable');
        insert session;

        Session_Participation__c sessionParticipation = new Session_Participation__c(Contact__c = c.Id, Session__c = session.Id, Status__c = 'Pending');
        insert sessionParticipation;

        List<Order__c> ords = OrderHelper.createNewOrder(
            new Map<String,Object> {
                'participantsPrice' => new List<Map<String,Object>> {
                    new Map<String,Object> {
                        'participant' => p,
                        'price' => 50
                    }
                },
                'sessionParticipantPrice' => new Map<String,Object> {
                    sessionParticipation.Id => new Map<String,Object> {
                        'id' => session.Id, 
                        'price' => 5
                    }
                },
                'generalData' =>  new Map<String,Object> {
                    'contactId' => c.Id,
                	'eventId' => event.Id
                }
            }
        );
        System.assertEquals(1, ords.size());
        List<Order__c> secondAttemptOrds = OrderHelper.createNewOrder(
            new Map<String,Object> {
                'participantsPrice' => new List<Map<String,Object>> {
                    new Map<String,Object> {
                        'participant' => p,
                        'price' => 50
                    }
                },
                'sessionParticipantPrice' => new Map<String,Object> {
                    sessionParticipation.Id => new Map<String,Object> {
                        'id' => session.Id, 
                        'price' => 5
                    }
                },
                'generalData' =>  new Map<String,Object> {
                    'contactId' => c.Id,
                	'eventId' => event.Id
                }
            }
        );
        System.assertEquals(2, secondAttemptOrds.size());
        
        List<Order__c> orders = [
        	SELECT 
                Id, Total_amount__c, Status__c, Contact__c, Invoice_Number__c, 
                (SELECT Id, Amount__c, Total_amount__c FROM Order_Items__r) 
         	FROM Order__c WHERE Id =: ords[0].Id 
        ];
        
        System.assertEquals(55, orders[0].Total_amount__c);
        // System.assertEquals('EAN' + String.valueOf(Date.today().year()).right(2) + '-OC-000001', orders[0].Invoice_Number__c);
        //  https://jira.towa-digital.com/browse/EANER-19   use EAN21-F-#### (= Invoice Number) 
        System.assertEquals('EAN' + String.valueOf(Date.today().year()).right(2) + '-F-000001', orders[0].Invoice_Number__c);
        System.assertEquals(2, orders[0].Order_Items__r.size());

    }

    @isTest
    public static void cancelOrderTest() {

        Contact c = new Contact(LastName = 'test', Email = 'orderCreate@test.com', MailingStreet = 'TestStreet',
        MailingCity = 'TestCity', MailingPostalCode = '11111',
        MailingCountry = 'Germany');
        insert c;
    
        Order__c order = new Order__c( Contact__c = c.Id );
        insert order;
        Order_Item__c oI = new Order_Item__c( Order_Custom__c = order.Id, Amount__c =  50, Quantity__c = 1 );
    	insert oI;
        
        insert new Transaction__c(Order_Custom__c = order.Id, Status__c = 'Success', Amount__c = 50, Payment_Method__c='Bank Transfer');

        oI.Refund_Amount__c = 50;
        Map<String,Object> resMap = OrderHelper.cancelOrder(new Map<String,Object> {
            'id' => order.Id,
            'refundAmount' => 50,
            'oI' => new List<Order_Item__c>{ oI },
            'oIOrig' => new Map<String,Object> {
                oI.Id => 50
            }
        });

        System.assertEquals('Success', String.valueOf(resMap.get('status')));
        
        List<Transaction__c> trs = [SELECT Id, Amount__c, Status__c FROM Transaction__c WHERE Id =: String.valueOf(resMap.get('id'))];
        System.assertEquals(1, trs.size());
        System.assertEquals('Refund', trs[0].Status__c);
        System.assertEquals(-50, trs[0].Amount__c);

        List<Order__c> os = OrderHelper.getOrderInfo(order.Id);

        System.assertEquals(1, os.size());
        System.assertEquals(0, os[0].Paid_Amount__c);
        System.assertEquals(50, os[0].Total_amount__c);

        Map<String, Object> result = OrderHelper.getCancellationSettings(order.Id);
        System.assert(result.containsKey('displayContactColumn'));
        System.assert(Boolean.valueOf(result.get('displayContactColumn')) == false);

    }

    @isTest
    public static void getSoloParticipatCommunityButtonsInitDataTest() {
        Contact c = new Contact(LastName = 'test', Email = 'orderCreate@test.com', MailingStreet = 'TestStreet',
        MailingCity = 'TestCity', MailingPostalCode = '11111',
        MailingCountry = 'Germany');
        insert c;

		Datetime nowAdd10 = System.now().addDays(10);
		Datetime nowAdd20 = nowAdd10.addDays(10);

		Id congressEventRT = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
		Event__c event1 = new Event__c(Name = 'Event1', RecordTypeId = congressEventRT, Start_Time__c = nowAdd10, End_Time__c = nowAdd20, Status__c = 'Scheduled');
		insert event1;

		Id congressParticipantRT = Schema.SObjectType.Participant__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
		Participant__c p = new Participant__c(Contact__c = c.Id, Event_custom__c = event1.Id, RecordTypeId = congressParticipantRT, Status__c = 'Registered');
        insert p;
        
        Map<String, Object> resMap = OrderHelper.getSoloParticipatCommunityButtonsInitData(p.Id);

        System.assertEquals(false, Boolean.valueOf(resMap.get('displayCancelButton')));
        System.assertEquals(false, Boolean.valueOf(resMap.get('displayDoPaymentButton')));
        System.assertEquals(false, Boolean.valueOf(resMap.get('displayUpgradeButton')));
    }
    
}