force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QRcodeController_Test.cls
@isTest
private class QRcodeController_Test {
    public QRcodeController_Test() {

    }
    @testSetup
    static void Setup() {
        Contact testContact = new Contact(
            LastName = 'Test Contact',
            Email = 'test@mail.com'
        );
        insert testContact;
        Event__c event = new Event__c(
            Name = 'Test event'
        );
        insert event;
        Participant__c testParticipant = new Participant__c(
            Contact__c = testContact.Id,
            Event_custom__c = event.Id
        );
        insert testParticipant;
        List<Participant__c> testParticipants = [
            SELECT Id, Name FROM Participant__c LIMIT 1
        ];
        ContentVersion testConVer = new ContentVersion(
            ContentLocation = 'S',
            PathOnClient = 'QR code ' + testParticipants[0].Name + '.png',
            Title = 'QR code ' + testParticipants[0].Name + '.png',
            VersionData = Blob.valueOf('Test Version Data')
        );
        insert testConVer;
        List<ContentVersion> testConVers = [
                    SELECT Id, ContentDocumentId, Title FROM ContentVersion WHERE Id = :testConVer.Id
                    ];
        ContentDocumentLink conDocLink = new ContentDocumentLink(
            LinkedEntityId = testParticipant.Id,
            ContentDocumentId = testConVers[0].ContentDocumentId,
            shareType = 'V',
            Visibility='AllUsers'
        );
        insert conDocLink;
    }

    @isTest
	static void getUrlForBadgeRecordTest() {
        List<Participant__c> testParticipants = [
            SELECT Id, Name FROM Participant__c LIMIT 1
        ];
        QRcodeController controllerInstance = new QRcodeController();
        controllerInstance.participantId = testParticipants[0].Id;
        String contentDocumentName = 'QR code ' + testParticipants[0].Name + '.png';
        List<ContentDocumentLink> conDocLinks = [
                SELECT Id, ContentDocumentId
                FROM ContentDocumentLink
                WHERE LinkedEntityId = :testParticipants[0].Id
                AND ContentDocument.Title = :contentDocumentName
            ];
        List<ContentVersion> conVersions = [
                SELECT ContentBodyId, Id
                FROM ContentVersion
                WHERE ContentDocumentId = :conDocLinks[0].ContentDocumentId
                AND Title = :contentDocumentName
            ];
        String contentBodyId = conVersions[0].ContentBodyId;
        String conVersionId = conVersions[0].Id;
        System.debug(controllerInstance.externalUrl);
        System.assert(String.isNotBlank(controllerInstance.externalUrl));
        System.assert(controllerInstance.externalUrl.contains(URL.getSalesforceBaseUrl().toExternalForm().replace('.my.salesforce.com', '--c.documentforce.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId=').replace('.salesforce.com', '--c.documentforce.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId=')));
        System.assert(controllerInstance.externalUrl.contains(contentBodyId.left(15)));
        System.assert(controllerInstance.externalUrl.contains(conVersionId.left(15)));
    }
}