force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Early_Bird_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Early_Bird_Deadline__c</fullName>
    <label>Early Bird Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Registration_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Registration_Deadline__c</fullName>
    <label>Registration Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Event_Registration_Group__c/Event_Registration_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Group</label>
    <nameField>
        <label>Event Registration Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registration Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration_Group__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registration Groups</relationshipLabel>
    <relationshipName>Event_Registration_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration_Sub_Group__c/Event_Registration_Sub_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Sub Group</label>
    <nameField>
        <displayFormat>ERSG-{0000000000}</displayFormat>
        <label>Event Registration Sub Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registration Sub Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration_Sub_Group__c/fields/Event_Registration_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Group__c</fullName>
    <label>Event Registration Group</label>
    <referenceTo>Event_Registration_Group__c</referenceTo>
    <relationshipLabel>Event Registration Sub Groups</relationshipLabel>
    <relationshipName>Event_Registration_Sub_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/Event_Ticket__c.object-meta.xml
<CustomObject>
    <label>Event Ticket</label>
    <nameField>
        <displayFormat>ET-{0000000000}</displayFormat>
        <label>Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Ticket__c/fields/Early_bird_price__c.field-meta.xml
<CustomField>
    <fullName>Early_bird_price__c</fullName>
    <label>Early bird price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Tickets</relationshipLabel>
    <relationshipName>Event_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.IsAdditional__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Event Tickets</relationshipLabel>
    <relationshipName>Event_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Ticket__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Event Tickets</relationshipLabel>
    <relationshipName>Event_Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_Registration_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Sub_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to specify group during group registration on congress event</description>
    <label>Event Registration Sub Group</label>
    <referenceTo>Event_Registration_Sub_Group__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Registration_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Sub_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration Sub Group</label>
    <referenceTo>Event_Registration_Sub_Group__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Event_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Ticket</label>
    <referenceTo>Event_Ticket__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.Event_custom__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event_custom__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End__c.field-meta.xml
<CustomField>
    <fullName>Session_End__c</fullName>
    <label>Session End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start__c.field-meta.xml
<CustomField>
    <fullName>Session_Start__c</fullName>
    <label>Session Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Available_for_Countries__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Countries__c</fullName>
    <label>Available for Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Available_for_Memberships__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Memberships__c</fullName>
    <label>Available for Memberships</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Memberships</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Available_for_Personas__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Personas__c</fullName>
    <description>If there are special persona values then ticket available for only for these special personas, country and membership is not considered, otherwise it works and simple ticket.</description>
    <inlineHelpText>If there are special persona values then ticket available for only for these special personas, country and membership is not considered, otherwise it works and simple ticket.</inlineHelpText>
    <label>Available for Personas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Grant_Winner</fullName>
                <label>Grant Winner</label>
            </value>
            <value>
                <fullName>Invited_Person</fullName>
                <label>Invited Person</label>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Persona 1</fullName>
                <isActive>false</isActive>
                <label>Persona 1</label>
            </value>
            <value>
                <fullName>Persona 2</fullName>
                <isActive>false</isActive>
                <label>Persona 2</label>
            </value>
            <value>
                <fullName>Persona 3</fullName>
                <isActive>false</isActive>
                <label>Persona 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Is_Group_only__c.field-meta.xml
<CustomField>
    <fullName>Is_Group_only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Group only?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Is_IPR_only__c.field-meta.xml
<CustomField>
    <fullName>Is_IPR_only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is IPR only?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EventRegistrationController.cls
public without sharing class EventRegistrationController {
    @AuraEnabled
    public static Event__c getEvent(String eventId) {
        Event__c event = [
                SELECT Id, Name, Early_Bird_Deadline__c, Registration_Deadline__c
                FROM Event__c
                WHERE Id = :eventId
        ];
        return event;
    }

    @AuraEnabled
    public static Map<String, Object> getContactInfo() {
        Map<String, Object> result = new Map<String, Object>();
        User user = [SELECT Contact.Id FROM User WHERE Id = :UserInfo.getUserId()];
        Contact contact = [
                SELECT Id, Residency__c
                FROM Contact
                WHERE Id = :user.Contact.Id
        ];
        result.put('contact', contact);
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> insertEventParticipants( List<Participant__c> participants, Map<String,Object> generalData ) {
        Savepoint sp = Database.setSavepoint();
        try{
            System.debug('participants:: ' + participants);

            Contact undefinedContact = getUndefinedParticipant();
            Id congressRTId = Schema.SObjectType.Participant__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();

            if (undefinedContact == null) {
                return new Map<String, Object>{
                    'status' => 'Error',
                    'message' => 'Contact record Undefined Participant not found'
                };
            }

            for (Participant__c participant : participants) {
                participant.RecordTypeId = congressRTId;
                //todo event record type
                if (participant.Contact__c == null) {
                    participant.Contact__c = undefinedContact.Id;
                }
            }

            insert participants;

            //Create order
            List<Order__c> order = OrderHelper.createNewOrder( new Map<String,Object> {
				'generalData' => generalData,
                'participants' => participants
            });

            return new Map<String, Object>{
                'status' => 'Success',
                'message' => 'Success',
                'result' => order
            };
        }
        catch (Exception e) {
            Database.rollback(sp);
            return new Map<String, Object>{
                'status' => 'Error',
                'message' => e.getMessage()
            };
        }
    }

    public static Contact getUndefinedParticipant() {
        return [ SELECT Id FROM Contact WHERE FirstName = 'Undefined' AND LastName = 'Participant' LIMIT 1 ];
    }

    @AuraEnabled
    public static List<Event_Ticket__c> getEventTickets(String eventId) {
        List<Event_Ticket__c> tickets = [
                SELECT Id,
                        Price__c,
                        Early_bird_price__c,
                        Event_custom__c,
                        Ticket__c,
                        Ticket__r.Name,
                        Ticket__r.Available_for_Memberships__c,
                        Ticket__r.Available_for_Countries__c,
                        Ticket__r.Available_for_Personas__c,
                        Ticket__r.Is_Group_only__c,
                        Ticket__r.Is_IPR_only__c
                FROM Event_Ticket__c
                WHERE
                Event_custom__c = :eventId
                AND Ticket__c != NULL
                AND (Price__c != NULL
                OR Early_bird_price__c != NULL)
        ];

        return tickets;
    }

    @AuraEnabled public static String insertRegistrationGroup(String groupName, String groupLeaderId) {
      Event_Registration_Group__c ERGroup = new Event_Registration_Group__c();
      List<Event_Registration_Group__c> groups = [SELECT Id FROM Event_Registration_Group__c WHERE Name = :groupName AND Contact__c = :groupLeaderId LIMIT 1];

      if(groups.isEmpty()){
        ERGroup = new Event_Registration_Group__c(Name = groupName, Contact__c = groupLeaderId);
        insert ERGroup;
      } else {
        ERGroup = groups[0];
      }

      Event_Registration_Sub_Group__c subGroup = new Event_Registration_Sub_Group__c(Event_Registration_Group__c = ERGroup.Id);
      insert subGroup;
      return subGroup.Id;
    }

    @AuraEnabled
    public static List<Session__c> getExtraSessions(String eventId) {
        return [
                SELECT Id, Session_Start__c, Session_End__c, Registrations__c, Max_Participants__c,
                (
                        SELECT Id, Price__c, Early_bird_price__c, Event_custom__c, Ticket__c, Ticket__r.Name,
                                Ticket__r.Available_for_Memberships__c, Ticket__r.Available_for_Countries__c,
                                Session__r.Name, Session__r.Description__c, Session__r.Mutual_Exclusion__c,
                                Session__r.Max_Participants__c, Session__r.Registrations__c
                        FROM Event_Tickets__r
                        WHERE Ticket__c != NULL
                        AND (Price__c != NULL OR Early_bird_price__c != NULL)
                )
                FROM Session__c
                WHERE Event_custom__c = :eventId
                AND Type__c = 'Payable'
                AND Session_Start__c != NULL
                AND Session_End__c != NULL
                ORDER BY Session_Start__c ASC NULLS FIRST
        ];
    }

//    @AuraEnabled
//    public static List<Event_Ticket__c> getSessionsTickets(String eventId) {
//        List<Session__c> sessions = [
//                SELECT Id, Name, Session_Start__c, Session_End__c
//                FROM Session__c
//                WHERE Event_custom__c = :eventId
//                AND Session_Start__c != NULL
//                AND Session_End__c != NULL
//        ];
//
//        List<Event_Ticket__c> tickets = [
//                SELECT Id, Price__c, Early_bird_price__c, Event_custom__c, Ticket__c, Ticket__r.Name,
//                        Ticket__r.Available_for_Memberships__c, Ticket__r.Available_for_Countries__c
//                FROM Event_Ticket__c
//                WHERE Session__c IN :sessions
//                AND Ticket__c != NULL
//                AND (Price__c != NULL OR Early_bird_price__c != NULL)
//        ];
//
//        return tickets;
//    }
}