force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/App_Supported_By__c.field-meta.xml
<CustomField>
    <fullName>App_Supported_By__c</fullName>
    <label>App Supported By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Certificate_Link__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Link__c</fullName>
    <label>Certificate Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Congress_Postfix__c.field-meta.xml
<CustomField>
    <fullName>Congress_Postfix__c</fullName>
    <defaultValue>(&quot;th&quot;)</defaultValue>
    <label>Event Postfix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End meeting time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Number__c.field-meta.xml
<CustomField>
    <fullName>Event_Number__c</fullName>
    <label>Event Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Marketing_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Name__c</fullName>
    <defaultValue>(&quot;Congress of the European Academy of Neurolog&quot;)</defaultValue>
    <label>Marketing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Wi_Fi_Name__c.field-meta.xml
<CustomField>
    <fullName>Wi_Fi_Name__c</fullName>
    <label>Wi-Fi Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Wi_Fi_Supported_By__c.field-meta.xml
<CustomField>
    <fullName>Wi_Fi_Supported_By__c</fullName>
    <label>Wi-Fi Supported By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/Event_Badge__c.object-meta.xml
<CustomObject>
    <label>Event Badge</label>
    <nameField>
        <displayFormat>EB-{000000}</displayFormat>
        <label>Event Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Badge__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <label>Barcode</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Badges</relationshipLabel>
    <relationshipName>Event_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Event Badges</relationshipLabel>
    <relationshipName>Event_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Event_Participation_Role__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation_Role__c</fullName>
    <description>ePoster presenter, ePresentation presenter, Tournament candidate</description>
    <label>Event Participation Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Event_Registration_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration Group</label>
    <referenceTo>Event_Registration_Group__c</referenceTo>
    <relationshipLabel>Event Badges</relationshipLabel>
    <relationshipName>Event_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Footer_Definitions__c.field-meta.xml
<CustomField>
    <fullName>Footer_Definitions__c</fullName>
    <label>Footer Definitions</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Associate Member</fullName>
            </value>
            <value>
                <fullName>Corresponding</fullName>
            </value>
            <value>
                <fullName>Day of the week</fullName>
            </value>
            <value>
                <fullName>EAN Head Office</fullName>
            </value>
            <value>
                <fullName>Exhibitor</fullName>
            </value>
            <value>
                <fullName>Fellow of the EAN</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Hostess</fullName>
            </value>
            <value>
                <fullName>Meeting only</fullName>
            </value>
            <value>
                <fullName>Non-Member</fullName>
            </value>
            <value>
                <fullName>Panel Management Group Member</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Resident &amp; Research Member</fullName>
            </value>
            <value>
                <fullName>Student Member</fullName>
            </value>
            <value>
                <fullName>Technical Staff</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
            <value>
                <fullName>ePoster presenter</fullName>
            </value>
            <value>
                <fullName>ePresentation presenter</fullName>
            </value>
            <value>
                <fullName>Tournament candidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Group Name</description>
    <label>Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Label_type__c.field-meta.xml
<CustomField>
    <fullName>Label_type__c</fullName>
    <label>Label type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Danger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Non_Prescriber_Info__c.field-meta.xml
<CustomField>
    <fullName>Non_Prescriber_Info__c</fullName>
    <label>Non Prescriber Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/QR_code__c.field-meta.xml
<CustomField>
    <fullName>QR_code__c</fullName>
    <label>QR-code</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/QR_code_link__c.field-meta.xml
<CustomField>
    <fullName>QR_code_link__c</fullName>
    <description>Link to qr code wich will be displayed on badge. If QR_code__c is not blank the filed will contans it value.</description>
    <formula>IF( ISBLANK(QR_code__c) ,

 &quot;https://chart.googleapis.com/chart?chs=200x200&amp;cht=qr&amp;chl=&quot;
+LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))
+ Id, 

 QR_code__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR-code link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Badge__c/fields/Requested_For_Print_Or_Preview__c.field-meta.xml
<CustomField>
    <fullName>Requested_For_Print_Or_Preview__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requested For Print Or Preview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Registration_Group__c/Event_Registration_Group__c.object-meta.xml
<CustomObject>
    <label>Event Registration Group</label>
    <nameField>
        <label>Event Registration Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registration Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IF( TEXT(Status__c) =  &apos;Registered&apos;, IMAGE(&apos;https://chart.googleapis.com/chart?chs=200x200&amp;cht=qr&amp;chl=&apos;&amp; Id ,
&apos;Scan QR code to open record in mobile.&apos;), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.Event_custom__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event_custom__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/Session_Participation__c.object-meta.xml
<CustomObject>
    <label>Session Participation</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Session Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Participation__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Session_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The related events do not match.</errorMessage>
        <filterItems>
            <field>Participant__c.Event_custom__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Session Bookings</relationshipLabel>
    <relationshipName>Session_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Participants</relationshipLabel>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BadgeController.cls
public with sharing class BadgeController {
    public static final Set<String> LARGE_SIZE = new Set<String> { 'Exhibitor', 'Meeting only', 'Day of the week' };
   
    @AuraEnabled
    public static List<Map<String,Object>> getTemplateBadge(List<String> ids) {
        if (ids.size() == 0) { return new List<Map<String,Object>>(); }
        try {
            List<Map<String,Object>> badges = new List<Map<String,Object>>();
            // List<String> ids = new List<String>(); 
            // ids.add('a090E000006IxcNQAS');

            List<Event_Badge__c> upgradeEB = new List<Event_Badge__c>();

            System.debug('ids' + ids);
            List<Event_Badge__c> eBs = [
                SELECT 
                    Id, Event_Participation__c, FirstName__c, LastName__c, City__c, Country__c, Label__c, Label_type__c, Barcode__c, 
                    QR_code__c, Company__c, Footer_Definitions__c, Non_Prescriber_Info__c, Event_Participation_Role__c, 
                    Event_Registration_Group__c, Event_custom__c, Requested_For_Print_Or_Preview__c, QR_code_link__c,
                    Event_custom__r.Id,Event_custom__r.Name,Event_custom__r.City__c, Event_custom__r.Country__c, 
                    Event_custom__r.End_Time__c, Event_custom__r.Start_Time__c, Event_custom__r.Wi_Fi_Name__c, 
                    Event_custom__r.Wi_Fi_Supported_By__c,Event_custom__r.Certificate_Link__c,Event_custom__r.Congress_Postfix__c,
                    Event_custom__r.Event_Number__c, Event_custom__r.Marketing_Name__c, Event_custom__r.App_Supported_By__c
                FROM Event_Badge__c 
                WHERE id IN :ids
            ];

            System.debug('eBs' + eBs);
            if (eBs.size() == 0) {
                return new List<Map<String,Object>>();
            }

            Set<Id> partIds = new Set<Id>();

            for (Event_Badge__c eB: eBs) {
                if (!String.isBlank(eB.Event_Participation__c)) {
                    partIds.add(eB.Event_Participation__c);
                }
            }

            Map<String, Participant__c> sessionMap = new Map<String, Participant__c> (
                [
                    SELECT Id, (SELECT Id, Session__c, Session__r.Name FROM Session_Participations__r) 
                    FROM Participant__c where Id IN :partIds
                ]
            );

            for (Event_Badge__c eB: eBs) {
                upgradeEB.add( new Event_Badge__c(Id = eB.Id, Requested_For_Print_Or_Preview__c = true) );
                List<String> sessions = new List<String>();
                System.debug('sessionMap.containsKey(eB.Id) '  + sessionMap.containsKey(eB.Id));
                if (sessionMap.containsKey(eB.Id)) {
                    Participant__c part = sessionMap.get(eB.Id);
                    for (Session_Participation__c sP : part.Session_Participations__r) {
                        if (!String.isBlank(sP.Session__c)) {
                            sessions.add(sP.Session__r.Name);
                        }
                    }
                }
                
                String dates = eB.Event_custom__r.Start_Time__c.format('MMMM dd') + ' - ' + eB.Event_custom__r.End_Time__c.format('MMMM dd');
                List<Map<String, Object>> footers = new List<Map<String, Object>>();
                
                if (!String.isBlank(eB.Footer_Definitions__c)) {
                    for (String s : eB.Footer_Definitions__c.split(';')) {
                        String lg = LARGE_SIZE.contains(s) ? 'lg' : '';
                        footers.add(new Map<String, Object> {
                            'label' => s, 
                            'size' => lg
                        });
                    } 
                }
                
                badges.add( new Map<String,Object> {
                    'cityEvent' => eB.Event_custom__r.City__c,
                    'bookedTickets' => sessions,
                    'wiFiName' => eB.Event_custom__r.Wi_Fi_Name__c,
                    'wiFiSupportedBy' => eB.Event_custom__r.Wi_Fi_Supported_By__c,
                    'appSupportedBy' => eB.Event_custom__r.App_Supported_By__c,
                    'certificateLink' => eB.Event_custom__r.Certificate_Link__c,
                    'year' => eB.Event_custom__r.Start_Time__c.year(),
                    'count' => eB.Event_custom__r.Event_Number__c,                
                    'countPostfix' => eB.Event_custom__r.Congress_Postfix__c,
                    'date' => dates,
                    'name' => eB.Event_custom__r.Marketing_Name__c,
                    'company' => eB.Company__c,
                    'firstName' => eB.FirstName__c,
                    'lastName' => eB.LastName__c,
                    'city' => eB.City__c,
                    'country' => eB.Country__c,
                    'label' => eB.Label__c,
                    'labelType' => eB.Label_type__c,
                    'barcode' => eB.Barcode__c,
                    'qrcode' => eB.QR_code_link__c,
                    'footer' => footers
                });
                
            }
            update upgradeEB;

            return badges;
        } 
        catch(Exception e) {
            return new List<Map<String,Object>>();
        }
    }

    @AuraEnabled
    public static String getUrl(){
        return Url.getOrgDomainUrl().toExternalForm();
    }
}