force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Max_Participants__c.field-meta.xml
<CustomField>
    <fullName>Max_Participants__c</fullName>
    <label>Max Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Persona__c/Event_Persona__c.object-meta.xml
<CustomObject>
    <label>Event Persona</label>
    <nameField>
        <displayFormat>EP-{0000000000}</displayFormat>
        <label>Event Persona Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Personas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Persona__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Personas</relationshipLabel>
    <relationshipName>Event_Personas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Persona__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Personas</relationshipLabel>
    <relationshipName>Event_Personas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Persona__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>confirmed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>created</fullName>
                <default>true</default>
                <label>created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lecture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_Persona__c.field-meta.xml
<CustomField>
    <fullName>Event_Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Says that this participant is event persona on selected event</description>
    <inlineHelpText>Says that this participant is event persona on selected event</inlineHelpText>
    <label>Event Persona</label>
    <referenceTo>Event_Persona__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Event_Participations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Lecture__c.field-meta.xml
<CustomField>
    <fullName>Lecture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lecture</label>
    <referenceTo>Lecture__c</referenceTo>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.Event_custom__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event_custom__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End__c.field-meta.xml
<CustomField>
    <fullName>Session_End__c</fullName>
    <label>Session End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start__c.field-meta.xml
<CustomField>
    <fullName>Session_Start__c</fullName>
    <label>Session Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Career development session</fullName>
            </value>
            <value>
                <fullName>Case-based workshop</fullName>
            </value>
            <value>
                <fullName>Controversy</fullName>
            </value>
            <value>
                <fullName>Focused Workshop</fullName>
            </value>
            <value>
                <fullName>Hands-on Course</fullName>
            </value>
            <value>
                <fullName>Interactive Session</fullName>
            </value>
            <value>
                <fullName>Plenary Sysmposium</fullName>
            </value>
            <value>
                <fullName>Special Session</fullName>
            </value>
            <value>
                <fullName>Topical Symposium</fullName>
            </value>
            <value>
                <fullName>ePoster</fullName>
            </value>
            <value>
                <fullName>Oral Presentation</fullName>
            </value>
            <value>
                <fullName>Symposia</fullName>
            </value>
            <value>
                <fullName>Teaching Course</fullName>
            </value>
            <value>
                <fullName>Scientific theatre</fullName>
            </value>
            <value>
                <fullName>ePresentation</fullName>
            </value>
            <value>
                <fullName>Forum Programmes</fullName>
            </value>
            <value>
                <fullName>Networking Session</fullName>
            </value>
            <value>
                <fullName>3-Day Satellite Session</fullName>
                <isActive>false</isActive>
                <label>3-Day Satellite Session</label>
            </value>
            <value>
                <fullName>3-Days Satellite Session</fullName>
                <isActive>false</isActive>
                <label>3-Days Satellite Session</label>
            </value>
            <value>
                <fullName>Brain Challenge</fullName>
                <isActive>false</isActive>
                <label>Brain Challenge</label>
            </value>
            <value>
                <fullName>Controversy Session</fullName>
                <isActive>false</isActive>
                <label>Controversy Session</label>
            </value>
            <value>
                <fullName>Early bird satellite session</fullName>
                <isActive>false</isActive>
                <label>Early bird satellite session</label>
            </value>
            <value>
                <fullName>Grand Round session</fullName>
                <isActive>false</isActive>
                <label>Grand Round session</label>
            </value>
            <value>
                <fullName>Hands-on-course</fullName>
                <isActive>false</isActive>
                <label>Hands-on-course</label>
            </value>
            <value>
                <fullName>Networking</fullName>
                <isActive>false</isActive>
                <label>Networking</label>
            </value>
            <value>
                <fullName>Oral Session</fullName>
                <isActive>false</isActive>
                <label>Oral Session</label>
            </value>
            <value>
                <fullName>Plenary Symposium</fullName>
                <isActive>false</isActive>
                <label>Plenary Symposium</label>
            </value>
            <value>
                <fullName>Poster Session</fullName>
                <isActive>false</isActive>
                <label>Poster Session</label>
            </value>
            <value>
                <fullName>Satellite Symposium</fullName>
                <isActive>false</isActive>
                <label>Satellite Symposium</label>
            </value>
            <value>
                <fullName>Symposium</fullName>
                <isActive>false</isActive>
                <label>Symposium</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Payable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaking Engagement</label>
    <nameField>
        <displayFormat>SPR-{0000}</displayFormat>
        <label>Speaking Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaking Engagements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Lecture__c.field-meta.xml
<CustomField>
    <fullName>Lecture__c</fullName>
    <label>Lecture</label>
    <referenceTo>Lecture__c</referenceTo>
    <relationshipName>Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <formula>TEXT(Lecture__r.Session__r.Session_Type__c)</formula>
    <label>Session Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParticipantTriggerHelperTest.cls
@IsTest
public with sharing class ParticipantTriggerHelperTest {
    @TestSetup
    public static void setup(){
        List<Event__c> events = new List<Event__c>();

        for(Integer i = 0; i < 3; i++){
            events.add(new Event__c(Name = 'Event '+i));
        }

        insert events;

        List<Session__c> extraSessions = new List<Session__c>();

        for(Event__c event : events){
            extraSessions.add(new Session__c(Name = 'Session Extra 1', Type__c = 'Payable', Session_Type__c = 'Special Session',
                    Max_Participants__c = 50, Event_custom__c = event.Id, Session_Start__c = Datetime.now(),
                    Session_End__c = Datetime.now().addDays(1)));
        }

        insert extraSessions;

        Contact contact = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'info@test.com');
        insert contact;
    }
    @IsTest
    public static void updateEventPersonas_insert_undeleteTest(){
        Contact contact = [SELECT Id FROM Contact WHERE Email = 'info@test.com' LIMIT 1];
        Event__c event = [SELECT Id FROM Event__c LIMIT 1];
        List<Session__c> sessions = [SELECT Id FROM Session__c];

        List<RecordType> eventPersonaRTs = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Event_Persona__c'];
        Event_Persona__c ep = new Event_Persona__c(Contact__c = contact.Id, Event_custom__c = event.Id, RecordTypeId = eventPersonaRTs[0].Id);
        insert ep;

        Lecture__c lecture = new Lecture__c(Event_custom__c = event.Id, Session__c = sessions[0].Id);
        insert lecture;

        Speaker__c speaker = new Speaker__c(Lecture__c = lecture.Id, Contact__c = contact.Id);
        insert speaker;

        Participant__c participant = new Participant__c(Contact__c = contact.Id, Event_custom__c = event.Id,
                Status__c = 'Pending', Event_Persona__c = ep.Id, Lecture_Presentation__c = speaker.Id);
        insert participant;

        System.assertEquals('invited', [SELECT Id, Status__c FROM Speaker__c WHERE Id = :speaker.Id].Status__c);
        System.assertEquals('invited', [SELECT Id, Status__c FROM Event_Persona__c WHERE Id = :ep.Id].Status__c);

        participant.Status__c = 'Registered';
        update participant;

        System.assertEquals('confirmed', [SELECT Id, Status__c FROM Speaker__c WHERE Id = :speaker.Id].Status__c);
        System.assertEquals('confirmed', [SELECT Id, Status__c FROM Event_Persona__c WHERE Id = :ep.Id].Status__c);

        participant.Event_Persona__c = null;
        participant.Lecture_Presentation__c = null;
        update participant;

        System.assertEquals(null, [SELECT Id, Status__c FROM Speaker__c WHERE Id = :speaker.Id].Status__c);
        System.assertEquals(null, [SELECT Id, Status__c FROM Event_Persona__c WHERE Id = :ep.Id].Status__c);
    }
}