force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Email__c.field-meta.xml
<CustomField>
    <fullName>Participant_Email__c</fullName>
    <label>Participant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EAN_EmailControllerTest.cls
@isTest
private with sharing class EAN_EmailControllerTest {

    @testSetup static void setup() {
        List<Event__c> eventsCustom = new List<Event__c>();
        for (Integer i=1; i<=2; i++){
            Event__c eventCustom = new Event__c();
            eventCustom.Name = 'Test ivent ' + i;
            eventsCustom.add(eventCustom);
        }
        insert eventsCustom;
        
        List<Contact> contacts = new List<Contact>();
        for (Integer i=1; i<=8; i++){
            Contact contact = new Contact();
            contact.LastName = 'Test contact ' + i;
            contacts.add(contact);
        }
        insert contacts;
        List<Participant__c> participants = new List<Participant__c>();
        Integer i = 1;
        for (Contact contact : contacts){
            Participant__c participant = new Participant__c();
            participant.Event_custom__c = eventsCustom[Math.round(Math.random())].Id;
            participant.Participant_Email__c = 'test'+i+'@test.ru';
            participant.Contact__c = contact.Id;
            participants.add(participant);
            i = i +1;
        }
        insert participants;
    }
    @isTest
    static void sendEmailTest(){
        Map<String, Object> emailOptionsMap = new Map<String, Object>();
        List<String> recordIds = new List<String>();
        List<Participant__c> records = [SELECT Id FROM Participant__c];
        for (Participant__c record : records){
            recordIds.add(record.Id);
        }
        emailOptionsMap.put('recordIds', recordIds);
        emailOptionsMap.put('objectApiName', 'Participant__c');
        emailOptionsMap.put('emailFieldApiName', 'Participant_Email__c');
        emailOptionsMap.put('emailTemplateDevName', 'EANSuccessfullRegisrationEmailTemplate');
        Test.startTest();
        List<Participant__c> unusedRecords = EAN_EmailController.sendEmail(emailOptionsMap);
        Test.stopTest();
        System.assert(unusedRecords.size() == 0);
    }
}