force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Payments &amp; Invoices</relationshipLabel>
    <relationshipName>Payments_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <label>Total amount</label>
    <summarizedField>Order_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/VAT_Amount__c.field-meta.xml
<CustomField>
    <fullName>VAT_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>VAT Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Total_amount__c</fullName>
        <formula>(Quantity__c *  Amount__c) + Discount_Amount__c</formula>
        <label>Total amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF(NOT(ISBLANK(Event_Participation__c)), Event_Participation__r.Event_Ticket__r.Ticket__r.Name,
IF(NOT(ISBLANK(Session_Participation__c)), Session_Participation__r.Session__r.Name,
IF(NOT(ISBLANK(Membership__c)), Membership__r.Name,
IF(NOT(ISBLANK(Product__c)), Product__r.Name , &apos;&apos;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderInvoiceTableController.cls
public with sharing class OrderInvoiceTableController {
	public OrderInvoiceTableController() {
	}
	public String orderId { get; set; }
	public Integer orderItemsSize { get; set; }
	public Decimal vatAmount { get; set; }
	public Decimal vatValue { get; set; }
	public Decimal orderTotal { get; set; }
	public Decimal orderTotalAmount { get; set; }

	public List<OrderItemWrapper> getOrderItems() {
		orderTotalAmount = 0;
        vatAmount = 0;
		List<Order_Item__c> orderItems = [
			SELECT Id, Name, Name__c, Amount__c , Quantity__c, Total_amount__c, Event_Participation__r.Contact__r.Id,
				Order_Custom__c, Order_Custom__r.Event_custom__r.VAT_Amount__c, Event_Participation__r.Contact__r.FirstName,
				Event_Participation__r.Contact__r.LastName, Event_Participation__r.Contact__r.Email,
				Order_Custom__r.Contact__r.FirstName, Order_Custom__r.Contact__r.LastName,
				Order_Custom__r.Contact__r.Email 
			FROM Order_Item__c 
			WHERE Order_Custom__c = :orderId
		];
		this.orderItemsSize = orderItems.size();
		List<OrderItemWrapper> orderIs = new List<OrderItemWrapper>();
		if (orderItems.size() > 0) {
			vatValue = orderItems[0].Order_Custom__r.Event_custom__r.VAT_Amount__c != null ? orderItems[0].Order_Custom__r.Event_custom__r.VAT_Amount__c : 0;
			 
			for (Order_Item__c oI : orderItems) {
				OrderItemWrapper oIW = new OrderItemWrapper();
				oIW.id = oI.Id;
				oIW.name = oI.Name__c;
				oIW.amount = oI.Amount__c;
				oIW.totalAmount  = (oI.Total_amount__c - (oI.Total_amount__c * vatValue / 100)).setScale(2);
				oIW.quantity = oI.Quantity__c;
				oIW.contactId = oI.Order_Custom__r.Contact__r.Id;
				oIW.firstName = oI.Order_Custom__r.Contact__r.FirstName;
				oIW.lastName = oI.Order_Custom__r.Contact__r.LastName;
				orderIs.add( oIW );
				orderTotalAmount += oI.Total_amount__c;
			}
			if (orderTotalAmount > 0 && vatValue > 0) {
				vatAmount = (orderTotalAmount * vatValue / 100).setScale(2);
				orderTotal = (orderTotalAmount - vatAmount).setScale(2);                
			}
		}
		return orderIs;
	}

	public class OrderItemWrapper {
		public String id { get; set; }
		public String name { get; set; }
		public Decimal amount { get; set; }
		public Decimal totalAmount { get; set; }
		public Decimal quantity { get; set; }
		public String contactId { get; set; }
		public String firstName { get; set; }
		public String lastName { get; set; }
	}
}

 