force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End meeting time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Visa_Letter__c.field-meta.xml
<CustomField>
    <fullName>Visa_Letter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visa Letter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/recordTypes/Congress.recordType-meta.xml
<RecordType>
    <fullName>Congress</fullName>
    <active>true</active>
    <label>Congress</label>
</RecordType>

force-app/main/default/objects/Visa_Letter__c/Visa_Letter__c.object-meta.xml
<CustomObject>
    <label>Visa Letter</label>
    <nameField>
        <displayFormat>V-{00000}</displayFormat>
        <label>Visa Letter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visa Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visa_Letter__c/fields/Date_of_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Expiry__c</fullName>
    <label>Date of Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Date_of_Issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue__c</fullName>
    <label>Date of Issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visa_Letter__c/fields/Event_Participation__c.field-meta.xml
<CustomField>
    <fullName>Event_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Participation</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Visa Letter</relationshipLabel>
    <relationshipName>Visa_Letter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisaLetterControllerTest.cls
@isTest
public with sharing class VisaLetterControllerTest {
    @isTest
    public static void visaLetterTest() {
        Contact c = new Contact(LastName = 'test', Email = 'testEm@test.com', MailingStreet = 'TestStreet',
        MailingCity = 'TestCity', MailingPostalCode = '11111',
        MailingCountry = 'Germany');
        insert c;

        Id congressEventRT = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
        Event__c event = new Event__c(Name = 'Event1', RecordTypeId = congressEventRT, 
            Start_Time__c = System.now().addDays(10), End_Time__c = System.now().addDays(20), Status__c = 'Scheduled');
        insert event;

        Id congressParticipantRT = Schema.SObjectType.Participant__c.getRecordTypeInfosByDeveloperName().get('Congress').getRecordTypeId();
        Participant__c p = new Participant__c(Contact__c = c.Id, Event_custom__c = event.Id, 
            RecordTypeId = congressParticipantRT, Status__c = 'Registered');
        insert p;
        
        Visa_Letter__c vL = new Visa_Letter__c(
            Event_Participation__c =p.Id, Date_of_Birth__c = Date.Today(), Date_of_Issue__c = Date.Today(), Date_of_Expiry__c= Date.Today()
        );
        insert vL;
        PageReference pref = Page.VisaLetter;
        pref.getParameters().put('id', vL.Id);
        Test.setCurrentPage(pref);
        VisaLetterController controller = new VisaLetterController();
        System.assertEquals(1, controller.visaLetters.size()); 
    }
   
}