force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event custom</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Event_custom__c.field-meta.xml
<CustomField>
    <fullName>Event_custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Congress</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>G2M</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QRcodeControllerTest.cls
@IsTest
public with sharing class QRcodeControllerTest {

    @IsTest
    public static void QRcodeControllerTest(){
        Event__c event = new Event__c(Name = 'Test Event');
        insert event;

        Contact contact = new Contact(FirstName = 'Name', LastName = 'Name');
        insert  contact;

        Participant__c part = new Participant__c(Contact__c = contact.Id, Event_custom__c = event.Id);
        insert part;
        part = [SELECT Id, Name, Contact__c, Event_custom__c FROM Participant__c WHERE Id = :part.Id];

        ContentVersion cv=new ContentVersion();
        cv.Title = 'QR code ' + part.Name + '.png';
        cv.PathOnClient = 'QR code ' + part.Name + '.png';
        cv.VersionData = Blob.valueOf('Test');
        insert cv;

        cv = [SELECT Id, ContentDocumentId, ContentDocument.Title FROM ContentVersion WHERE  Id = :cv.Id];

        ContentDocumentLink contentLink = new ContentDocumentLink();
        contentLink.LinkedEntityId = part.Id;
        contentLink.ShareType = 'I';
        contentLink.LinkedEntityId = part.Id;
        contentLink.ContentDocumentId = cv.ContentDocumentId;
        contentLink.Visibility = 'AllUsers';
        insert contentLink;


        QRcodeController qr = new QRcodeController();
        qr.participantId = part.Id;
        System.assert(qr.externalUrl.contains(String.valueOf(cv.Id).left(15)));

    }
}