force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <label>Total amount</label>
    <summarizedField>Order_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Total_amount__c</fullName>
        <formula>(Quantity__c *  Amount__c) + Discount_Amount__c</formula>
        <label>Total amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Refund_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Refund_Invoice__c</fullName>
    <label>Refund Invoice</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Session_Participation__c.field-meta.xml
<CustomField>
    <fullName>Session_Participation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Participation</label>
    <referenceTo>Session_Participation__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participations</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FW Convenor</fullName>
            </value>
            <value>
                <fullName>FW speaker</fullName>
            </value>
            <value>
                <fullName>Group Participant</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Head</fullName>
            </value>
            <value>
                <fullName>Investigator Award Winner</fullName>
            </value>
            <value>
                <fullName>MT convenor</fullName>
            </value>
            <value>
                <fullName>MT speaker</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Panel Member (Individual)</fullName>
            </value>
            <value>
                <fullName>Panel Member (Institution)</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
                <default>true</default>
                <label>Participant</label>
            </value>
            <value>
                <fullName>Poster session /sc chair</fullName>
            </value>
            <value>
                <fullName>Special session speaker</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Sps convenor</fullName>
            </value>
            <value>
                <fullName>Sps speaker</fullName>
            </value>
            <value>
                <fullName>Stellar Lecture Speaker</fullName>
            </value>
            <value>
                <fullName>Tc convenor</fullName>
            </value>
            <value>
                <fullName>Tc speaker</fullName>
            </value>
            <value>
                <fullName>Tournament Participant</fullName>
            </value>
            <value>
                <fullName>Tournament Runner-up - Basic</fullName>
            </value>
            <value>
                <fullName>Tournament Runner-up - Clinical</fullName>
            </value>
            <value>
                <fullName>Tournament Winner</fullName>
            </value>
            <value>
                <fullName>Tournament Winner - Basic</fullName>
            </value>
            <value>
                <fullName>Tournament Winner - Clinical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Status 1</fullName>
                <isActive>false</isActive>
                <label>Status 1</label>
            </value>
            <value>
                <fullName>Status 2</fullName>
                <isActive>false</isActive>
                <label>Status 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Participation__c/Session_Participation__c.object-meta.xml
<CustomObject>
    <label>Session Participation</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Session Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Participation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Participations</relationshipLabel>
    <relationshipName>Session_Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Participation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RefundInvoiceTableController.cls
public with sharing class RefundInvoiceTableController {
    public RefundInvoiceTableController() {
    }
    public String orderId { get; set; }
    public String JSONBody { get; set; }
    public String orderNum { get; set; }
    
    public Decimal orderTotalAmount { get{
        return orderTotalAmount.setScale(2);
    } set; }
    public Decimal orderSubTotal { get{
        return orderSubTotal.setScale(2);
    } set; }
    public Decimal orderVATs { get{
        return orderVATs.setScale(2);
    } set; }
    public Decimal vatValue { get{
        return vatValue.setScale(2);
    } set; }


    public List<Order_Item__c> getOrderItems(){
        List<Order_Item__c> orderIs = new List<Order_Item__c>();        
        vatValue = 0;
        orderVATs = 0;
        orderSubTotal = 0;
        orderTotalAmount = 0;
        Map<String,Object> oIOrig = (Map<String,Object>)JSON.deserializeUntyped(JSONBody);

        List<Transaction__c> trs = [
                SELECT Id, Order_Custom__c, Status__c, Refund_Invoice__c, CreatedDate  
                FROM Transaction__c 
                WHERE Order_Custom__c = :orderId AND Status__c = 'Refund' ORDER BY CreatedDate DESC
            ];
        if (trs.size() > 0) {
            orderNum = trs[0].Refund_Invoice__c;
        }
        
        List<Order_Item__c> oIs = [
            SELECT 
                Id, Name, Total_amount__c, Refund_Amount__c, Order_Custom__r.Contact__r.Id, Order_Custom__r.Contact__r.FirstName, 
                Order_Custom__r.Contact__r.LastName, Session_Participation__r.Role__c, Session_Participation__r.Event_Ticket__r.Ticket__r.Name,
                Event_Participation__r.Event_Ticket__r.Ticket__r.Name, Session_Participation__r.Session__r.Name, Order_Custom__r.VATamount__c,
                    Order_Custom__r.Event_custom__r.VAT_Amount__c
            FROM Order_Item__c 
            WHERE Order_Custom__c = :orderId
		];
        
        vatValue = !oIs.isEmpty() ? oIs[0].Order_Custom__r.Event_custom__r.VAT_Amount__c : 0;
        
        for (Integer i = (oIs.size()-1) ; i>= 0 ; i--){
			if (oIOrig.containsKey(oIs[i].Id)) {
                Decimal refPrice = ((Decimal)oIOrig.get(oIs[i].Id)).setScale(2);
                oIs[i].Refund_Amount__c =  (refPrice / (1 + vatValue / 100)).setScale(2);
                orderTotalAmount += refPrice;
            } else {
				oIs.remove(i);
			}
        }
        if (!oIs.isEmpty()) {
            orderVATs = orderTotalAmount - (orderTotalAmount / (1 + vatValue / 100)).setScale(2); 
            orderSubTotal = orderTotalAmount - orderVATs;        
        } 
       
        return oIs;
    }
}