force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Custom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/JournalOrderConfirmationController.cls
public class JournalOrderConfirmationController {
    public Id contactId {get; set;}
    public Order__c order {get{
        return order.Id == null?new Order__c():[SELECT Id, Name, Contact__r.Salutation, Contact__r.FirstName, Contact__r.LastName, Contact__r.Title FROM Order__c WHERE Id = :order.Id];
    } set;}
    public List<String> mailingAddress {get{
        List<Contact> contact = [SELECT Id, Selected_Mailing_Address__c FROM Contact WHERE Id = :order.Contact__c];
        return contact.isEmpty()?new List<String>{'none'}:contact[0].Selected_Mailing_Address__c.split('<br>');
    } set;}
    public String myEANProfileUrl {get{
        if(Test.isRunningTest()) return 'link.com';
        Network myNetwork = [SELECT Id FROM Network WHERE Name ='ean'];
        ConnectApi.Community myCommunity = ConnectApi.Communities.getCommunity(myNetwork.Id);
        return myCommunity.siteUrl + '/s/profile/' + UserInfo.getUserId();
    } set;}
}