force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Payment &amp; Invoice</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Success</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <label>Total amount</label>
    <summarizedField>Order_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order_Custom__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_amount_Gros__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Gros__c</fullName>
    <formula>Total_amount__c + VAT_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Gros</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Total_amount__c</fullName>
        <formula>(Quantity__c *  Amount__c) + Discount_Amount__c</formula>
        <label>Total amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF(NOT(ISBLANK(Event_Participation__c)), Event_Participation__r.Event_Ticket__r.Ticket__r.Name,
IF(NOT(ISBLANK(Session_Participation__c)), Session_Participation__r.Session__r.Name,
IF(NOT(ISBLANK(Membership__c)), Membership__r.Name,
IF(NOT(ISBLANK(Product__c)), Product__r.Name , &apos;&apos;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Custom__c.field-meta.xml
<CustomField>
    <fullName>Order_Custom__c</fullName>
    <label>Order Custom</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MembershipRenewalOrderTableController.cls
public with sharing class MembershipRenewalOrderTableController {
	public MembershipRenewalOrderTableController() {
	}

	public String orderId { get; set; }

	public Decimal orderTotalAmount { get; set; }
	public Decimal orderReceivedAmount { get; set; }
	public Decimal balanceAmount { get; set; }

	public List<OrderItemWrapper> getOrderItems() {

		orderTotalAmount = 0;
		orderReceivedAmount = 0;
		balanceAmount = 0;

		List<Order_Item__c> orderItems = [
			SELECT Id, Name, Name__c, Amount__c , Quantity__c, Total_amount__c, Order_Custom__r.Paid_Amount__c, Order_Custom__r.Total_amount__c, 
				Order_Custom__r.Total_Amount_Gros__c
			FROM Order_Item__c
			WHERE Order_Custom__c = :orderId
		];

		List<OrderItemWrapper> orderItemsList = new List<OrderItemWrapper>();

		orderTotalAmount = orderItems[0].Order_Custom__r.Total_amount__c != null ? orderItems[0].Order_Custom__r.Total_amount__c : 0;
		orderReceivedAmount = orderItems[0].Order_Custom__r.Paid_Amount__c != null ? orderItems[0].Order_Custom__r.Paid_Amount__c : 0;
		balanceAmount = orderTotalAmount - orderReceivedAmount;

		if (orderItems.isEmpty()) return orderItemsList;

		for (Order_Item__c orderItem : orderItems) {
			OrderItemWrapper orderItemWrap = new OrderItemWrapper();
			orderItemWrap.id = orderItem.Id;
			orderItemWrap.name = orderItem.Name__c;
			orderItemWrap.amount = orderItem.Amount__c;
			orderItemWrap.totalAmount = orderItem.Total_amount__c;
			orderItemWrap.quantity = orderItem.Quantity__c;
			orderItemsList.add(orderItemWrap);
		}
		return orderItemsList;
	}

	public class OrderItemWrapper {
		public String id { get; set; }
		public String name { get; set; }
		public Decimal amount { get; set; }
		public Decimal totalAmount { get; set; }
		public Decimal quantity { get; set; }
	}
}