force-app/main/default/objects/Chatter_Group_Settings__mdt/Chatter_Group_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Default chatteg group notification frequency settings.</description>
    <label>Chatter Group Setting</label>
    <pluralLabel>Chatter Group Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chatter_Group_Settings__mdt/fields/Chatter_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Id__c</fullName>
    <label>Chatter Group Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Chatter_Group_Settings__mdt/fields/NotificationFrequency__c.field-meta.xml
<CustomField>
    <fullName>NotificationFrequency__c</fullName>
    <label>Default Notification Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
                <default>true</default>
                <label>Every Post</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Daily Digest</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Weekly Digest</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CollaborationGroupMemberHelper.cls
public with sharing class CollaborationGroupMemberHelper {
    public static void setNotificationFrequency(List<CollaborationGroupMember> members){
        List<Chatter_Group_Settings__mdt> groupSettings = [
                SELECT Chatter_Group_Id__c, NotificationFrequency__c
                FROM Chatter_Group_Settings__mdt
        ];

        Map<Id, Chatter_Group_Settings__mdt> groupIdSettingsMap = new Map<Id, Chatter_Group_Settings__mdt>();

        if(!groupSettings.isEmpty()){

            for(Chatter_Group_Settings__mdt setting : groupSettings){
                groupIdSettingsMap.put(setting.Chatter_Group_Id__c, setting);
            }

            for(CollaborationGroupMember member : members){
                if (groupIdSettingsMap.containsKey(member.CollaborationGroupId)){
                    member.NotificationFrequency = groupIdSettingsMap.get(member.CollaborationGroupId).NotificationFrequency__c;
                }
            }

        }

    }
}