force-app/main/default/objects/Campaign_Names__c/Campaign_Names__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Campaign Names</label>
</CustomObject>

force-app/main/default/objects/Campaign_Names__c/fields/IPE_Name__c.field-meta.xml
<CustomField>
    <fullName>IPE_Name__c</fullName>
    <label>IPE Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Names__c/fields/Newsletter_Name__c.field-meta.xml
<CustomField>
    <fullName>Newsletter_Name__c</fullName>
    <label>Newsletter Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_credentials__c/MC_credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MC credentials</label>
</CustomObject>

force-app/main/default/objects/MC_credentials__c/fields/AuthUri__c.field-meta.xml
<CustomField>
    <fullName>AuthUri__c</fullName>
    <label>AuthUri</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_credentials__c/fields/SoapUri__c.field-meta.xml
<CustomField>
    <fullName>SoapUri__c</fullName>
    <label>SoapUri</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestService.cls
public class TestService {
    public static void insertMcCustomSettings() {

        Campaign_Names__c cmpgNames = new Campaign_Names__c();
        cmpgNames.Newsletter_Name__c = 'Test1';
        cmpgNames.IPE_Name__c = 'Test2';
        cmpgNames.Name = 'MC';

        insert cmpgNames;
        
        MC_credentials__c creds = new MC_credentials__c();
        creds.Name = 'MC';
        creds.ClientId__c = 'test';
        creds.ClientSecret__c = 'test';
        creds.AuthUri__c = 'test';
        creds.SoapUri__c = 'test';
        
        insert creds;
    }
}